### ISSUE TITLE
[Feature Request] Smoother UX flow to and from Quick Access

### ISSUE THREAD

**Issue by NinjaBoyLao** [d4rken-org/sdmaid#1043]
boi i bet youre tired of seeing me show up in your issues  

When on the Quick Access screen, if you tap one of the functions (App Cleaner, System Cleaner, CorpseFinder, etc) it takes you to a more detailed view of that function. If you then tap the back arrow (the one from Android UI that is sometimes a physical button on some phones) it then pulls out the left-side tray, rather than just kicking you back to the Quick Access screen.  

I'm not sure if this is by design but it would make it a lot easier if it just put you back on the Quick Access screen, so you could quickly check another functions details after you've done your scanning, or after doing a clean to see results.

**Comment by d4rken** [comment]
Hm, so like switching labels in GMail maybe... I'm not sure it's better though.

The back button works best when through hierachical layers but in SD Maid the tools are all on the same level.

**Comment by NinjaBoyLao** [comment]
right, so if you went into one tool, then hit the back button, shouldn't it take you back to the "quick access" layer? Or is the sidebar in between the topmost layer and the tool layers
