### ISSUE TITLE
Fuction about File Explorer

### ISSUE THREAD

**Issue by Edfgdz** [d4rken-org/sdmaid#1365]
Function[Open file in File Explorer] in Searcher is very good.Want add this function to CorpseFinder,System Cleaner and Duplicates.
![1512736959418](https://user-images.githubusercontent.com/26460124/33766633-64e8bc9a-dc59-11e7-8908-f43ffa56a9dc.jpg)

**Comment by d4rken** [comment]
- [ ] AppCleaner
- [ ] CorpseFinder
- [ ] Databases
- [ ] Duplicates
- [ ] SystemCleaner
