### ISSUE TITLE
Restrictions in exclusion

### ISSUE THREAD

**Issue by Edfgdz** [d4rken-org/sdmaid#1486]
Some files i want to exclude are distributed in file system. So i want to use regex to exclude them,but i find regex cant figure out file/folder difference in file system,therefore some folders whose names same as those files may be excluded without restriction. 

Like if i want to exclude[.nomedia] file with regex in Exclusion,but it will include[.nomedia]folders in exclusion,i want make it exclude more accurately.
This is just a example.

Can you add this three restrictions to Exclusions? Type,content and min/max size.

![1517376281643](https://user-images.githubusercontent.com/26460124/35606532-b202a2ec-068a-11e8-9734-93da0cd309e8.jpg)

**Comment by Edfgdz** [comment]
This restriction page should only pop up displaying when regex option is on.
When regex option in Exclusion isnt choosen this page can be hidden.

**Comment by d4rken** [comment]
That's a good idea. This way it will be less confusing who beginner users.

**Comment by Edfgdz** [comment]
I think it is better to remove minimum and maximum restrictions because these two restrictions may not be too much helpful for users who use regex to exclude.

**Comment by Edfgdz** [comment]
I rethought this issue and I think it is better to not hide these restrictions because users may also need these restrictions when they only use Path contains.

Although it could make restriction editing page more higher, I think it is better not to hide it.
