### ISSUE TITLE
secure file deletion

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid#152]
Originally reported by: **andrew foster (Bitbucket: [andysgenie](http://bitbucket.org/andysgenie), GitHub: [andysgenie](http://github.com/andysgenie))**

---

The ability in the file manager to select files and folders for secure deletion with selectable overwrites .
This would be a useful feature to have as everyone at some point has a file of some description ( an embarrassing photo for example ) that they would like to delete with the knowledge that it can never be recovered .
I suggest this feature of selecting files and folders to delete manually instead of a "wipe free space feature" which have unpredictable results , ranging from not doing anything to totally destroying everything not just the free space , depending on the device.
I have tried these programs in the past and found them  dangerously unpredictable. 

---
- Bitbucket: https://bitbucket.org/d4rken/sd-maid/issue/153

**Comment by d4rken** [comment]
AFAIK: Can't be reliably achieved due to too many differences between storage setups on all devices and ROMs. Promising anykind of secure file deletion would be missleading.

**Comment by itsarjunsinh** [comment]
+1
