### ISSUE TITLE
Appcontrol: Delete app but keep data

### ISSUE THREAD

**Issue by jancm** [d4rken-org/sdmaid#1551]
Using AdAway as example.

Following are left over files/directories associated with AdAway after "delete the app but keep the data". This list excludes anything on /sdcard or /data/data/<package-name>, which items are expected to remain.
---------------------------------

/data/system/package_cache/1/org.adaway-yo7YyzPgnnousF6-PsRpOA==-0

/config/sdcardfs/org.adaway:
appid
clear_userid
excluded_userids

/data/misc/profiles/cur/0/org.adaway:
primary.prof

/data/misc/profiles/ref/org.adaway:

/data/system/graphicsstats/1520121600000/org.adaway:
60/

/data/user_de/0/org.adaway:
cache/
code_cache/

---------------------------------
The following are the package* files in /data/system/ that contain a reference to AdAway within them 
---------
/data/system/package-cstats.list

/data/system/packages.xml

**Comment by d4rken** [comment]
Some thoughts for future me:

Some of these locations are not tracked by the corpsefinder, if we teach SD Maid to remove these too we basically have to teach SD Maids "FileForensics" about detecting ownership in those locations. Once that is done, adding corpsefinder filters for them would be trivial. The question is, would that be worth it?
Don't have much experience with these locations.

In case of the graphicsstats maybe we want to keep them? Though I think if the app is removed Android just shows a not useful random number within the stats, so it's almost impossible to identify the app anyways...

SD Maid internally also uses `pm uninstall -k` so these are also files the system itself leaves behind. But `uninstall -k` has a different usecase than what we use it for hm....
