### ISSUE TITLE
Deletion of duplicates based on metadata.

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid#163]
Originally reported by: **Bitbucket: [avamander](http://bitbucket.org/avamander), GitHub: [avamander](http://github.com/avamander)**

---

Could you please add a feature to Duplicates that allows finding the same songs (that MD5 doesn't match) based on the tags saved into the .mp3 file (default selection of finding dupes should be Artist+Title but there should be other options). Also there is no good looking app that does this on market so adding this feature would make SD Maid even more useful.

---
- Bitbucket: https://bitbucket.org/d4rken/sd-maid/issue/164

**Comment by peter9811** [comment]
+1
I needed, thanks
