### ISSUE TITLE
Scan /system for corpses

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid#1649]
> The problem is there is .odex files remaining after uninstalling system apps in both folders of 
/system/app
/system/priv-app

>My device is SM-A320F, Android N Stock

**Comment by d4rken** [comment]
> It depends on what system apps each person wants to uninstall, but for me, like, galaxy apps, google chrome and all samsung pre installed apps, like samsung keyboard, samsung memebers, etc.. 

> Samsung themes
/system/priv-app/SamsungThemes/oat/arm/

> Samsung voice
/system/priv-app/SVoice/oat/arm/

> Google chrome
/system/app/Chrome/oat/arm/

> Each odex file in these folders are like 0.6 megabyte
The google chrome odex file is 8.2 megabyte

**Comment by d4rken** [comment]
>This is a follow up, 
I think maybe you need to make sd maid to scan each folder for apk file, if apk file not found that means the app has been uninstalled, so sd maid will delete the while folder

> For example this filder for google chrome
/system/app/Chrome/
If no apk file found, just delete it..

**Comment by d4rken** [comment]
> The things is,, if it is a system app then the pre installed version apk file will still be in the system/app folder.. So the folder wont be deleted by sd maid

> For example google drive
There is 2 folders in my phone
System version is here, as if you disable or uninstalled the newer version it will go back to the preinstalled veraion which is in this folder
/system/app/Drive/

>This is the folder after a drive is updated
/data/app/com.google.android.apps.docs-1/

> And i also checked some of the other apps like
Google play
Google services
Samsung AOD
Samsung Email

**Comment by Pimmakon** [comment]
Good
