### ISSUE TITLE
Sort in Searcher

### ISSUE THREAD

**Issue by Edfgdz** [d4rken-org/sdmaid#1655]
Wish you can add sort options as drawer style menu in Searcher like in AppControl.
You can add two options,one is option that sort file/folder with name,size,date,type.
Another option is that descend or ascend those results.
At the same time,wish you can make folder result in front of files result.

Maybe you can add descend/ascend options in AppControl too.

**Comment by Edfgdz** [comment]
Will you add that in AppControl too?

**Comment by d4rken** [comment]
I can, can you make an extra ticket for AppControl?

Each tool is still scheduled for a UI rework, I can make such changes then.
