### ISSUE TITLE
Replace the `Overview` list entry with a status button in the header

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid#1744]
Since the `Overview` page is somewhat a niche info page we could remove it's entry in the list of tools and instead add an `Info` or `Status` button to the header graphic in the navigation drawer.

Thoughts?

**Comment by mcl21014** [comment]
Any concept imagery?

**Comment by d4rken** [comment]
Nope, just an idea atm.

I'm open for suggestions and concept images 😉
