### ISSUE TITLE
Show badge-style shortcut to help on first launch

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid#1745]
Similar to the changelog entry in the navigation drawer each update, we could show an entry on first install or each update  that takes the user to SD Maid's wiki (if the system language is english).

**Comment by Georgious40** [comment]
Just bought a lenova haloA12.&i would like to enhance & streamline for necessites;&fast processing .D-load files&app storage listing & activation with quality ,&sharp crisp pictures& sound capability. Firmware , parts or apps too os ? Any Help ,appriciated please! It
.runs android6.0.1 sdk23, operating system.kernal-linux version 314.55x86_641(queen@fyy.smblosfyy)gcc.version492(gcc)#1smp preempt.Dec 28 2018.
