### ISSUE TITLE
Add shortcut near basepath in Userfilter 

### ISSUE THREAD

**Issue by Edfgdz** [d4rken-org/sdmaid#1754]
Is it possible to add a shortcut near basepath to make user directly go to Explorer to add more pathes?

![1529903594186](https://user-images.githubusercontent.com/26460124/41831481-e4121706-780c-11e8-8bf0-791e66f525c0.jpg)

**Comment by Edfgdz** [comment]
Don't add this feature in the near furure, I have another idea to replace it.

It is better to put this ticket aside at present.

**Comment by Edfgdz** [comment]
I have another idea.

Is it possible that when users in userfilter editing page, users can slide out sd maid left drawer and click into Explorer to copy files /folders paths and click SystemCleaner again into editing page to add paths?

I think this is better.

**Comment by d4rken** [comment]
> Is it possible that when users in userfilter editing page, users can slide out sd maid left drawer and click into Explorer to copy files /folders paths and click SystemCleaner again into editing page to add paths?

Not possible in the current userinterface, changing it would be like a whole rewrite.

It would be easier, but still a lot of work, to create a "file picker" dialog/screen. Some of the settings already have that, maybe it can be reused.
