### ISSUE TITLE
Request: Create copies of file in the same directory with a different name.

### ISSUE THREAD

**Issue by mcl21014** [d4rken-org/sdmaid#1821]
### What should the feature do?
Copying a file named sample for example and pasting into the same directory should result in sample(1) being created. Currently SD Maid does nothing.

### When/How would you use it?
Every time I want to copy and paste a file within the same directory.

### How would you implement it?
Using the existing copy and paste functionality, paste would turn a file named sample to sample(1) or something similar. Name it like Windows would to make it more familiar to users.

### Comments
Will be useful for testing a Duplicates bug.

### SD Maid
Version: `4.11.3 (41103)`
Unlocker: `4.3.0 (40300) (true)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `google/marlin/marlin:9/PPP4.180612.004/4838310:user/release-keys`

**Comment by d4rken** [comment]
The current architecture does not support copy/move + rename in the same step, implementing this is much more work than I thought.

**Comment by d4rken** [comment]
v4.14.0 will offer better feedback though.
