### ISSUE TITLE
Searchfield for the current path

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid#1967]
> I I contact to report a fault that happened to me not long ago, and I'm not sure in the search if time or searches, conflict and no longer seeks anything, it would be good that could be arranged, too I propose to include the search in the file browser to search within a folder in which I find myself without having to search globally.

> 1. Can you explain a little more when you would use this feature?
> -Imagine, I want to find a file within a specific folder, within this folder I have more than 100 files and it would be a cumbersome task to search one by one, the option would be in the bar of more options, there a search magnifying glassI can search the content while I write it, and so I will find the file more quickly.

>2. Do you have any idea where you should add it?
> -Sleeping aside from the options points, or in the options strip.

> 3. Just one option in the menu when the elements are selected?
> -I consider that it would not be a good idea for this action to be executed with the selected elements, but if once I am inside the folder n
would be very helpful if we had these changes available, in my case, I move from one folder to another and I have many files, this app makes many of these things easier, I like the ease in which I can use it.
Apology for the translator

**Comment by d4rken** [comment]
Something like the search field from, e.g. Duplicates could work here.

**Comment by Kilincs** [comment]
# 1967
