### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by rakleed** [d4rken-org/sdmaid#2058]
Add support for shortcuts.

https://developer.android.com/guide/topics/ui/shortcuts/

**Comment by d4rken** [comment]
Please be more specific, what should the shortcuts do?

**Comment by d4rken** [comment]
Lack of info, reopen if needed.

**Comment by Rakleed** [comment]
<details><summary>Screenshot with Pocket Casts</summary>

![screenshot_20181029-120100_nova_launcher 1](https://user-images.githubusercontent.com/19418601/47640527-d7eb2000-db74-11e8-832a-10ad70e0273b.png)

</details>
Your application may have the following shortcuts: QuickAccess, CorpseFinder, SystemCleaner, AppCleaner, Database, etc.

**Comment by d4rken** [comment]
Clicking such a shortcut would open that tool? Should it start an action or just open it?

**Comment by Rakleed** [comment]
@d4rken probably should start the action. But then you should call "Start CorpseFinder", etc., to make it clear.

**Comment by signoraria** [comment]
Im 100% agree with @Rakleed, should start the action but without "execute".

Example, you press shortcut appcontrol, the appcontrol just start the action for scanning.

So the point is when we press the shortcut, the shortcut automatically scanning ur device.
