### ISSUE TITLE
Check mount matching and remount behavior on systemless root setups

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid#2135]
See https://github.com/d4rken/sdmaid-public/issues/2110#issuecomment-440325101

**Comment by d4rken** [comment]
On @toledofaustino85's LOS setup ([see](https://github.com/d4rken/sdmaid-public/issues/2110#issue-377227325)) SD Maid already correctly maps the `SYSTEM` storage to mountpoint `/` 

```
Storage(location=SYSTEM, path=/system, userHandle=-1, flags=[PRIMARY], safUri=null, mount=Mountpoint(path=/, blockDevice=/dev/root, fileSystemType=EXT4, options=[relatime, seclabel, data=ordered, ro]))
```

this is due to us searching hierarchical along the path of `/system` and ending up at `/`.

So systemless `/` works and the default `/system` works. The only issue here would be the edge case where `/system` is a symlink and the actual mount is `/system_root`. Possibly on older SuperSU setups, still unconfirmed though.

My first thought would be to check whether `/system` is a symlink and if so, follow the link and resolve the mount of it's link target. Hm, can we read this via java's fs calls? Does the Storage class generation tool have access to a root shell? Do we need root to determine this?

Androids API offers `Environment.getRootDirectory()`, I wonder what that returns on such a symlinked setup...

**Comment by toledofaustino85** [comment]
> Currently we want to write something that devices whether the mount applet is usable, as quickly as possible. To do this we attempt to remount "the system partition".

Ok, I understand. With the information we have available until now I propose the following logic:

Try /system
If no error then goto :additional_checks
else
check ro.build.system_root_image
If "true" then try "/"
If no error then goto :additional_checks //false alarm, all be ok, its a "new phone"
else goto :we_have_a_problem
else goto :we_have_a_problem
endif
endif
endif

:additional_checks
try /system_root (optional and for info. purposes)

:we_have_a_problem
run panic_mode (maybe applet does not works...)

Better?

**Comment by gitVictim83** [comment]
To everyone here..a big thank you for destroying my entire life! I lost my job, lost my kids and now, im about to lose my life..i a great pleasure not hearing my side of the story before doing this to me..one of u here, knows the true story and everything happnd..and for those who dont believe me, please check out my microsoft one drive or google drive using this email..since u guys have done these, and ruined my whole year, not gving u my password will not be a problem..again, thank u everyone..and i hope none of these happens to anyone of u..tc and god bless..

**Comment by gitVictim83** [comment]
And bro...thanks foe welcoming me to ur  family..sorry i didnt haa thed chance to catch amd say gudbye..u knw who u are..no bad blood..for me, were still bros.. "de gustibus non desputandum est..." salute kapatid.. 😊✋
