### ISSUE TITLE
Priority selecting of duplicates

### ISSUE THREAD

**Issue by Makarnak** [d4rken-org/sdmaid#2167]
Well, say you download a bunch of PDFs into the download folder, an app download folder and another app download folder, and maybe you have more that are copied over from an old device into another directory. Then you have a directory that is where you keep the ones you want to keep in an organized way (by subject/author/etc.). They all have unhelpful names like 104058666.pdf.

Now, you have a bunch of files that you've downloaded different ways, that are scattered throughout the download folders, but you want to make it as easy as possible to find the ones that aren't duplicated (say ones that were downloaded in sequence that were created by the same author in your download folder, as opposed to more random ones in the other directories).

Ideally, you want to keep the ones in your organized archive before the others. Then, the next best directory would be the download folder (because a bunch were downloaded in sequence by author), then the other directories down the line.

It would be helpful to set up a list of directories that are prioritized, like this:

Organized directory
Download folder
Copied from old device directory
App Download Folder
App Download Folder 2

Then be able to say 'Autoselect least preferred directories'. The autoselect would select the ones that were in the lowest directory first.  Say a file was in the Organized directory, the old device directory and App Download Folder 2. The Autoselect would choose the App Download Folder 2 copy and the Old Device copy, leaving the one in the Organized directory alone. 

Basically, it will autoselect all of the lower directories on the list first, leaving whichever is the top directory's copy alone.

The PC app Visipics does this when searching for duplicate photos, and it's very useful for when you're archiving and trying to sort identical but differently organized photos. 

The way they implement it is to put the priority in the order you added the directories, with the 'keep' directories added first. You can sort the order using arrows buttons.

(I just had another idea, something I wish visipics does. It would be less important when searching identical files (like SD Maid does), but still useful for people sorting items: the ability to send a duplicate to a directory rather than deleting it? But I digress.)

In a way, SD Maid kind of does this when you choose to prefer external SD card or internal storage. I've been using it that way, but when downloading a ton of files, I run out of room on the internal and move them to a folder on the external to sort later, which makes it less useful. I could also game the 'deeper directory' setting and just make my sort folder buried in a long directory name, but it would be easier just to be able to prioritize directories.

Thank you.

**Comment by marlenehstack** [comment]
Duplicates stop at 45%, can't seem to get beyond that.

**Comment by d4rken** [comment]
@marlenehstack please open a new issue for that.
