### ISSUE TITLE
Updated system applications require 2 uninstalls

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid#220]
Originally reported by: **Bitbucket: [d4rken](http://bitbucket.org/d4rken), GitHub: [d4rken](http://github.com/d4rken)**

---

Currently uninstalling an updated system app in AppControl will first uninstall the update, then after a rescan, the app from /system will be uninstalled.
- Should this happen in one pass?
- Should this not happen in one pass, but be a setting?
- Should "Reset to install state" not only wipe data, but also uninstall the update and "delete app" delete all in one pass?

Also see:
http://forum.xda-developers.com/showthread.php?t=1013063&page=206

---
- Bitbucket: https://bitbucket.org/d4rken/sd-maid/issue/221

**Comment by d4rken** [comment]
From #411:

> Delete the app and its data -> delete app, data, updates
> Resets the app to its first install -> delete data, updates
> Delete data -> delete data

> So basically the current 'Resets the app to its first install' would become 'Delete data'
> This would be in line with the description provided by the wiki "Returns the app to it's install state."

**Comment by carlosnewmusic** [comment]
my still not cleared, remain in cleaning system for example some of google
