### ISSUE TITLE
[REQUEST/SUGGESTION] Option to sort files by size, type, date, etc

### ISSUE THREAD

**Issue by zombosses** [d4rken-org/sdmaid#2200]
Hi,

I think adding an option to sort files while in app & system clear, after tapping the “i” icon beside the app info given could help people understand what type of files are being created, how big they are, when they were created, etc.

Thank you!

 ( here are some screenshots https://i.imgur.com/ZakPKHS.jpg https://i.imgur.com/EOIrJTD.jpg)

**Comment by d4rken** [comment]
What do you mean by "type"?

**Comment by zombosses** [comment]
Type as in file type, like .apk, .jpg, .zip, .mp4, .img, etc.

**Comment by zombosses** [comment]
I can't believe it's been a year

**Comment by d4rken** [comment]
Some requests just draw the short straw when I try to allocate my time :frowning:
