### ISSUE TITLE
System Cleaner User Rule Export Proposal

### ISSUE THREAD

**Issue by Vstory** [d4rken-org/sdmaid#2327]
When the user rules of the system cleaner are exported, the text content is very confusing, and there is no such thing as automatic line breaks.

[Ideal export status](https://i.loli.net/2019/02/23/5c714b0c043f2.png)
[Actual export](https://i.loli.net/2019/02/23/5c714b357f553.png)

The file name of the exported rule file should not be randomly generated.
Can the rule name be exported using the name of the creation rule?

**Comment by d4rken** [comment]
Formatting the export should be no problem.

The random name was "cheap" way to ensure no collisions, because the file manager used to pick the path does not yet support name collision detection.

The filepicker/manager used for options like this needs a rework too, I'll look into it.

**Comment by Vstory** [comment]
@d4rken The exported rules I want to merge into a single profile export. Can you support this situation?

**Comment by d4rken** [comment]
Sure, sounds like a good idea.
Please make a new ticket for this, smaller tickets are more fun to work on because they can be closed sooner, after each new feature :grin: .

**Comment by Vstory** [comment]
> Sure, sounds like a good idea.
> Please make a new ticket for this, smaller tickets are more fun to work on because they can be closed sooner, after each new feature 😁 .

Create a new issue?
