### ISSUE TITLE
apk installer task shown in recents 

### ISSUE THREAD

**Issue by ChristophHeilmann** [d4rken-org/sdmaid#2645]
Marshmallow 6.01, Sony Tablet Z4

When I open an apk with the file explorer and use the default Android apk installer, the install task of the Android installer will be shown in the recents app screen, although in the manifest of the Android installer app excludeFromRecents is set to true.

**Comment by d4rken** [comment]
Hi,

What SD Maid version?

Is the reproducible every time?

**Comment by ChristophHeilmann** [comment]
Hallo,

Ich habe die 4.14.14 auf dem Gerät und das Verhalten ist mit verschiedenen apks jederzeit reproduzierbar. An Marshmallow kann es nicht liegen, denn beim Solid Explorer erscheint der Installer nicht auf dem Recents-Bildschirm wenn ich eine apk öffne.

**Comment by d4rken** [comment]
Using `Intent.createChooser(....)`, adding `FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS` manually has no effect.

Solid Explorer seems to use it's own "chooser" component, where as SD Maid uses the system one.

Not using the chooser would remove the ability to "open with".
The equivalent solution would be write an additional "chooser" component.
