### ISSUE TITLE
Scan & Execute function working incorrectly.

### ISSUE THREAD

**Issue by sp1cyf0x** [d4rken-org/sdmaid#2692]
After the app finished `Scan & Execute` action, it suppose to open the `QuickAccess` page in-app to show results.
![Screenshot_20190610-185238_One UI Home](https://user-images.githubusercontent.com/24849056/59195092-45543a00-8bb5-11e9-86f2-430e07bad196.jpg)
![Screenshot_20190610-185008_Discord](https://user-images.githubusercontent.com/24849056/59195097-49805780-8bb5-11e9-9bc2-97031911c195.jpg)

**Comment by d4rken** [comment]
Some more thoughts, if this can be disabled, we still have the problem of #2686 which would be even more apparent then.

So #2686 would have to be fixed before it really makes sense to fix this :frowning:.
