### ISSUE TITLE
Add deleting old call logs and SMSs/MMSs

### ISSUE THREAD

**Issue by Avamander** [d4rken-org/sdmaid#272]
It would be nice if there would be a old call log, SMS and MMS deletion function. 

User could be asked on first startup if he/she cares about old SMSs, MMSs or call logs (older than a certain time period). 

| Would you like to delete: | (These preferences can be changed in the settings) | (Tap to enable deletion) | _ |
| --- | --- | --- | --- |
| Old call logs older than | (clickable) 15 days | (clickable) 30 days | (clickable) 90 days |
| SMSs and MMSs older than | (clickable) 15 days | (clickable) 30 days | (clickable) 90 days |

**Comment by D0r4** [comment]
Would b very convenient:-)
