### ISSUE TITLE
Force Media Scan... 

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/sdmaid#2896]
Good day,

The force media scan feature doesn't seem to have any effect. The gallery apps continue to display thumbnails of files already deleted. This is the only app I found to work nicely:

https://play.google.com/store/apps/details?id=com.house.noranuko.mediarescanner

Kindly fix so we don't have to install another app just for this feature.

Also, please provide this option under quick access, so that every time we run SD Maid, it can automatically force a media rescan.

Thank you.

**Comment by d4rken** [comment]
Forced media scanning can only ADD files, not remove them AFAIK. So to remove them we might have to wipe the database and rescan? Hm that doesn't integrate nicely with the way this is currently setup as Explorer action...

**Comment by TheMysticS** [comment]
I don't know how that app successfully forces a proper Android Media Scan. It has always worked for me, even when other apps I tried failed to make any difference.

For example, when the gallery app shows blank thumbnails or thumbnails of pictures deleted, even a restart has failed to sort this out on a few occasions. But the Media Rescan app linked above has always worked for me in removing blank thumbnails or thumbnails of pics already deleted.

I don't know if you have a way of checking what that app does to make this work successfully.

The app was last updated in 2018, but it works properly even on Android 11.
