### ISSUE TITLE
AppCleaner: ACS: Improve locale support on Samsung OneUI ROMs

### ISSUE THREAD

**Issue by MeloriTensei** [d4rken-org/sdmaid#2909]
This post is updated to fit the current goal of covering 100% of OneUI 3.0 locales.
For now, I'm the only one pushing for full support.
13th Sept 2021 Update: Wew... I've finished OneUI 3.0, and Samsung announced 4.0, great day, people! ><

This is similar to #2847 where I try to cover locale support for that particular ROM (Samsung Pie/OneUI for this case).  If you got a phone that rocks on a Samsung OneUI 3, you can help contributing to this by following this pattern:
(Top of #2802 for more info)
[If you know how to write EXACTLY what the text says follow this.  Otherwise, look below.]
1) Go to Settings > Apps > (Any app of your choice, I suggest Google Photos).
2) Take a screenshot of the page of the app, also write down what it says on the "Storage" button of that page in a text file. 
[(Example 1)](https://ibb.co/Sc57v4r) [(Example 1 button)](https://ibb.co/9ycMnS4)
3) Enter the storage page, take a screenshot and write down what it says on the "Clear Cache" button.
[(Example 2)](https://ibb.co/5v1cWhx) [(Example 2 button)](https://ibb.co/djZxzMX)
4) Gather the screenshots and the transciptions into a zip file and post it here :)

[If you do not know how to write in that language but still wanna help, here's how]
1) Open SDMaid, open up the side menu, hold down the settings button, press RECORD DEBUG LOG.  Then, press DEBUG ACCESSIBILITY SERVICE.
2) Open side menu then navigate to AppCleaner.  Use AppCleaner and search.
3) Click on any app of your choice by it's icon (I suggest Google Photos).
4) Take a screenshot of the page of the app and press the "Storage" button (of that language).
[(Example 1)](https://imgur.com/a/JC5TNfC)
5) Take a screenshot and press "Clear Cache" button (of that language) then press the X button on the Debug overlay.
[(Example 2)](https://imgur.com/a/aGqOElM)
6) Go back to SDMaid then pull up the notifications.
7) Press done on the dialog "Debug log is recording..." (Expand the notification if necessary)
8) Collect your log at (sdcard)/Android/data/eu.thedarken.sdm/cache/logfiles
9) Gather your log file and screenshot and zip it and post it here :)

[Post your findings in this pattern so it's easy for us to read it]
Language: `(Language) - (Writing system/Region)`
Locale ID: `(put it if you know.  **en_US** is American English)`
Files: `(blah blah blah.zip)`

I aim to cover ALL languages ever existed on the languages list, so, any possible help will be GREATLY APPRECIATED.  In event Samsung decides to change the texts for those button on certain languages and break our current line of text, please do report it to us here.  We will look into it and update it. :)

Anyways, good luck reporting. 😄

**Comment by JeffHorinzon** [comment]
[RESERVED FOR SUPPORT STATUS]

**Comment by d4rken** [comment]
> AOSP deletion pattern, english works but other translations differ from AOSP ones

**Comment by JavkhlanK** [comment]
(German) - (samsung/a70qeea/a70q:9/PPR1.180610.011/A705FNXXU3ASG6:user/release-keys, Region: AT)
(**de_AT**)
([Language_deAT.zip](https://github.com/d4rken/sdmaid-public/files/3634963/LanguageDE_at.zip))

**Comment by d4rken** [comment]
#3036 improves support for Samsung devices on Android 10.
