### ISSUE TITLE
Support ACS based cache clearing on ColorOS ROMs

### ISSUE THREAD

**Issue by MeloriTensei** [d4rken-org/sdmaid#2910]
Apparently, it's something that needs a hecka long time for us to figure out how to get this working.  I personally reported this to darken and he's aware of this.  So, here's the context:
```
ColorOS's menu pattern is hella different from Samsung OneUI, AOSP and MIUI.  Everything we need is not in it's own category but IN ONE PAGE, which "wasn't engineered" yet for such scenario.  
```
So, this ticket is basically to begin support ColorOS as a base first.  Further locale support will come on another comment below.  What me and Boss (D4rken) needs is a debug log for ColorOS of different scenarios, such as small screens where scrolling is needed to reach the "Clear Cache" button and so on.
[Here's the guide for recording the debug log]
```
1) Open SDMaid, open up the side menu, hold down the settings button, press RECORD DEBUG LOG.  Then, press DEBUG ACCESSIBILITY SERVICE.
2) Open side menu then navigate to AppCleaner.  Use AppCleaner and search.
3) Click on any app of your choice by it's icon (I suggest Google Photos).
5) Press "Clear Cache" button then press the X button on the Debug overlay.
6) Go back to SDMaid then pull up the notifications.
7) Press done on the dialog "Debug log is recording..." (Expand the notification if necessary)
8) Collect your log at (sdcard)/Android/data/eu.thedarken.sdm/cache/logfiles
9) Gather your log file and post it here :)
```
[Post it in this format so we can easily understand]
```
Device: (Phone model) - (Codename if known) [Eg. Oppo F5 - CPH1723]
Android version: (ColorOS version) - (Android version) - (Patch period if known) [Eg. ColorOS V3.2 - Android 7.1.1 - July 5, 2019 Patch]
Language: (Language) - (Language code if known)
Additional info: (add any extra that might help) [Eg. Font size is set 125%]
File: (log file goes here) (screenshot is optional but helps)
```

Hopefully, we can get SDMaid to work with ColorOS sooner.  Good luck and happy reporting! 😄

**Comment by JeffHorinzon** [comment]
[RESERVED FOR ANY PURPOSE]

**Comment by JeffHorinzon** [comment]
Device: Oppo F5 - CPH1723
Android version: ColorOS V3.2 - Android 7.1.1 - July 5, 2019 Patch
Language: English (United States) - en_US
Additional info: Font size is set 125%
File: [sdmaid_logfile_1567358322575.txt](https://github.com/d4rken/sdmaid-public/files/3563750/sdmaid_logfile_1567358322575.txt)

**Comment by dragonGod97677** [comment]
Device: OPPO A3s - CPH1803
Android version: v5.2.1 - 8.1.0 - January 5 2021
Language: English US - (i dont know)
Additional info: font is set to smallest possible and dp is set to 360
File: 
[sdmaid_logfile_1624296233211.txt.zip](https://github.com/d4rken/sdmaid-public/files/6688500/sdmaid_logfile_1624296233211.txt.zip)
![Screenshot_2021-06-22-01-35-57-25](https://user-images.githubusercontent.com/38875906/122804535-9cd82500-d2fa-11eb-9cbd-0a4981e7acfa.png)

Video of it https://youtu.be/YoOZLWPnvjc

SD maid version: 5.1.5
