### ISSUE TITLE
In a specific partition, do not distinguish between the case of the path

### ISSUE THREAD

**Issue by Vstory** [d4rken-org/sdmaid#3073]
I don't think there is a need to distinguish between path case when PUBLIC_DATA & SDCARD is specified.This makes it easier for users who are not familiar with regular expressions to create rules.
Or provide an option to decide whether to distinguish between path case.
#3062

**Comment by d4rken** [comment]
Additional thought.
While SDCARD and PUBLIC_DATA on primary public storage (e.g. `/storage/emulated/0`) is case-insensitive, SDCARD and PUBLIC_DATA on secondary public storage (e.g. /storage/1234-ABCD/) can be case sensitive, can't it? E.g. external sdcards with EXT4 are supported?

**Comment by d4rken** [comment]
Looked a bit more into this, note: Having to lookup locations prior to comparisons will decrease scan speed a lot. Currently it's the last comparison because the lookup to determine the storage type is very expensive.
