### ISSUE TITLE
[Theme] Dark mode for navigation bar.

### ISSUE THREAD

**Issue by sp1cyf0x** [d4rken-org/sdmaid#3259]
I think there's a code to change the navigation bar theme to dark mode. If possible, please make it transparent so users can see more contents on the screen. (If you add it then also add settings to change between those)
![Screenshot_20200115-114440_SD_Maid](https://user-images.githubusercontent.com/24849056/72581608-89a97480-3912-11ea-817b-ce8b4fd31563.jpg)

**Comment by d4rken** [comment]
What OS/API level is this?

**Comment by spicyfoxx** [comment]
> What OS/API level is this?

OneUI 1.1 based on Android 9 Pie, API level 28.
