### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by Da-OldMan** [d4rken-org/sdmaid#334]
The RTL implementation of SdMaid beta 4.0.10 is not correctly done:
1) Navigation drawer is on the left side
2) In the navigation drawer all items that have image are LTR , and those that are just text are RTL .... complete salad. Also the title is LTR
3) Translation to hebrew is not full, if you want I can take a look at it when I have time or ask the original translator to help out
4) In app some things like "in queue" are RTL, some LTR

**Comment by JeffHorinzon** [comment]
@Da-OldMan If you wanna volunteer completing Hebrew localization, you can apply yourself here: https://crowdin.com/project/sdmaid/he
