### ISSUE TITLE
Support for Accessibility Service based cache deletion on MIUI 11

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid#3349]
Looks like the UI changed. I'll need a few people with this type of ROM to provide a debug log of SD Maid failing on that screen.

Preferably one in English and one in your native language (change the system language, not the one in SD Maid).

https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

![Screenshot from 2020-03-07 11-52-44](https://user-images.githubusercontent.com/1439229/76142049-2f06dc00-606a-11ea-86dc-89002fe5778e.png)

**Comment by turbo25** [comment]
![IMG-20211230-WA0001](https://user-images.githubusercontent.com/9088592/147760603-e257904d-5349-480a-95c8-f7a03cbee6e6.jpg)
![IMG-20211230-WA0002](https://user-images.githubusercontent.com/9088592/147760600-fd2c5def-4133-4f65-b85a-47cfa0a00169.jpg) 
![IMG-20211230-WA0003](https://user-images.githubusercontent.com/9088592/147760613-17bc7637-75c8-492c-9189-de3bda533dab.jpg)
![IMG-20211230-WA0000](https://user-images.githubusercontent.com/9088592/147760615-62a14d01-b12e-454d-8ffa-2532f5f1f872.jpg)

**Comment by d4rken** [comment]
Thanks, can you provide a debuglog? 

https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log

**Comment by turbo25** [comment]
[sdmaid_logfile_1641387895973.txt](https://github.com/d4rken/sdmaid-public/files/7815166/sdmaid_logfile_1641387895973.txt)
