### ISSUE TITLE
wechat in the bugreporting filter

### ISSUE THREAD

**Issue by redjumper** [d4rken-org/sdmaid#3354]
see https://github.com/d4rken/sdmaid-public/issues/1907
the bugreporting filter 			

>  			"^(?>tencent\\/MicroMsg\\/crash\\/)([\\W\\w]+?)$",
> 			"^(?>tencent\\/MicroMsg\\/xlog\\/)([\\W\\w]+?)$",
> 			"^(?>tencent\\/MicroMsg\\/locallog\\/)([\\W\\w]+?)$",
> 			"^(?>tencent\\/MicroMsg\\/watchdog\\/)([\\W\\w]+?)$",
> 			"^(?>tencent\\/MicroMsg\\/failmsgfilecache\\/)([\\W\\w]+?)$",
> 			"^(?>tencent\\/MicroMsg\\/)(FTS5IndexMicroMsgInfo.txt)$",
> 			"^(?>tencent\/MicroMsg\/[0-9a-z-]{32}\/logcat\/)(?>.+)"

maybe the last line should be
> 			"^(?>tencent\\/MicroMsg\\/[0-9a-z-]{32}\\/logcat\\/)(?>.+)"

**Comment by d4rken** [comment]
Thanks! Will look into this, I think the additional escape is optional though.

**Comment by d4rken** [comment]
Was optional, but I've cleaned it up anyways.

https://github.com/d4rken-org/sdmaid-se/pull/495

**Comment by Darby101** [comment]
> Thanks! Will look into this, I think the additional escape is optional though.
