### ISSUE TITLE
Feature request - use checkbox to enable multiple user filters

### ISSUE THREAD

**Issue by redjumper** [d4rken-org/sdmaid#3374]
It's inconvenient when there are a lot of user filters and want to enable them . Maybe sd maid could use checkbox to select and enable multiple filters , and this could apply to all filter operation not just user filters only .

**Comment by d4rken** [comment]
It takes just one tap to enable a filter though, right?

If we add multi selection, then it still takes 1 tap for each filter + 1-2 taps at the end.

**Comment by redjumper** [comment]
You're right, but we may still need a button to  enable all selected filters.  ![16o4f-1hppe](https://user-images.githubusercontent.com/16910542/77426997-89e15700-6e10-11ea-8e18-2c1532434247.gif)
And when importing filters, an import and enable all filters option is very useful.

**Comment by d4rken** [comment]
I will look into it.
Will depend on how much work the code for this is.
