### ISSUE TITLE
Restore default exclusions (without wiping data)

### ISSUE THREAD

**Issue by megapro17** [d4rken-org/sdmaid#3382]
If I add them manually, they will always be shown, even when "show default exclusions" option is disabled. Why this obvious feature is not exist?

**Comment by d4rken** [comment]
> Why this obvious feature is not exist?

You are the first one to ask for this in 7+ years :wink:

**Comment by megapro17** [comment]
Bruh, why

**Comment by d4rken** [comment]
Feature stop for SD Maid 1.
https://github.com/d4rken-org/sdmaid-se/wiki/FAQ#why-are-you-creating-sd-maid-se

New features only in SD Maid 2:
https://github.com/d4rken/sdmaid-se

**Comment by megapro17** [comment]
Okay, but make ability to buy it using unlocker app, so it can be shared with family
