### ISSUE TITLE
Idea: Check if the app is using battery in background > The app is running.

### ISSUE THREAD

**Issue by idriss1991** [d4rken-org/sdmaid#3385]
Idea: Check if the app is using battery in background > The app is running.

_Originally posted by @spicyfoxx in https://github.com/d4rken/sdmaid-public/issues/946#issuecomment-499424499_

**Comment by d4rken** [comment]
That's not a bad idea.
What permission do we need for this?
What's the data resolution, i.e. how often is it updated?

**Comment by Chacha4149** [comment]
**Would be awesome... **

**Comment by Chacha4149** [comment]
What happened to idea...? Just curious ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by d4rken** [comment]
Never found a 100% solution for it an decided it is too confusing then.
