### ISSUE TITLE
Bug: AppCleaner crash, too many files. Exclusion not working 

### ISSUE THREAD

**Issue by whinette** [d4rken-org/sdmaid#3433]
# What happened?
Sdmaid closed while scanning path contained if a excluded one.

### What did you expect to happen?
Sub path of exclusion defined shouldn't be scanned

### How can I reproduce the issue?
Have too many files to trigger out of memory error (suspected) 

### Comments
I have about 1M files on SD card.
SDMaid crash after a while when AppCleaner is ran.

Exclusion list doesn't seem to work:
I've excluded the whole SD card. The path are still analysed in all tools.
Exclusion is `/storage/XXXX-YYYY`, added from builtin explorer.
Tried with a terminal slash, also with path of the root folder containing the files.

This looks similar to https://github.com/d4rken/sdmaid-public/issues/2843

### SD Maid
Version: `4.15.8 (41508)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `Sony/SGP611/SGP611:6.0.1/23.5.A.1.291/713254892:user/release-keys`

[sdmaid_logfile_1587459299608.txt.zip](https://github.com/d4rken/sdmaid-public/files/4508909/sdmaid_logfile_1587459299608.txt.zip)

**Comment by whinette** [comment]
:(

**Comment by d4rken** [comment]
If this is still an issue in SD Maid 2, please raise a new ticket:
https://github.com/d4rken-org/sdmaid-se
