### ISSUE TITLE
The total size of the data being cleared is not displayed correctly

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#3441]
Meizu M8
Android: 8.1.0
No root
SD Maid v4.15.8, Unlocker v4.4.1
install ID:
b38bd81e-8c54-47ed-a238-503cec388423

После сканирования SD Maid отображает неверный суммарный объём данных, которые будут удалены. Не обратил внимания, было ли это изначально, но уже давно. SD Maid переустанавливал.

[sdmaid_logfile_1587792058583.txt.zip](https://github.com/d4rken/sdmaid-public/files/4532415/sdmaid_logfile_1587792058583.txt.zip)

![S00425-082400](https://user-images.githubusercontent.com/60130882/80272194-f4b3d580-86cf-11ea-9de7-9bacc438bd40.png)

**Comment by d4rken** [comment]
Does it happen everytime?

What steps did you take? Just press scan?

**Comment by programmist87** [comment]
Каждый раз. Просто при нажатии на сканирование.

**Comment by programmist87** [comment]
Проблема в новой версии осталась

**Comment by d4rken** [comment]
How huge is the difference? Does it come from a specific tool?

**Comment by programmist87** [comment]
В инструментах CorpseFinder и Databases.

[sdmaid_logfile_1592555655133.txt.zip](https://github.com/d4rken/sdmaid-public/files/4803574/sdmaid_logfile_1592555655133.txt.zip)



![S00619-113614(1)](https://user-images.githubusercontent.com/60130882/85116162-9285d580-b225-11ea-8464-e805946130ac.png)
![S00619-113725(1)](https://user-images.githubusercontent.com/60130882/85116175-97e32000-b225-11ea-89d9-78de0d40defb.png)
![S00619-113740(1)](https://user-images.githubusercontent.com/60130882/85116185-9c0f3d80-b225-11ea-8592-f0ea1094126f.png)

**Comment by d4rken** [comment]
The database size is a "worst case" guess, it's not possible to accurately predict how much will be freed when vacuuming the databases.

The CorpseFinder size should be correct though.

Can you show me which corpses were found? I think it might be related to folders with files inside them, where SD Maid only counts the folder, but not the content.

**Comment by d4rken** [comment]
The database size is a "worst case" guess, it's not possible to accurately predict how much will be freed when vacuuming the databases.

The CorpseFinder size should be correct though.

Can you show me which corpses were found? I think it might be related to folders with files inside them, where SD Maid only counts the folder, but not the content.

**Comment by programmist87** [comment]
![S00624-052642](https://user-images.githubusercontent.com/60130882/85491070-8b6f1680-b5db-11ea-817b-0488f8cd8c08.png)
![S00624-052650](https://user-images.githubusercontent.com/60130882/85491079-8f029d80-b5db-11ea-8d57-b0ab67e61e22.png)
![S00624-052657](https://user-images.githubusercontent.com/60130882/85491087-92962480-b5db-11ea-8e8f-13aed89812df.png)
