### ISSUE TITLE
What is this file on the device?

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#3457]
Что это за файл? 

shape_predictor_68_face_landmarks.dat

Находится в корневом каталоге устройства. Он встречается выложенным на вашем сайте. Нужно ли отправлять о нем рапорт?

**Comment by d4rken** [comment]
I don't know :frowning:

**Comment by programmist87** [comment]
Вот страницы на вашем сайте, где этот файл, и с текстом, где есть упоминанием о нём.

https://github.com/AKSHAYUBHAT/TensorFace/blob/master/openface/models/dlib/shape_predictor_68_face_landmarks.dat

https://github.com/AKSHAYUBHAT/TensorFace/blob/master/openface/models/get-models.sh



Я думал вы знаете, для чего он. Хотелось бы знать, что его можно безопасно удалять. По всей видимости он связан с распознаванием лиц.

**Comment by d4rken** [comment]
Which app created it though?

We need a packagename.

**Comment by Ingood5** [comment]
Нашёлся владелец:

com.zmobileapps.celebrityfacemorph

**Comment by d4rken** [comment]
https://github.com/d4rken-org/sdmaid-se/pull/200
