### ISSUE TITLE
Clutterreport: /storage/emulated/0/backups

### ISSUE THREAD

**Issue by ghost** [d4rken-org/sdmaid#3465]
### Target
Target: `/storage/emulated/0/backups`
Prefix-free: `backups`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Pure Writer`
Packagename: `com.drakeet.purewriter`
Version: `15.1.2 (1120015120)`

### Current owners
Appname: `?`
Packagename: `ccc71.at.free`
Version: ` (-1)`

Appname: `?`
Packagename: `com.jrummy.app.managerfree`
Version: ` (-1)`

Appname: `?`
Packagename: `ccc71.at`
Version: ` (-1)`

Appname: `?`
Packagename: `com.estrongs.android.pop.cupcake`
Version: ` (-1)`

Appname: `?`
Packagename: `com.estrongs.android.pop.pro`
Version: ` (-1)`

Appname: `?`
Packagename: `com.estrongs.android.pop.app.shortcut`
Version: ` (-1)`

Appname: `?`
Packagename: `com.estrongs.android.pop`
Version: ` (-1)`

### SD Maid
Version: `4.15.9 (41509)`

### Device
Fingerprint: `google/walleye/walleye:10/QQ1A.200205.002/6084386:user/release-keys`

**Comment by d4rken** [comment]
https://github.com/d4rken-org/sdmaid-se/pull/196
