### ISSUE TITLE
Cannot delete system app

### ISSUE THREAD

**Issue by MitchelAtherloson** [d4rken-org/sdmaid#3478]
**Device**: Google Pixel 3a
**Android version**: Latest (April 2020) factory image (build: QQ2A.200405.005)
**SD Maid version**: SD Maid Pro 4.15.8. Automatic bug reports and App analytics enabled
**Root version**: Magisk 20.4 (20400), Magisk Manager 7.5.1 (267) (7)
**Install-id**: 928c31f1-dfa7-4922-be32-b3575492afab

**What happened**: Tried to uninstall a system app. (NFC) SD Maid has root access verified in Magisk log.
**What did you expect**: Application to be uninstalled.
**What actions did you take**: Launched app control, clicked NFC, killed application, clicked  delete. SD Maid says it has been deleted however after refreshing app control it still remains.
**Can you reproduce it**: Yes, in fact even tho NFC is frozen it still managed to run. It cannot uninstall other system apps also such as play music. 
**Extra**: Tried reinstalling magisk. Tried reinstalling SD Maid. Issue remains.

**SD Maid Debug Log**: Trying to kill and delete the app
[sdmaid_logfile_1588491036428.txt.zip](https://github.com/d4rken/sdmaid-public/files/4569787/sdmaid_logfile_1588491036428.txt.zip) (sha256 checksum:  
76CFD6F2D2473E861FE14D97063E3174041F1B3B3FBF82C4E07B532406F3DF8C)

**SD Maid Debug Log**: Opening the SD Maid app from scratch and running AppControl scan 
[sdmaid_logfile_1588494479670.txt.zip](https://github.com/d4rken/sdmaid-public/files/4569834/sdmaid_logfile_1588494479670.txt.zip) (sha256 checksum: 1F647DFB15C7962B3B47D59AD887568D1DE40BFE487839F2362E48FD3AB38D6D)

**Logcat**: 
[logcat_05-03-2020_16-15-29.txt](https://github.com/d4rken/sdmaid-public/files/4569808/logcat_05-03-2020_16-15-29.txt) (sha256: checksum: 720F4037E81F41FE5E4E4DDFF9D3D76F1B012CDA0AE402743E7B7E8B7049A1B8)

**Comment by d4rken** [comment]
Thanks for the comprehensive report.

Did you check that it is not this: https://github.com/d4rken/sdmaid-public/issues/220

I assume you did, then I think it's either:
https://github.com/d4rken/sdmaid-public/issues/1125
or
https://github.com/d4rken/sdmaid-public/issues/2273

Both sadly not trivial to fix, I'll have to check your logs to be sure.

**Comment by williamsp** [comment]
Hi, I am also having this issue.

Device: Xiaomi Redmi Note 8
Android version: 10 QKQ1.200114.002 on MIUI 12.0.1 QCOIDXM
SD Maid version: SD Maid Pro 5.0.3
Root version: Magisk 21.0 (21000), Magisk Manager 8.0.3 (314)
Install-id: 23f7b416-564b-4998-b07a-06a51aca0dad

I tried to uninstalled com.android.chrome, a system app which has not been updated.
And, here's the log: [sdmaid_logfile_1607055492507.txt.zip](https://github.com/d4rken/sdmaid-public/files/5640633/sdmaid_logfile_1607055492507.txt.zip)
