### ISSUE TITLE
Bug when entering text

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#3525]
Meizu M8
Android: 8.1.0
No root
SD Maid v4.15.8, Unlocker v4.4.1
install ID: 06d0f2d5-18e1-4244-9ac3-edf247ccfd40

Если при вводе текста с помощью Яндекс.клавиатуры (имя пакета ru.yandex.androidkeyboard) выполнить последовательность действий:

1. Ввести, используя Swipe-ввод, любое слово в любом окне SD Maid (в котором есть поле для ввода текста).
2. Нажать на любую клавишу клавиатуры.

то введённое с помощью Swipe-ввода слово исчезает. Если с помощью swipe-ввода ввести несколько слов, то после нажатия клавиши исчезнет только последнее. Исключения составляют только окна "Создать карточку проблемы" и окно создания пользовательского фильтра для SystemCleaner, в этих окнах все работает правильно. При вводе в других приложениях такой проблемы нет. SD Maid и Яндекс.Клавиатуру переустановил. Это происходит каждый раз.

[sdmaid_logfile_1589108683779.txt.zip](https://github.com/d4rken/sdmaid-public/files/4605728/sdmaid_logfile_1589108683779.txt.zip)

[Screen video recording.mp4.zip](https://github.com/d4rken/sdmaid-public/files/4605755/Screen.video.recording.mp4.zip)

**Comment by d4rken** [comment]
I'm not sure if I can fix this, I'll do some research.

If you use a different keyboard on the same phone, does it work?

**Comment by programmist87** [comment]
Проверил на нескольких клавиатурах, почти везде работает, кроме SwiftKey-клавиатуры (com.touchtype.Swiftkey), в ней swipe-ввод вообще не работает, как будто отключен, и исключения тоже для окна "Создать карточку проблемы" и окна создания пользовательского фильтра для SystemCleaner.

**Comment by Ingood5** [comment]
Если после ввода слова с помощью Swipe-ввода нажать на поле с текстом в другом месте, а затем вернуть курсор обратно, то проблема не появляется. Возможно, с помощью этого можно реализовать обход ошибки или найти ее причину. 

[video.zip](https://github.com/d4rken/sdmaid-public/files/5361105/video.zip)
