### ISSUE TITLE
AppControl Fails to Uninstall App, Not Found in List of Installed Apps

### ISSUE THREAD

**Issue by sonic65101** [d4rken-org/sdmaid#3548]
[sdmaid_logfile_1589897483542.txt.zip](https://github.com/d4rken/sdmaid-public/files/4651078/sdmaid_logfile_1589897483542.txt.zip)
As requested on Discord, here is the debug log from the failed uninstall attempt.

**Comment by DLuna888** [comment]
Please delete bugs from my phone
