### ISSUE TITLE
Connection to Google Play services and occupied memory.

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#3583]
Для чего SD Maid в фоне использует сервис Google Play Market? Он занимает большую часть ОЗУ приложения. Возможно как-то снизить потребление памяти для старых телефонов?

![S00607-105330](https://user-images.githubusercontent.com/60130882/83964438-dab40800-a8b5-11ea-911f-74c1db3cd6a8.png)

**Comment by d4rken** [comment]
SD Maid isn't really using 80MB. It just means that SD Maid is connected to Google Play services.
Google Play services is using 63.8MB, not SD Maid.

I'm not sure why SD Maid is connected while you took the screenshot, but it's likely related to IAPs and the accessibility service being permantly alive.
I could investigate whether the IAP connection can be severed when only the accessibility service is loaded. Not that easy though, as the downside could be more people complaining about having bought SD Maid and not getting pro features.

In any case, you will only regain those 63.8MB, if the Google Play Market is pushed out of memory, which is usually very unlikely as lot's of other services bind to Google Play (services) and thus keep it alive.

**Comment by programmist87** [comment]
Возможно добавить в настройки опцию, чтобы можно было это отключать, чтобы была возможность попробовать на старом телефоне освободить память?

**Comment by programmist87** [comment]
> In any case, you will only regain those 63.8MB, if the Google Play Market is pushed out of memory, which is usually very unlikely

То есть на старом телефоне с 512 мб ОЗУ с большой долей вероятности 63 мб постоянно будут заняты, они не будут выгружаться в кэш, и следовательно это соответственно скажется на скорости работы устройства?

**Comment by Ingood5** [comment]
Если быть точным, меня интересует, как работает оперативная память на старых телефонах, в настройках которых нет возможности запрещать приложениям работу в фоне. SD Maid + сервисы Google Play будут постоянно занимать эти 80 мб? Или когда SD Maid не используется, эти 80 мб выгружаются в кэш и перестают занимать память и влиять на производительность устройства?

**Comment by d4rken** [comment]
I currently don't know. Further investigation is necessary.

It may be entirely possible that RAM will be occupied in any case, that it's just displayed confusingly.
