### ISSUE TITLE
Scanned app size is incorrect for some apps in AppControl

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#3598]
Meizu M8
Android: 8.1.0
No root
SD Maid v4.15.12, Unlocker v4.4.1 
install ID:
560ee930-d4f0-4d01-8995-c144f353fce0

SD Maid отображает неверный размер у приложений. У одних приложений показывает больше чем на самом деле, у других меньше. Размер иногда отличается в два раза. Пример приложения с верным размером — com.zmobileapps.celebrityfacemorph. Это происходит каждый раз после сканирования в AppControl.

[sdmaid_logfile_1592651491768.txt.zip](https://github.com/d4rken/sdmaid-public/files/4807792/sdmaid_logfile_1592651491768.txt.zip)

**Comment by d4rken** [comment]
Can you show a screenshot of an app that shows the wrong size?
If you go into the details in AppControl, which path has the incorrect size?

**Comment by programmist87** [comment]
![S00624-053738](https://user-images.githubusercontent.com/60130882/85492403-c96d3a00-b5dd-11ea-9323-0bcccc8a78d3.png)
![S00624-053745](https://user-images.githubusercontent.com/60130882/85492421-cf631b00-b5dd-11ea-9a79-187266973de1.png)
![S00624-054007](https://user-images.githubusercontent.com/60130882/85492430-d1c57500-b5dd-11ea-995d-6535400780cd.png)
![S00624-054013](https://user-images.githubusercontent.com/60130882/85492435-d558fc00-b5dd-11ea-8dbb-a2af292660a4.png)

**Comment by programmist87** [comment]
У вас не получилось это повторить? Или это только на Meizu?

**Comment by JonDous** [comment]
The same on Xiaomi Mi9.

**Comment by JonDous** [comment]
![Screenshot_2020-07-28-18-12-09-885_com miui securitycenter](https://user-images.githubusercontent.com/68903949/88658638-f392aa00-d0fd-11ea-8bf8-39f4bbb93e0d.png)
![Screenshot_2020-07-28-18-12-14-976_eu thedarken sdm](https://user-images.githubusercontent.com/68903949/88658656-f9888b00-d0fd-11ea-9e89-77480fcb5579.png)

**Comment by JonDous** [comment]
I'm sure problem coz the app shows only the apk size and maybe some libraries. But you have to add cache size of apps in this tab. Sometimes we have no free space and sort apps by size and find which games or apps are too heavy would be nice.

**Comment by Ingood5** [comment]
Кажется, я нашёл в чем проблема.


Во всех приложениях не показывает размер по пути data/user:

![S01223-15561248(1)](https://user-images.githubusercontent.com/60130882/102999541-3ab08a00-453a-11eb-9071-a897cba7802c.png)


В AppCleaner размер по полному пути к кэшу в data/user показывает:

![S01223-15565622](https://user-images.githubusercontent.com/60130882/102999726-a4309880-453a-11eb-9cf7-1ff61a92d35b.png)


Путь к папке data недоступен:

![S01223-16032733](https://user-images.githubusercontent.com/60130882/103000017-3c2e8200-453b-11eb-85ea-e925d6080dba.png)


Если перейти в папку приложения в data/app, она доступна, но если выйти из неё в саму папку data/app, она не доступна:

[VIDEO.zip](https://github.com/d4rken/sdmaid-public/files/5735427/VIDEO.zip)


По какой-то причине пути к подпапкам доступны, а пути к их родительским каталогам не доступны.
