### ISSUE TITLE
Reset button for AppCleaner & SystemCleaner filter settings

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#3599]
Возможно стоит добавить кнопку сброса к параметрам по умолчанию в настройках фильтров AppCleaner и SystemCleaner. При поиске нового мусора часто есть необходимость возвращать настройки к изначальным. Только без удаления пользовательских фильтров SystemCleaner, нужно просто снять галочки с фильтров.

**Comment by d4rken** [comment]
The AppCleaner has a reset button in the settings, does it not work for the filters?

Would the reset button for the SystemCleaner delete the custom filters?

**Comment by programmist87** [comment]
Кнопка сброса в настройках фильтры не сбрасывает.

В SystemCleaner с пользовательских фильтров лучше просто снять флажки. Даже при поиске мусора обычно нужно просто временно вернуть их по умолчанию, затем опять все включить. Настройки сбросятся, если нужно пользователь сам очистит список.
