### ISSUE TITLE
Extra rescan button within QuickAccess

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#3600]
Возможно стоит добавить общую кнопку повторного сканирования в меню быстрого доступа. Когда есть необходимость повторного сканирования, неудобно заходить в каждой пункт меню по отдельности и после каждого пункта снова возвращаться в главное меню.

**Comment by programmist87** [comment]
Я имею ввиду когда есть необходимость сделать повторное сканирование, не очищая то, что было найдено при предыдущем сканировании. Часто нужно при поиске нового мусора.
