### ISSUE TITLE
Monitor filesystem access per app

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid#365]
Would be cool to select an app and monitor what files it accessed, creates or modifies.

Aproaches:
- `lsof`
- `strace`

**Comment by randomname1234** [comment]
As stated in #366 `lsof` is not good for monitor activities so it's better use `strace`

**Comment by jawz101** [comment]
I've always wanted strace for Android.  I'd even suggest making a whole separate app just for it.  Still haven't found good, comprehensive and pretty apps to perform functions similar to Windows SysInternals Process Explorer and Process Monitor ... but for Linux/Android and, frankly, Linux devs don't care for such nice things:/

**Comment by d4rken** [comment]
The basics would be to get strace running and working on different Android versions. Not sure what is necessary for that. I guess it would probably a root only function?

**Comment by jawz101** [comment]
I would imagine so.  Btw, I think there's several people who have ported it to Android if you Google strace Android though I don't think they got any attention because they weren't wrapped in a shiny gui.
