### ISSUE TITLE
Monitor what apps do in a specific path

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid#366]
Would be cool to select a specific path and see what apps (processes) change in that path.

Approaches:
- `inotify`
- `lsof`
- `auditctl`

**Comment by randomname1234** [comment]
- `inotify`: It's better not use that. Inotify does not support recursively watching directories, meaning that a separate inotify watch must be created for every subdirectory.
[https://en.wikipedia.org/wiki/Inotify](https://en.wikipedia.org/wiki/Inotify)

- `lsof`: It will tell you what process has a file open at the time you run it but lsof won't tell you about file that were opened two microseconds ago and closed one microsecond ago, so it's not good for monitoring activities.
[http://unix.stackexchange.com/questions/13776/how-to-determine-which-process-is-creating-a-file](http://unix.stackexchange.com/questions/13776/how-to-determine-which-process-is-creating-a-file)
- `auditctl`: This is ok :smiley:
