### ISSUE TITLE
Select/copy all permissions text

### ISSUE THREAD

**Issue by JonnyTech** [d4rken-org/sdmaid#3667]
Currently it is possible to select/copy only single permissions at a time in the AppControl section. Can you please change it that one can select all or more of the text block please? Or even to export it to a text file?

**Comment by d4rken** [comment]
You mean in the app details view? Can you show a screenshot?

In my mind that was a single textview and should allow to select multiple lines, I'll have to check that.

**Comment by JonnyTech** [comment]
Yes, details for the app with AppControl, as shown here:

![img_0](https://user-images.githubusercontent.com/3584732/87222374-0c176c00-c36b-11ea-83e2-c68f66637b64.jpg)
