### ISSUE TITLE
Shortcuts are not created for some Activities.

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#3707]
Meizu M8
Android: 8.1.0
No root
SD Maid v4.15.13, Unlocker v4.4.1
install ID:
bee65a72-b1ce-4b09-80ad-1a90794750f6

В AppControl не создаются ярлыки для некоторых Активити. Например на Meizu M8  в приложении Настройки (com.android.settings) не создаются для этих:

![S00731-163916(1)](https://user-images.githubusercontent.com/60130882/89042267-59c23b80-d34f-11ea-8bec-73b1d748c2af.png)

И для многих других.
При нажатии на значок "+" не появляется окно с кнопками "Отмена" и "Ок", а сразу внизу появляется уведомление "1 OK", и ярлык на главном экране не создаётся. В других приложениях ошибка не попадалась. Приложение Запуск Activity (de.szalkowski.activitylauncher) все эти ярлыки успешно создаёт. Некоторые из них очень нужные. Это повторяется каждый раз.

[sdmaid_logfile_1596203363225.txt.zip](https://github.com/d4rken/sdmaid-public/files/5007381/sdmaid_logfile_1596203363225.txt.zip)

**Comment by programmist87** [comment]
Нашёл пример в общеизвестном приложении (com.google.android.gm).


![S00807-17002292(1)](https://user-images.githubusercontent.com/60130882/89653731-31e35280-d8d0-11ea-9098-cc063230e978.png)

**Comment by Ingood5** [comment]
Заметил другой вариант ошибки, при котором окно с предложением создать ярлык появляется, но после нажатия на ОК ярлык не появляется. Пример – ярлыки для SD Maid.

**Comment by Ingood5** [comment]
Третий вариант ошибки, это когда ярлыки для одного приложения, которые можно создать по отдельности, нельзя создать одновременно, то есть можно создать или один ярлык, или другой. Пример – com.microsoft.office.word.
