### ISSUE TITLE
The explorer needs the ability to sort

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#3789]
Explorer needs the ability to sort by creation / modification time. For example, I am looking for which application created the folder, install everything with similar names, at the same time I look at the last created folders, what kind of garbage was left by the newly installed applications, and immediately send reports on them. Without sorting, you have to do this in other conductors.

And, perhaps, it is necessary that the date of modification of the folder changes not only when changes are made directly in the folder, but also in subfolders, otherwise if all subfolders have already been created earlier, the folder will not be displayed as recently changed.

> В проводнике нужна возможность сортировки по времени создания/изменения. Например ищу какое приложение создало папку, устанавливаю все с похожими названиями, заодно смотрю по последним созданным папкам, какой мусор оставили только что установленные приложения, и сразу отправляю отчёты по ним. Без сортировки приходится это делать в других проводниках. 

> И, возможно, нужно чтобы дата изменения папки менялась не только при изменениях непосредственно в папке, но и в подпапках, иначе если все подпапки ранее уже были созданы, то папка не отобразится как недавно изменённая.

**Comment by Ingood5** [comment]
Прошу прощения, не заметил, в проводнике уже есть возможность сортировки:

![S00921-16121698(1)](https://user-images.githubusercontent.com/60130882/93772112-1b4a4e00-fc27-11ea-8eaf-cbc7994bf64a.png)


Но если сортировать в обратном порядке, то есть сделать сортировку не сначала алфавита, а с конца, то после принудительной остановки SD Maid сортировка опять становится с начала алфавита. Так во всех режимах сортировки:

![S00921-16121698(2)](https://user-images.githubusercontent.com/60130882/93772125-20a79880-fc27-11ea-9615-247d80ad8294.png)

**Comment by Ingood5** [comment]
> если сортировать в обратном порядке, то есть сделать сортировку не сначала алфавита, а с конца, то если закрыть и заново открыть SD Maid, сортировка опять становится с начала алфавита. Так во всех режимах сортировки



Можете для SD Maid 1 сделать это исправление? Неудобно когда приходится каждый раз вручную переключаться на режим "новые файлы вверху", при следующем запуске SD Maid опять сбрасывает на "старые файлы вверху" 😥

**Comment by d4rken** [comment]
This will be included in the next update.
