### ISSUE TITLE
Предложение внести исправление в расписание.

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#3808]
Возможно, вам нужно сделать исправление в очистку по расписанию. Если во время настройки телефона или по другой причине нужно перевести время вперёд позже даты, когда должна запуститься очистка, а после этого вернуть назад, то все пропущенные очистки уже не запустятся, и приходится настраивать расписание заново. Будет лучше, чтобы при настройке расписания SD Maid запоминал время и дату, когда оно включено, и в последствии основываясь на ней подсчитывал в какие дни запускать очистку.

**Comment by programmist87** [comment]
Дополнение: очистка оказывается пропущенной, если на момент активации телефон выключен. Нужно чтобы в таких случаях очистка запускалась при включении телефона.
