### ISSUE TITLE
Determine app sizes in AppControl with fewer clicks

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#3836]
Возможно стоит сделать, чтобы подробности о размере приложения в AppControl отображались при однократном нажатии. На данный момент, если в настройках отключена Предзагрузка связей приложения, приходится нажимать два раза: 

[S00823-16100483.mp4.zip](https://github.com/d4rken/sdmaid-public/files/5113980/S00823-16100483.mp4.zip)

**Comment by programmist87** [comment]
На данный момент нажатие на сам пункт "Размер" нужно делать два раза. При первом нажатии происходит сканирование, и только при втором открываются детали. Нужно чтобы после одного нажатия произошло сканирование и сразу открылись детали, без повторного нажатия. То есть при выборе приложения в AppControl детали не отображаются, но после однократного нажатия на пункт "Размер" происходит сканирование и сразу открываются детали, без повторного нажатия.
