### ISSUE TITLE
Make the report via question mark easier to tap

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#3860]
При отправке отчёта очень часто палец не попадает по знаку вопроса, вместо этого открывается папка. Вас нужно сделать, чтобы попадать было легче.

**Comment by d4rken** [comment]
How would you change it?

**Comment by Ingood5** [comment]
Диаметр круга попадания вокруг знака вопроса должен быть намного больше, равным ширине папки в проводнике:

![S00901-20252590(1)(1)](https://user-images.githubusercontent.com/60130882/91886207-a8862c80-ec91-11ea-8e9a-2f328204f52f.png)


Если это окажется чрезмерным, то чуть меньше.
