### ISSUE TITLE
Unlock application is not displayed again

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#3866]
Meizu M8
Android: 8.1.0
No root
SD Maid v4.15.13, Unlocker v4.4.1 
install ID:
41d53121-f926-45d1-898d-044c704247bc

Если скрыть приложение разблокировки и после этого хотя бы один раз перезагрузить телефон, то нельзя нельзя повторно увидеть его через соответствующий пункт в настройках. При нажатии на него ничего не происходит. Это повторяется каждый раз.

[sdmaid_logfile_1598518943229.txt.zip](https://github.com/d4rken/sdmaid-public/files/5135477/sdmaid_logfile_1598518943229.txt.zip)

**Comment by d4rken** [comment]
Have you tried rebooting, after clicking the entry in SD Maid's settings?

Depending on the launcher on your phone, reboots are necessary to change app visibility.

**Comment by Ingood5** [comment]
Пробовал, не помогает.
