### ISSUE TITLE
Closing details in AppControl when minimizing SD Maid

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#3869]
Если в AppControl открыть подробности размера приложения, а переключиться с SD Maid на другое приложение, или свернуть SD Maid, то при переключении на SD Maid подробности о размере в AppControl закрываются.

**Comment by d4rken** [comment]
Do you mean the screen, or the collapsible box?

**Comment by Ingood5** [comment]
[S00830-12542212.mp4.zip](https://github.com/d4rken/sdmaid-public/files/5146609/S00830-12542212.mp4.zip)

**Comment by d4rken** [comment]
![Screenshot from 2020-08-30 12-41-58](https://user-images.githubusercontent.com/1439229/91657037-36112300-eabe-11ea-91e6-9e4780aa6777.png)
