### ISSUE TITLE
Refresh internal application list after installed packages change

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#3879]
Заметил, что после удаления приложения SD Maid часто не обновляет статус файлов. Или одни файлы отображают значок приложения, а другие вообще без значка:

[S00830-17411727.mp4.zip](https://github.com/d4rken/sdmaid-public/files/5146975/S00830-17411727.mp4.zip)

Такое часто сохраняется даже если SD Maid перезапустить несколько раз.

**Comment by d4rken** [comment]
SD Maid internally caches the list of installed packages. This would be a feature where SD Maid watches the installed packages, and if it changes, the internal cache is invalidated.

> This often persists even if SD Maid is restarted several times.

You need to completely stop SD Maid, i.e. "force stop", afterwards it should work correctly.

**Comment by Ingood5** [comment]
То есть это нормально, или вы внесёте какие-то изменения?

**Comment by d4rken** [comment]
The current behavior is normal.

I will keep this ticket as feature request, to have SD Maid refresh it's internal app caches dynamically.

**Comment by d4rken** [comment]
Need to look into cache timeout, apparently it's longer than 10 minutes?
See https://github.com/d4rken/sdmaid-public/issues/4444#issue-771578894

**Comment by Ingood5** [comment]
Такое впечатление, что #3879 и #4444 разные проблемы. В проблеме #3879 я не уточнил, что статус файлов все равно обновляется, но не сразу, а примерно в течение минуты, возможно иногда немногим дольше, всегда по разному. На видео в первом комментарии (https://github.com/d4rken/sdmaid-public/issues/3879#issue-688732224) видно, что статус файлов все равно спустя определённое время обновился. То есть всегда есть задержка в обновлении статуса файлов, но она небольшая.

В проблеме #4444 приложение не находил AppControl, и не находил намного дольше, 30 минут, после этого я сделал принудительную остановку SD Maid. Обычно если сразу после установки/удаления приложения сделать сканирование с помощью AppControl, AppControl показывает изменения без задержки. 

Возможно #4444 связано с #4254, там аналогичная проблема, но после удаления приложения. То есть AppControl в отдельных случаях не фиксирует изменения среди установленных приложений .

**Comment by d4rken** [comment]
SD Maid only has a single "in-memory cache" for the list of installed apps. It is used by all of SD Maids functions. There is logic to force a data refresh for certain operations, maybe there is a bug that cause the refresh to not work.

I need to check if uninstalling an app triggers a forced refresh...
I think it  would make sense :thinking:

**Comment by Ingood5** [comment]
> I need to check if uninstalling an app triggers a forced refresh...

В связи с появлением проблемы #4444 нужно проверить это и после установки приложения.

**Comment by MikeZeDev** [comment]
Sorry for reviving this old report but i have the issue on Android 12. I use a stock Samsung ROM on this Samsung A51 that i rooted using magisk. I uninstalled some system apps using pm uninstall, they still show as installed but only in SDMaid. 

Other app like Appinspector/ Titanium / Alpha backup doesnt see them . Even the windows pc app "Unioversal Android Debloater" saw them as uninstalled.

If i uninstall them using SDMaid doesn't change anything. They are indeed "stopped" but still here after another SDmaid scan.

I know that there are some persistant app that come back like the infamous "samsung GOS" but its the first time i see that for applications like ANT+, Aremoji etc.. I dont know whats going on.

I cant read all that russian stuff sorry.
