### ISSUE TITLE
Clutterreport: /storage/emulated/0/Удалить нежелательный объект (new)

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#3950]
### Target
Target: `/storage/emulated/0/Удалить нежелательный объект`
Prefix-free: `Удалить нежелательный объект`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Удалить нежелательный объект`
Packagename: `vn.remove.photo.content`
Version: `1.1.7 (16)`

### Current owners
None

### SD Maid
Version: `4.15.15 (41515)`

### Device
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

### Comment
`Не проверял, keeper это или нет.`

**Comment by d4rken** [comment]
Yes there seems to be a typo in the russian text in the definitions.
