### ISSUE TITLE
Proposing changes to log creation.

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#3961]
1. Сохранение лога нужно сделать не в /storage/emulated/0/Android/data/eu.thedarken.sdm/cache/logfiles, а по короткому пути. Например, в папку SD Maid в корневом каталоге или просто как файл без папки в /storage/emulated/0/Download, так же как при экспорте ссылок на Google Play из AppControl. При прикреплении лога к отчёту неудобно заходить по длинному пути, сразу бросается в глаза разница по сравнению с другими приложениями, в них сохранение данных всегда происходит где-либо на поверхности и поэтому их прикреплять просто. 
2. При создании лога создаётся два файла: zip и txt. Лучше чтобы создавался только zip. Файл txt создаёт лишний мусор и мешает при отправке, если есть необходимость создать несколько логов. Если пользователю нужно, он всегда сможет извлечь zip архив. 
3. После окончания записи лога лучше чтобы предлагалось открыть папку с логом, как при экспорте ссылок на Google Play из AppControl, а не Отправить. Лог всегда требуется прикреплять к отчёту, а не отправлять.

**Comment by d4rken** [comment]
I can look into it again, but the core idea behind `Android/data/eu.thedarken.sdm/cache/logfiles` is that it's reliable.

There is the real chance that there are issues with permissions to access `Download` or similar directories, so when we try to debug issues related to permissions we don't have a reliable logfile.

The current directory has special behavior guaranteed by the system that makes debug log recording more reliable, we don't need any special permissions.

The "share log dialog" should make the location irrelevant though, can't you just use the dialog?

**Comment by Ingood5** [comment]
Лог всегда приходится прикреплять к отчёту в интернет-браузере через проводник, который предлагается в браузере, поэтому "shared log dialog" не может помочь. К тому же "share log dialog" предлагает отправить в другие приложения, не совсем понятно для чего это нужно:

[video.zip](https://github.com/d4rken/sdmaid-public/files/5252166/video.zip)

В таком случае, если бы предлагалось скопировать лог в удобное место, было бы лучше.

По какой причине у может не быть доступа к Download и аналогичным каталогам? Я думал, что если у приложения есть доступ к файлам для очистки, то оно может свободно использовать общеизвестные каталоги.
