### ISSUE TITLE
Exclude public/private data from storage size calculation for emulated storages

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid#399]
When displaying the size of primary private storage (e.g. /data ), and the device uses an emulated storage as sdcard (e.g. /storage/emulated/0 ) the displayed size is missleading because it uses the values for the underlying partition.

Storage is 10GB, 3GB is free
- Public storage (`/sdcard`) shows 7GB of 10GB (4GB actual data) 
- Private storage (`/data`) shows 7GB of 10GB (3GB actual data outside of /data/user/0)

We could display public storage as 4GB of 7GB and private storage as 3GB of 6GB.
This would be more accurate to the description of that storage area and it would be more clear how much space is actually used up on that location.

**Comment by randomname1234** [comment]
This could be ambiguous as the user could think the storage is 13GB (7GB + 6GB)

**Comment by d4rken** [comment]
Should no longer be an issue in SD Maid SE's storage analyzer.
