### ISSUE TITLE
Selected files are reset when the deletion dialog is canceled

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4003]
Если 
1. Выделить несколько файлов, 
2. Нажать на значок корзины, 
3. Отменить удаление, 

то выбор файлов сбрасывается.

[video.zip](https://github.com/d4rken/sdmaid-public/files/5276730/video.zip)

**Comment by d4rken** [comment]
I think I added this on purpose, there were some problems otherwise, possibly related to device rotation.
I'll look into the reasons again when I have time.
