### ISSUE TITLE
Duplicate details -> Open in Explorer doesn't scroll to the right position

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4004]
Если при поиске дубликатов перейти к найденному файлу, то список файлов в папке не перематывается автоматически к выбранному файлу. Это повторяется каждый раз.

[video.zip](https://github.com/d4rken/sdmaid-public/files/5276887/video.zip)

**Comment by d4rken** [comment]
SD Maid v4.15.15?

**Comment by Ingood5** [comment]
Да.

**Comment by Ingood5** [comment]
Такая же проблема если из инструмента Поиск перейти к найденному файлу в проводник.
