### ISSUE TITLE
Bug: Bug in AppCleaner scrolling

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4057]
### What happened?
> В AppCleaner список деталей найденного кэша автоматически проматывается вверх, если свернуть SD Maid или переключиться на другое приложение и обратно. Повторяется каждый раз.

In AppCleaner, the list of details of the found cache is automatically scrolled up if you minimize SD Maid or switch to another application and back. Repeats every time.

[video.zip](https://github.com/d4rken/sdmaid-public/files/5321156/video.zip)

### SD Maid
Version: `4.15.15 (41515)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

**Comment by waters420** [comment]
happened?
 In AppCleaner, the list of details of the found cache is automatically scrolled up if you minimize SD Maid or switch to another application and back.  Repeats every time.

**Comment by d4rken** [comment]
Not so much a bug, but just not been implemented in all cases. That scrolling stuff is really difficult :frowning:, will look into fixing it though, thanks for the report :heart: .
