### ISSUE TITLE
QuickAccess: When scanning individually the main button stays on "search"

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4082]
### What happened?
Если в быстром меню запустить сканирование каждого пункта отдельно, то все равно продолжает отображаться кнопка "Сканировать".

[video.zip](https://github.com/d4rken/sdmaid-public/files/5348618/video.zip)

### SD Maid
Version: `4.15.15 (41515)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

**Comment by d4rken** [comment]
There were some edge cases to this when I last looked into it. This has been an issue that regularly came up.

Does it also happen on a fresh start?

**Comment by Ingood5** [comment]
Если вы про принудительную остановку SD Maid, то после неё проблема исчезает.

Проблему можно вызвать, если после сканирования один инструмент очистить отдельно, а остальные общей кнопкой:
[video.zip](https://github.com/d4rken/sdmaid-public/files/5364716/video.zip)
