### ISSUE TITLE
Tool status messages in the sidemenu could scroll their content

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4093]
### What happened?
На русском языке в меню с левой стороны экрана не отображаются до конца детали пункта Explorer. Видно начало слова "Объём", то есть по смыслу дальше должен быть показан полный объём встроенной памяти.

![S01011-16141486(1)](https://user-images.githubusercontent.com/60130882/95680164-3124b080-0be0-11eb-965f-8449beb107ab.png)
![S01011-16131367(1)](https://user-images.githubusercontent.com/60130882/95680165-3255dd80-0be0-11eb-85bd-146774425f86.png)

### SD Maid
Version: `4.15.15 (41515)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

**Comment by Ingood5** [comment]
Не до конца отображается информация также и о выполнении  различных действий в проводнике.

**Comment by d4rken** [comment]
This is a general issue for all tools and in all languages.

This is not a bug. The text is just a "preview".

We can treat this a feature and try to make the text scroll automatically.

**Comment by Ingood5** [comment]
Возможно, нужно добавить в настройки возможность отключать автоматическую прокрутку, если это может повлиять на производительность на старых телефонах.
