### ISSUE TITLE
Google TV w/ Chromecast (2020) - debug logs are not dismissable nor will they stop running 

### ISSUE THREAD

**Issue by mcl21014** [d4rken-org/sdmaid#4151]
Google TV w/ Chromecast (2020) - 
Device: Google TV w/ Chromecast (2020)
SDM version: 5.0.0 beta (sideloaded)
Root status: unrooted
SDM Unlocker version: 4.4.1
Install ID: ? Too lazy, it changed after another clear data

What happened?
I go to record a debug log in app via long pressing Settings and running "Record Debug Log" and no notification appears to stop it under the Notification area on the right of the home screen. Neither force stopping nor rebooting even will not stop it. User has to clear data for SDM to stop the recording process,
What did you expect to happen?
I should be able to stop it via a notification on the right of Android TV's Home Screen where shortcuts to settings, notifications, etc are. It should also stop upon power off or reboot, but it doesn't. The log will run endlessly and I assume will eventually use a ton if not all the user's storage. Not good.
What actions did you take?
See above.
Can you reproduce it, i.e. does this happen everytime?
Yes.

**Comment by buornhnufnofnr** [comment]
> Google TV w/ Chromecast (2020) -
> Device: Google TV w/ Chromecast (2020)
> SDM version: 5.0.0 beta (sideloaded)
> Root status: unrooted
> SDM Unlocker version: 4.4.1
> Install ID: ? Too lazy, it changed after another clear data
> 
> What happened?
> I go to record a debug log in app via long pressing Settings and running "Record Debug Log" and no notification appears to stop it under the Notification area on the right of the home screen. Neither force stopping nor rebooting even will not stop it. User has to clear data for SDM to stop the recording process,
> What did you expect to happen?
> I should be able to stop it via a notification on the right of Android TV's Home Screen where shortcuts to settings, notifications, etc are. It should also stop upon power off or reboot, but it doesn't. The log will run endlessly and I assume will eventually use a ton if not all the user's storage. Not good.
> What actions did you take?
> See above.
> Can you reproduce it, i.e. does this happen everytime?
>  no
