### ISSUE TITLE
Screen does not turn off when is SD Maid is open

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4152]
### What happened?
Если запустить очистку и положить телефон, то после очистки экран не отключается, то есть остаётся включённым даже когда время отключения экрана давно истекло.

### SD Maid
Version: `4.15.15 (41515)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

**Comment by d4rken** [comment]
This is on purpose.
I can evaluate to disable it if no operation is running.
