### ISSUE TITLE
Предложение изменений в перевод.

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4155]
Возможно нужно изменить перевод названий инструментов AppCleaner и AppControl на русском языке. Инструмент AppCleaner переведён как "Приложения". Пункт в настройках телефона, где находятся все приложения обычно называется "Приложения" или "Все приложения", и эта схожесть может запутать, если пользователь впервые использует SD Maid. У меня есть пример, я объяснял малоопытному пользователю как делать очистку с помощью SD Maid и он спросил, нужно ли ему в пункте "Приложения" тоже все удалять, так как такое название и значок корзины напротив каждого приложения выглядит как удаление самих приложений. Перевод "Приложения" подходит для AppControl, для AppCleaner подойдёт какой-нибудь другой перевод.

**Comment by d4rken** [comment]
The russian translation is done by volunteers, you are welcome to discuss it and change it:
https://crowdin.com/project/sdmaid

Any help is appreciated!
