### ISSUE TITLE
Bug: Unable to open file [ android 11 ]

### ISSUE THREAD

**Issue by SauravDharwadkar** [d4rken-org/sdmaid#4166]
### What happened?
I'm trying to open file but respective app say file doesn't exist

### What did you expect to happen?
File should open , media file play , text file open in text editor (any available)

### How can I reproduce the issue?
Open storage analys , then try to open any file 

### Comments
I'm using android 11 , nice work
### SD Maid
Version: `5.0.0 (50000)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `google/sargo/sargo:11/RP1A.201005.004/6782484:user/release-keys`

**Comment by d4rken** [comment]
Can't reproduce it on a Pixel5, can you share a debug log?
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

Does it work without root?

**Comment by SauravDharwadkar** [comment]
Without root it work , when i use normal storage /internal it worked , but when i tried to open from /data then /data/media then check my files then this happen

**Comment by d4rken** [comment]
I'm not sure that worked before Android 11. I don't think SD Maid can forward access to rooted files to other apps.
I'll look into it.
