### ISSUE TITLE
Target SDK...

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/sdmaid#4170]
Can you please include the 'Target SDK' of each app under AppControl?
Or you may also provide 'Target SDK' as a separate tool that will list all the apps installed in the system and the 'Target SDK' of each.

**Comment by d4rken** [comment]
Cool idea!

**Comment by Sridhar-Ananthanarayanan** [comment]
Great!

Whichever way you implement it (either as part of AppControl or as a separate tool), please allow for the following:

1. Ability to sort all installed apps by their Target SDK.
2. Filter apps by their Target SDK.
3. Number of apps installed for each Target SDK.
4. Please include the Android version along with the SDK number (e.g. Android 11 for Target SDK 30).

Thank you.
