### ISSUE TITLE
Bug: Error while sorting in AppControl.

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4176]
### What happened?
В AppControl проблема с сортировкой аналогичная этой – https://github.com/d4rken/sdmaid-public/issues/3789#issuecomment-696113639

### SD Maid
Version: `4.15.15 (41515)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

**Comment by d4rken** [comment]
I'm not sure what you mean, can you elaborate?
AppControl already has various sorting methods (right side drawer menu).

**Comment by Ingood5** [comment]
[video.zip](https://github.com/d4rken/sdmaid-public/files/5434892/video.zip)


На видео видно, куда я нажимаю в меню сортировки, затем я перезапускаю SD Maid и по списку приложений видно, что изменения в сортировке не сохранились.

В отчёте по ссылке выше (https://github.com/d4rken/sdmaid-public/issues/3789#issuecomment-696113639)  точно такая же проблема (на случай, если там тоже не совсем ясно о чем речь)

**Comment by Sridhar-Ananthanarayanan** [comment]
> I'm not sure what you mean, can you elaborate?
> AppControl already has various sorting methods (right side drawer menu).

If I sort apps by size, it doesn't sort them properly. I don't know the language used by the OP, but this is a problem for your attention.

**Comment by Ingood5** [comment]
> If I sort apps by size, it doesn't sort them properly.

Скорее всего, речь здесь идёт об этом – #4186
