### ISSUE TITLE
The selection of applications is reset in AppControl.

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4177]
Необходимо изменение, чтобы при выделении одного или несколько приложений, выделение не сбрасывалось при совершении в меню действий над ними, пока пользователь сам не отменит выделение. Бывает нужно продолжить другие действия над приложениями, и приходится заново их выделять.

![S01025-13584862(1)](https://user-images.githubusercontent.com/60130882/97105471-f6d10e00-16cb-11eb-8ec3-305faffdc649.jpg)

**Comment by Ingood5** [comment]
Если нажать на значок корзины, а затем отменить, то выделение тоже сбрасывается.

**Comment by d4rken** [comment]
Will look into it, but I think this is on purpose.
There were problems with list selections going out of sync.
