### ISSUE TITLE
Application cleanup error

### ISSUE THREAD

**Issue by bluepoi** [d4rken-org/sdmaid#4184]
![Screenshot_2020-10-28-10-01-24-19](https://user-images.githubusercontent.com/73566190/97378127-f2436a00-1904-11eb-9f0d-36e407e821ba.jpg)
![Screenshot_2020-10-28-10-04-08-36](https://user-images.githubusercontent.com/73566190/97378134-f5d6f100-1904-11eb-9ada-2eebc32400a5.jpg)

**Comment by bluepoi** [comment]
=== Device info ===
Install ID: c77b1b75-375a-4bf7-9f34-68a01697188a
ROM: OPPO/PCCM00/OP46C3:10/QKQ1.191021.002/1595317900:user/release-keys/zh_CN
SD Maid: 5.0.1[50001]
Pro: 解锁器: 4.4.1 (40401)
Root: false
Storage: /storage/emulated/0 (SAF-match=false)

**Comment by d4rken** [comment]
How do the system screens for clearing cache in each application look like?

**Comment by bluepoi** [comment]
![Screenshot_2020-11-09-14-57-59-46](https://user-images.githubusercontent.com/73566190/98505234-15becb00-229c-11eb-8821-d0f4d43c9f05.jpg)
![Screenshot_2020-11-09-14-57-55-31](https://user-images.githubusercontent.com/73566190/98505244-1c4d4280-229c-11eb-9e5b-78212870e02e.jpg)
![Screenshot_2020-11-09-14-58-19-13](https://user-images.githubusercontent.com/73566190/98505252-1fe0c980-229c-11eb-8e3f-1679c95425b7.jpg)

**Comment by d4rken** [comment]
I can't type Japanese :fearful: 

Can you "record debug log" and "debug accessbility service"?

https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by bluepoi** [comment]
I record log in simplified Chinese.  Because it is also not supported on my device.
log：https://claris.lanzoui.com/i44Kiifh9uj

**Comment by bluepoi** [comment]
Log recorded in Japanese
https://claris.lanzoui.com/i6YuEifibna

**Comment by d4rken** [comment]
Chinese might be working with 5.0.6, can you confirm?

**Comment by bluepoi** [comment]
Yes, the new version 5.0.6 supports Chinese on ColorOS11 Android 11
