### ISSUE TITLE
Suggestion to clarify the description in the AppControl settings.

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4190]
В настройках AppControl слишком неявно назначение пункта "Перепроверка приложений". Назначение других настроек в общем понятно, а для этого пункта приходится открывать справку, чтобы посмотреть. Я несколько раз забывал его назначение и при появлении каких-либо ошибок в AppControl приходилось каждый раз смотреть в справке, не с этим пунктом ли они связаны. Предлагаю изменить описание пункта, чтобы сразу было понятно, какую именно ошибку он исправляет.

> In the AppControl settings, the purpose of the "Recheck applications" item is too implicit. The purpose of other settings is generally clear, but for this item you have to open the help to see. I forgot its purpose several times, and when any errors appeared in AppControl, I had to look in the help each time to see if they were related to this item. I suggest changing the description of the item so that it is immediately clear which error it is correcting.

![S01029-11582750(1)](https://user-images.githubusercontent.com/60130882/97547062-66057580-19de-11eb-90d8-0880c79b812e.jpg)

**Comment by d4rken** [comment]
How would you describe the option so that it easier to understand?

**Comment by Ingood5** [comment]
Какие именно состояния приложений могут быть определены неправильно, если отключен этот пункт? В AppControl есть эти: системное, пользовательское, замороженное запущенное, остановленное, boot, библиотека.

И что означает состояние "boot"? Не смог понять.

**Comment by Ingood5** [comment]
При активации этого пункта сканирование в AppControl должно быть дольше? У меня нет абсолютно никакой разницы. В справке на сайте выделено предупреждение, что пункт нужно активировать ТОЛЬКО при проблемах, поэтому я подумал, что сканирование должно быть дольше.

**Comment by Ingood5** [comment]
Вы не пропустили?


Я бы назвал:

ПЕРЕПРОВЕРКА ПРИЛОЖЕНИЙ.  Результаты сравниваются с файлом packages.xml, это исправляет проблемы на некоторых прошивках, при которых неправильно отображается состояние приложений (например, включено/отключено).  Если проблемы у Вас отсутствуют, не активируйте этот пункт.

**Comment by Ingood5** [comment]
Должно ли сканирование продолжаться дольше при включенном пункте? Я не заметил разницы

**Comment by Ingood5** [comment]
Вы не пропустили?
