### ISSUE TITLE
The number of multi-actions does not always correspond to the selected one.

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4200]
### What happened?
Количество мультидействий не всегда соответствует выбранному.

### SD Maid
Version: `4.15.15 (41515)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

**Comment by d4rken** [comment]
Can you give me an example, maybe a video?

**Comment by Ingood5** [comment]
1. Например, иногда возникает после принудительной остановки SD Maid (включены 3 мульти действия), при первом сканировании 2 мультидействия, при втором – 3:

[video.zip](https://github.com/d4rken/sdmaid-public/files/5506368/video.zip)

[sdmaid_logfile_1604840148067.txt.zip](https://github.com/d4rken/sdmaid-public/files/5506371/sdmaid_logfile_1604840148067.txt.zip)

2. Кроме этого, иногда инструменты запускаются не по порядку, например, сначала CorpseFinder и Базы данных, после этого остальные два. Пример для двух мульти действий:

[video 2.zip](https://github.com/d4rken/sdmaid-public/files/5506378/video.2.zip)

3. При изменении в настройках количества мультидействий появляется оповещение, что нужно перезапустить SD Maid, хотя на самом деле его нужно принудительно остановить. Желательно изменить текст оповещения.
