### ISSUE TITLE
Предложение сделать активацию очистки недоступных элементов при первом запуске.

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4202]
Возможно лучше сделать включённой по умолчанию очистку недоступных элементов и при первом запуске автоматически предлагать включить службу в специальных возможностях телефона. Я думаю, очистка кэша один из важных элементов, и она должна быть всегда полностью включена. И при включении службы в специальных возможностях телефона должно быть уведомление о необходимости разрешить для SD Maid работу в фоне (даже если очистка недоступных элементов включена самостоятельно в настройках телефона). Если на некоторых телефонах с ней могут быть трудности, то может быть просто возможность отказаться от этого.

**Comment by d4rken** [comment]
I'm unsure about this. In the beta the accessibility setup is part of the initial permission dialogs and if granted, it will be enabled like you described. I've gotten several emails already though about users complaining that SD Maid doesn't work in the "background", i.e. complaining about the screen overlay. :thinking:

**Comment by Ingood5** [comment]
> SD Maid doesn't work in the "background", i.e. complaining about the screen overlay. 

Можете описать подробнее?
