### ISSUE TITLE
Databases list doesn't display all app icons.

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4243]
### What happened?
В базах данных не отображаются иконки у некоторых приложений, например com.xvideostudio.videoeditor и com.estrongs.android.pop.

![S01109-11313412](https://user-images.githubusercontent.com/60130882/98518144-0d589700-2280-11eb-8a3f-2c23f661e050.jpg)

### SD Maid
Version: `4.15.15 (41515)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

**Comment by d4rken** [comment]
Difficult to debug. :frowning: 

Can you share a debug log?

**Comment by Ingood5** [comment]
[sdmaid_logfile_1605528973643.txt.zip](https://github.com/d4rken/sdmaid-public/files/5546121/sdmaid_logfile_1605528973643.txt.zip)
