### ISSUE TITLE
Oppo A9 (2020) incorrect work - again

### ISSUE THREAD

**Issue by Hunterus2020** [d4rken-org/sdmaid#4246]
Hello! 
Unfortunately, it still doesn't correct work. :(
Again, again, again...
![Screenshot_2020-11-11-07-38-40-33](https://user-images.githubusercontent.com/67745239/98768875-fab19f80-23f0-11eb-8aa5-584df6409d2b.jpg)

video:
https://drive.google.com/file/d/13wxcdIhHIoSPy_0JC9bqCN4x1ufuM1D6/view?usp=drivesdk

LOG:
https://drive.google.com/file/d/14IGXI1wq-uabhf5h1wO_mJVQyxlwND7h/view?usp=drivesdk

![98534276-46e7cd00-2295-11eb-8154-e2ef39cea2b1](https://user-images.githubusercontent.com/67745239/98768078-b6260400-23f0-11eb-8993-92e348e4c74d.jpg)

**Comment by d4rken** [comment]
I can see a few steps to code for SD Maid based on the video.

Would you be able to record  a debug log + demo a cache deletion for SD Maid?

"Record debug log" + "debug accessibility service", then just open the system screen for an app, and press the buttons to clear the cache.
