### ISSUE TITLE
Proposal to make it possible to create a shortcut for forced scanning of media

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4248]
Возможно добавить функцию добавления на главный экран ярлыка для принудительного сканирования медиа? Чтобы пользователь мог заранее выбрать список папок и затем при нажатии на ярлык на главном экране запускать сканирование медиа в этих папках. На моём телефоне через определённое время после сброса телефона до заводских настроек перестаёт автоматически сканироваться медиа в некоторых папках. И становится проблемой отправлять фото в некоторые мессенджеры, например в Вайбер, так как фото отображаются в нём только после сканирования. В галерее фото тоже не видно, увидеть его можно только через проводник, поэтому возникает много неудобств с отправкой фото и работой с ним. В гугл плее не нашёл ни одного удобного медиа сканера с возможностью выбрать для сканирования только нужные мне папки и сканировать их при нажатии на ярлык, не заходя в приложение. Если сканировать сразу все устройсво, то новые фото появляются в галерее не сразу, и пока идёт сканирование галерея тормозит, это неудобно. Использовать сканирование медиа, заходя каждый раз в проводник SD Maid тоже неудобно. Если я правильно понял, проблема с автоматическим сканированием медиа есть у многих пользователей. 

> Is it possible to add the function of adding a shortcut to the main screen to force scan media? So that the user can preselect a list of folders and then, when clicking on the shortcut on the main screen, start scanning media in these folders. On my phone, after a certain time after resetting the phone to factory settings, it stops automatically scanning media in some folders. And it becomes a problem to send photos to some instant messengers, for example to Viber, since the photos are displayed in it only after scanning. In the gallery, the photo is also not visible, you can see it only through the explorer, so there are many inconveniences with sending a photo and working with it. In Google Play, I did not find a single convenient media scanner with the ability to select only the folders I need for scanning and scan them when I click on the shortcut without going into the application. If you scan the entire device at once, then new photos do not appear in the gallery immediately, and while scanning is in progress, the gallery slows down, this is inconvenient. It is also inconvenient to use media scanning by entering the SD Maid explorer every time. If I understand correctly, many users have a problem with automatic media scanning.

**Comment by d4rken** [comment]
It's technically possible, but it seems very niche, only very few advanced users would need this :thinking:

**Comment by Ingood5** [comment]
Возможно, было бы лучше, если бы такая функция появилась. Если эта функция есть в проводнике, то с помощью ярлыка ее использование может стать более удобным. Если я правильно понял, проблема со сканированием медиа не возникает на телефонах однократно, то есть если у кого-то функция работает плохо, то она будет работать так постоянно. Так как сканирование медиа уже есть в проводнике, при постоянно возникающих проблемах с медиасканером пользователю было бы намного удобней использовать его не заходя постоянно в проводник. Постоянно заходить в проводник, проматывать к нужной папке, выделять ее и выбирать пункт в меню – очень не удобно.
