### ISSUE TITLE
AppCleaner: "Skip Running" is not working

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4270]
### What happened?
Если в настройках AppCleaner включить пункт "Пропустить работающие", то приложения все равно не пропускаются.

### SD Maid
Version: `4.15.15 (41515)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

**Comment by d4rken** [comment]
Do you have an example?

**Comment by Ingood5** [comment]
[video.zip](https://github.com/d4rken/sdmaid-public/files/5616323/video.zip)

**Comment by d4rken** [comment]
I think this is caused by problems to determine running apps on newer Android versions (#946) there is currently no solution except root.

Maybe we should hide the option on affected devices.
