### ISSUE TITLE
Bug: The error is displayed when enabling the accessibility service

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4271]
### What happened?
При включении службы специальных возможностей через настройки SD Maid, пункт "служба специальных возможностей" в настройках SD Maid поначалу все равно остаётся помечен, как будто служба в настройках телефона не включена, то есть слева от него стоит восклицательный знак. Повторяется каждый раз.

[video.zip](https://github.com/d4rken/sdmaid-public/files/5547370/video.zip)

### SD Maid
Version: `4.15.15 (41515)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

**Comment by d4rken** [comment]
Did the service work correctly afterwards? 

I mean: Is it a bug in the user interface, or a bug in the service :thinking:?

**Comment by Ingood5** [comment]
Ошибка в интерфейсе, служба работает.
