### ISSUE TITLE
Database Cleanup seems to be breaking Whatsapp's databases, needs further investigation

### ISSUE THREAD

**Issue by fabiorzfreitas** [d4rken-org/sdmaid#4273]
I never delete any message from Whatsapp, so my database files are quite big and it seems that the last 3 times (in 2 days) that I ran Database Cleanup, I had to restore my messages from a backup.

I didn't run more proper testing or tried to generate logs because I'm afraid to end up losing more — it's bad enough that I lost everything since my last daily backup.

For now, I had to add an exception to "whatsapp" in Database Cleanup scans, but I'm not sure of how that feature works and I don't know if I did it correctly.

**Comment by d4rken** [comment]
Can you share more details about your device?
* Root?
* Was WhatsApp running beforehand?
* Which options in SD Maid?
* Is it possibile you received messages while SD Maid was working?

**Comment by fabiorfreitas** [comment]
Hi there, here's some info:

I have Root and Pro version, the only setting I changed was scheduling a daily run of everything, but duplicate cleaner and reboot.

Whatsapp is running 24/7 on my device and it's likely I received messages while SD Maid was running, although I never received any warning when it started dealing with Whatsapp that I should close it.
