### ISSUE TITLE
Databases button has wrong state

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4303]
### What happened?
В базах данных после очистки кнопка внизу-справа остаётся оранжевой, как будто очистки ещё не было.

[video.zip](https://github.com/d4rken/sdmaid-public/files/5565630/video.zip)

### SD Maid
Version: `4.15.15 (41515)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

**Comment by d4rken** [comment]
Can you share a debug log of this?

**Comment by Ingood5** [comment]
[sdmaid_logfile_1606739696436.txt.zip](https://github.com/d4rken/sdmaid-public/files/5615901/sdmaid_logfile_1606739696436.txt.zip)
