### ISSUE TITLE
Questions about filter colors. 

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4318]
У меня вопросы про цвета, которыми помечены фильтры SystemCleaner и AppCleaner.

SystemCleaner:
1. Почему временные файлы помечены оранжевым? Их может быть опасно удалять?
2. Какие файлы входят в категорию Прочие файлы?
3. Почему пустые каталоги помечены жёлтым, а не зелёным? Их удаление не всегда безопасно?
4. Почему реклама жёлтым, а не зелёным? Удаление не всегда безопасно?
5. Почему файлы журнала жёлтым, а не зелёным? Удаление не всегда безопасно?
6. Почему обложки альбомов оранжевым?
7. Файлы мусора Linux и эскизы файлов слегка отличаются по оттенку от других фильтров зелёного цвета в этом окне. Это ошибка или их безопасней удалять?

AppCleaner:
1. Почему реклама, сообщения об ошибках, аналитика оранжевым? Какие именно сбои может вызвать удаление этих файлов?
2. Telegram не должен быть красным – #3551, хотя пока я не нашёл официальной информации в интернете для вас.
3. Скрытый кэш, корзины, старые копии сообщений WhatsApp нестандартного цвета с синим оттенком, они выпадают из шкалы зелёный-красный (зелёный, жёлтый, оранжевый, красный с их оттенками), неясна степень опасности их удаления относительно зелёного.

**Comment by d4rken** [comment]
In general, the color also represents a rating in regards to possible errors too: "How bad would it be if there is a bug in this filter."

> SystemCleaner:
> Why are temporary files marked orange? Could it be dangerous to delete them?

The system cleaner does not know "applications", so it can not know if the file it is deleting is being used by an app. The temporary file may be in use.

> What files are included in the Other Files category?

A few of SD Maids own internal file (sdm_write_test), a ROM file (mmsyscache) and an analytics file (bugsense).

> Why are empty directories marked in yellow instead of green? Is their removal not always safe?

Some applications use empty directories to mark something. Some applications only try to create folders once. They may have problems if they try to create a file in that folder, but the folder doesn't exist. Normally you should try to recreate the folder, but sometimes developers forget to do that.

> Why are ads yellow instead of green? Is deletion not always safe?

I don't know all ad sources, some could have problems, I didn't want to say it's safe when I don't know 100%.

> Why are the log files yellow instead of green? Is deletion not always safe?

I didn't want to say it's safe when I don't know 100%. The problem are files that could be in use.

> Why are the album covers orange?

Some users have reported that the album covers were not automatically recreated, and they had empty cover previews.

> Linux junk files and thumbnails are slightly different in tint from the other green filters in this window. Is this a bug or is it safer to delete them?

:thinking:  Yes they should be the same color. That's a bug.

> AppCleaner:

> Why are ads, bug reports, analytics orange? What kind of failures can cause deleting these files?

I can't predict how all analytics and ads software reacts to their files being deleted. Some are safer than others, but they are all in the same category.

> Telegram shouldn't be red - # 3551 , although I haven't found official information on the Internet for you yet.

:thinking: I'm not sure if it would not mean loosing some images, e.g. WhatsApp doesn't store the images on their servers to redownload.

> Hidden cache, trash cans, old copies of WhatsApp messages of a non-standard color with a blue tint, they fall out of the green-red scale (green, yellow, orange, red with their shades), the degree of danger of their deletion relative to green is unclear.

You are right. We should change that. Which colors would be fitting? :thinking:

**Comment by Ingood5** [comment]
Чем может грозить удаление временного файла?

Реклама в SystemCleaner и AppCleaner разного цвета. Или это разные виды рекламы? В SystemCleaner написано "Файлы, созданные рекламными программами", по смыслу это больше относится к Adware, нежелательному программному обеспечению. А на Андроиде реклама это норма для многих приложений. Поэтому не понятно, это разные типы фильтров или нет. И второе: в случае если это одинаковые типы фильтров, как SystemCleaner распознаёт рекламные файлы? У них нет общего обозначения, например как расширение ".log" у лог-файлов.

Оранжевый цвет рекламы, сообщений об ошибках и аналитики по оттенку отличается от других оранжевых цветов в SystemCleaner и AppCleaner.

> A few of SD Maids own internal file (sdm_write_test), a ROM file (mmsyscache) and an analytics file (bugsense).

"A few of SD Maids" – здесь вы имеете ввиду "некоторые старые версии SD Maid"?

> Telegram shouldn't be red - # 3551 , although I haven't found official information on the Internet for you yet.

> 🤔 I'm not sure if it would not mean loosing some images, e.g. WhatsApp doesn't store the images on their servers to redownload.

100% что все фото, видео, аудиофайлы, голосовые сообщения и любые другие файлы, отравленные пользователем, всегда хранятся на серверах и доступны для загрузки после повторной установки Telegram, даже если он используется на одном устройстве и файлы удалены у всех пользователей. Можно загрузить любые файлы, которые были отправлены или получены несколько лет назад. Просто я пока не нашёл для вас официальной информации в интернете.

> Hidden cache, trash cans, old copies of WhatsApp messages of a non-standard color with a blue tint, they fall out of the green-red scale (green, yellow, orange, red with their shades), the degree of danger of their deletion relative to green is unclear.

> You are right. We should change that. Which colors would be fitting?

Эти файлы не подходят под какую-то уже существующую категорию? Иначе придётся создать категорию с помощью оттенков, например, светло-зелёный и темно-зелёный, или светло-оранжевый и темно-оранжевый. Между какими цветами должен быть этот цвет?
