### ISSUE TITLE
Explorer: Permission changes are not reflect in the UI

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4359]
### What happened?
В проводнике у файлов и папок не меняется разрешение. То есть если повторно открыть диалоговое окно, в котором меняются разрешения, галочки будут в той же позиции, что и до изменений.

### SD Maid
Version: `5.0.3 (50003)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

**Comment by d4rken** [comment]
Does it show the correct permissions when reloading the path?

**Comment by Ingood5** [comment]
Если вы об этом, то нет:
[VIDEO.zip](https://github.com/d4rken/sdmaid-public/files/5647153/VIDEO.zip)

**Comment by Ingood5** [comment]
Что означает "Установить рекурсив"?

**Comment by d4rken** [comment]
> Что означает "Установить рекурсив"?

Set for folder and all sub folders/files inside.

**Comment by Ingood5** [comment]
Возможно, лучше "Установить рекурсив" переименовать, чтобы было более понятно для обычных пользователей.

**Comment by HSA2020-cod1** [comment]
> ### What happened?
> В проводнике у файлов и папок не меняется разрешение. То есть если повторно открыть диалоговое окно, в котором меняются разрешения, галочки будут в той же позиции, что и до изменений.
> 
> ### SD Maid
> Version: `5.0.3 (50003)`
> Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`
> 
> ### Device
> Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
> Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`
