### ISSUE TITLE
AppCleaner behavior when accessibility and or "unavailable items" are disabled

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4363]
### What happened?
Если в настройках SD Maid включено отображение недоступного кэша, но отключена служба специальных возможностей, то недоступный кэш все равно очищается (в настройках телефона служба включена)

[sdmaid_logfile_1606912438623.txt.zip](https://github.com/d4rken/sdmaid-public/files/5629301/sdmaid_logfile_1606912438623.txt.zip)

Это происходит в том числе если выполнить последовательность действий:
1. При включённой очистке недоступного кэша запустить сканирование.
2. В настройках SD Maid отключить службу специальных возможностей и отображение недоступного кэша.
3. Запустись очистку.

В этом случае недоступный кэш очищается даже при отключённом отображении недоступного кэша.

### SD Maid
Version: `5.0.3 (50003)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

**Comment by d4rken** [comment]
> If the display of an unavailable cache is enabled in the SD Maid settings, but the accessibility service is disabled, the unavailable cache is still cleared (the service is enabled in the phone settings) sdmaid_logfile_1606912438623.txt.zip 


> This also happens if you perform the following sequence of actions: When clearing unavailable cache is enabled, run scanning. In SD Maid settings, disable accessibility service and display unavailable cache. Start cleaning. In this case, the unavailable cache is cleared even if unavailable cache mapping is disabled.

I will check the code, if "inaccessible cache" items are shown, and then the setting is disabled, the will still be in the results and SD Maid should attempt to delete them if they are visible in the results.

But if the accessibility service is disabled, it should not be used. Maybe I'm checking the system state instead of the setting in SD Maid :thinking:
