### ISSUE TITLE
AppCleaner Accessibility Service based operations hanging on "Media Storage" app

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid#4443]
The media storage apps shows as having cache, but also it's clear cache button is disabled.

Adding an exclusion for this app works, but maybe we can understand why/when this state is reached and have SD Maid recognize it :thinking: 

https://user-images.githubusercontent.com/1439229/102711043-1002cf00-42b7-11eb-8fde-53d0f425a11d.mp4

**Comment by sick13** [comment]
this started happening on Android 11 (S10+ Exynos OneUI3.0) added to exclusion like the OP mentioned and now it works
