### ISSUE TITLE
FR: Allow "Show/Hide tabs" UI to reorder tabs

### ISSUE THREAD

**Issue by Gitoffthelawn** [d4rken-org/sdmaid#4463]
Greetings Matthias!  It's been a long time since we've communicated.  I hope you are well!

I find that I use SD Maid tools in a different order than is presented in the side-menu.  For example, I always run `AppCleaner` before `SystemCleaner` because `AppCleaner` usually causes some folders to become empty, which `SystemCleaner` can then remove.

Could the `Show/Hide tabs` UI be improved to allow the user to specify the order the tabs will be listed?

Thanks, and be well!

**Comment by d4rken** [comment]
Happy to hear from you! I hope you and your loved ones are healthy!

I don't see me implementing this soon, but it would certainly be possible.

What do you do at each step, look through things?

Would it help you if we change the automatic execution flow of QuickStart?
"If SD Maid is set to serial execution, run system cleaner after appcleaner" :thinking:

**Comment by Gitoffthelawn** [comment]
> Happy to hear from you! I hope you and your loved ones are healthy!

Thank you! You too!  We are all well.  We are staying away from other humans, which actually hasn't been that bad!  With all the video-conferencing opportunities, it really hasn't been that hard to stay connected with others without getting exposed to COVID.

> I don't see me implementing this soon, but it would certainly be possible.

I'm an optimist, so I'll focus on the possibility!

> What do you do at each step, look through things?

Yes, I set SD Maid to be pretty aggressive, so I make sure nothing is getting deleting that I don't want to lose.  I think one time it wanted to delete a couple thousand photographs, so I keep a close eye on it!  Undoubtedly, I set it too aggressive, but it was a close enough call to warrant being cautious.

> Would it help you if we change the automatic execution flow of QuickStart?
> "If SD Maid is set to serial execution, run system cleaner after appcleaner"

It's funny you mention that possibility.  Before posting this issue report, I originally was thinking more along those lines.  I honestly thought it would be easier just to allow reordering the menu, as the only noticeable change would be to add sliders to the items in the `Show/Hide tabs` page.

*When you mention `QuickStart`, you are referring to `QuickAccess`, correct?*

I like the idea behind `QuickAccess` (QA) , but I find that it takes too many taps if you want to ensure each step is doing what you really want (which is why I'm guessing you asked if look at each step).  With QA, you pretty much have 2 choices:

1. Use the "reload" icons (round arrows).  They are efficient if you don't review what is about to be deleted, but that feels too risky to me.  If you review the changes, the number of taps required makes them rather inefficient.
2. Use the area to the left of the "reload" icons.  This works much like the side-menu, but the big issue is that the back button does not go back to the QA page.  Thus, you wind up having to use both the QA page and the side-menu, which gets disorienting and requires extra taps.

*So, what are some different possible solutions?*  Here are the results of my initial brainstorming:

1. Allow the side-menu order to be edited.  This is the original proposal for this issue report.
2. Simply move `AppCleaner` above `SystemCleaner` in the side-menu.  That's obviously the quickest to implement, as it likely just requires changing 2 lines of code.  WFM.
3. Allow the back button to return to the QA menu when a page is called from the QA menu.
4. Rethink the whole QA and side-menu thing.  I envision them being integrated into a customizable SD Maid "home page".  That page would be shown when SD Maid starts and all navigation would be performed from it.  No side-menu or QA to maintain... just a single unified UI to display each module.  It could even be a grid of tiles, each of which the user would drag into their desired position.

That's my braindump... what are *your* thoughts?

Outside of all this technical stuff, I'm real happy to hear that you and yours are doing well.  😃

**Comment by d4rken** [comment]
> That's my braindump... what are your thoughts?

> Allow the side-menu order to be edited. This is the original proposal for this issue report.
Thinking more about it, I don't think I'll add this.

> Simply move AppCleaner above SystemCleaner in the side-menu. That's obviously the quickest to implement, as it likely just requires changing 2 lines of code. WFM.

This would be an option, I don't mind this, but would prefer to hear more user opinions on that, but how :thinking: 

> Allow the back button to return to the QA menu when a page is called from the QA menu.

This has come up a few times already, while also not being trivial, it would be something more users requested, and be more effective to allowing the workflow you are describing, right? I think there is a ticket about this? Isn't there? :thinking: 

> Rethink the whole QA and side-menu thing. I envision them being integrated into a customizable SD Maid "home page". That page would be shown when SD Maid starts and all navigation would be performed from it. No side-menu or QA to maintain... just a single unified UI to display each module. It could even be a grid of tiles, each of which the user would drag into their desired position.

I tried grids for but there is just not enough horizontal space for progress messages to make any sense then. I kinda like the idea though, but due to the large established userbase it would probably end in a shitstorm if I just change the UI like that, everyone has existing workflows they used to... :wink:

**Comment by Gitoffthelawn** [comment]
I'm still interested in all this, but for now, how about moving "AppCleaner" above "SystemCleaner" so that "SystemCleaner" cleans up empty folders left by "AppCleaner" when you run them in the presented order?
