### ISSUE TITLE
Request: Hide SD maid Pro 

### ISSUE THREAD

**Issue by SauravDharwadkar** [d4rken-org/sdmaid#4484]
### What should the feature do?
Hide app from launcher menu     

### When/How would you use it?
After verification of license.  

### How would you implement it?
https://stackoverflow.com/questions/19114439/android-hide-unhide-app-icon-programmatically

### Comments
Sd maid pro doesn't ask for any permission so it will work in android Q+ devices too IG
### SD Maid
Version: `5.0.6 (50006)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `Realme/RMX1851/RMX1851:10/QKQ1.190918.001/1597290604:user/release-keys`

**Comment by d4rken** [comment]
Hiding is no longer supported by Android.

There may be a few options for rooted users that I have not looked into.
I'm not sure if that's a good approach though.

TBD

**Comment by SauravDharwadkar** [comment]
according to documentation of android , if android doesn't ask for any permission it can be hide launcher activity , i didn't try personality but its possible IG

**Comment by Dreiundachzig** [comment]
If Sleep as Android could solve this problem you can do it too.
