### ISSUE TITLE
Repeated APK extraction not working

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4493]
### What happened?
Нельзя повторно извлечь APK одного и того же приложения, пока APK файл не удалён. SD Maid сообщает что извлечение успешно, но не извлекает.

### SD Maid
Version: `5.0.6 (50006)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

**Comment by d4rken** [comment]
Explorer or AppControl?

Can you provide a debug log?

**Comment by Ingood5** [comment]
AppControl.

[sdmaid_logfile_1610253410469.txt.zip](https://github.com/d4rken/sdmaid-public/files/5792242/sdmaid_logfile_1610253410469.txt.zip)


Я неправильно написал. APK повторно извлекается, но при этом стирается файл APK, который создался при предыдущем извлечении.
