### ISSUE TITLE
Scans for a long time with a large number of files.

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4542]
### What happened?
Если на телефоне большое количество файлов (в моём случае много разархивированных APK), то SystemCleaner и Базы Данных сильно долго сканирует.

[VIDEO.zip](https://github.com/d4rken/sdmaid-public/files/5856195/VIDEO.zip)

[sdmaid_logfile_1611321704815.txt.zip](https://github.com/d4rken/sdmaid-public/files/5856199/sdmaid_logfile_1611321704815.txt.zip)

### SD Maid
Version: `5.0.7 (50007)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

**Comment by d4rken** [comment]
The logs show about 400.000+ files for SD Maid to scan.
This will just take time, there is no way to change that.

It's possible that some of the SystemCleaner filters are more costly than others.

Is there a specific filter that makes everything a lot slower?

**Comment by Ingood5** [comment]
Время сканирования при одинаковом количестве файлов:
Lost dir – 1:04 
Эскизы – 1:12
Файлы мусора Windows – 1:14
Файлы мусора MacOS – 1:57

Остальные фильтры ≈ 0:54

**Comment by Ingood5** [comment]
Чем больше одновременно включённых фильтров, тем меньше операций в секунду. Это нормально? Разница при отключении всех фильтров примерно в 5 раз. 

![IMG_20210210_072547](https://user-images.githubusercontent.com/60130882/107464390-3a636100-6b71-11eb-9ff2-09d20f51a0b7.jpg)

**Comment by d4rken** [comment]
> Чем больше одновременно включённых фильтров, тем меньше операций в секунду. Это нормально? Разница при отключении всех фильтров примерно в 5 раз.

Yes. Every file that is found has to be compared all enabled filters. When more filters are enabled, more comparisons have to be made.

If there is a specific filter that makes the whole operation a lot slower than other filters, then I can look if it is possible to optimize it.

Generally speaking, filters work most efficiently if they have simple and easy abort conditions, e.g. by checking if the base path contains a certain string before doing more expensive comparisons.

**Comment by Ingood5** [comment]
> If there is a specific filter that makes the whole operation a lot slower than other filters, then I can look if it is possible to optimize it.

В моем сообщении выше видно какой фильтр дольше, фильтр MacOS:

> Время сканирования при одинаковом количестве файлов:
Lost dir – 1:04
Эскизы – 1:12
Файлы мусора Windows – 1:14
Файлы мусора MacOS – 1:57
Остальные фильтры ≈ по 0:54
