### ISSUE TITLE
Clutterreport: /storage/emulated/0/.gs_file

### ISSUE THREAD

**Issue by vvvnightwishvvv** [d4rken-org/sdmaid#4563]
### Target
Target: `/storage/emulated/0/.gs_file`
Prefix-free: `.gs_file`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `AlipayHK`
Packagename: `hk.alipay.wallet`
Version: `3.15.1.1 (248)`

### Current owners
Appname: `?`
Packagename: `com.eg.android.AlipayGphone`
Version: ` (-1)`

Appname: `?`
Packagename: `com.uc.browser.en`
Version: ` (-1)`

Appname: `?`
Packagename: `com.UCMobile.testch`
Version: ` (-1)`

Appname: `?`
Packagename: `com.uc.browser.hd`
Version: ` (-1)`

Appname: `?`
Packagename: `com.UCMobile.intl`
Version: ` (-1)`

Appname: `?`
Packagename: `com.UCMobile.x86`
Version: ` (-1)`

Appname: `?`
Packagename: `com.uc.browser`
Version: ` (-1)`

Appname: `?`
Packagename: `com.UCMobile.xiaoma`
Version: ` (-1)`

Appname: `?`
Packagename: `com.UCMobile.ac`
Version: ` (-1)`

Appname: `?`
Packagename: `com.UCMobile`
Version: ` (-1)`

Appname: `?`
Packagename: `com.alibaba.aliexpresshd`
Version: ` (-1)`

### SD Maid
Version: `5.0.7 (50007)`

### Device
Fingerprint: `samsung/d2qzh/d2q:10/QP1A.190711.020/N9750ZSU3DTL2:user/release-keys`

**Comment by d4rken** [comment]
How do you know this app created the file?

**Comment by d4rken** [comment]
https://github.com/d4rken-org/sdmaid-se/pull/196
