### ISSUE TITLE
The hidden cache is not cleared when the phone is rotated horizontally.

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4599]
### What happened?
Если с включенным автоповоротом провернуть телефон, то экран зависает на очистке скрытого кэша

[sdmaid_logfile_1613273087617.txt.zip](https://github.com/d4rken/sdmaid-public/files/5976949/sdmaid_logfile_1613273087617.txt.zip)

### SD Maid
Version: `5.0.7 (50007)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Redmi/dandelion_ru/dandelion:10/QP1A.190711.020/V12.0.3.0.QCDRUXM:user/release-keys`

**Comment by d4rken** [comment]
Can you share a video?

Is SD Maid not finding the elements? Does SD Maid scroll?

**Comment by Ingood5** [comment]
[VIDEO.zip](https://github.com/d4rken/sdmaid-public/files/6007914/VIDEO.zip)
Надеюсь на видео все что вам нужно.

**Comment by d4rken** [comment]
In landscape mode, are the buttons at the bottom hidden below the progress bar from SD Maid?

Are they different?

Same behavior in english?

Can you show me screenshot in english of portrait and landscape?

**Comment by Ingood5** [comment]
Кнопки внизу скрыты и в виде пейзажа и в виде портрета:

![Screenshot_2021-02-22-03-25-54-243_uplayer video player](https://user-images.githubusercontent.com/60130882/108644552-8642ce00-74c0-11eb-813c-476d48ed6fa9.jpg)
![Screenshot_2021-02-22-03-27-21-920_uplayer video player](https://user-images.githubusercontent.com/60130882/108644554-8773fb00-74c0-11eb-912b-be2286279fd0.jpg)


Если зайти в настройки в пейзажном режиме без SD Maid, то на кнопках внизу нет надписей, скорее всего проблема из-за этого:

![Screenshot_2021-02-22-03-21-46-516_com miui securitycenter](https://user-images.githubusercontent.com/60130882/108644588-b9855d00-74c0-11eb-8e6f-04aac43b7725.jpg)
![Screenshot_2021-02-22-03-39-53-573_com miui securitycenter](https://user-images.githubusercontent.com/60130882/108644589-ba1df380-74c0-11eb-84d8-2234813d273f.jpg)


На английском такое же поведение.

Скриншоты на английском:

![Screenshot_2021-02-22-03-41-41-701_uplayer video player](https://user-images.githubusercontent.com/60130882/108644610-cd30c380-74c0-11eb-8159-560048a3cffd.jpg)
![Screenshot_2021-02-22-03-42-36-402_uplayer video player](https://user-images.githubusercontent.com/60130882/108644612-cdc95a00-74c0-11eb-9b9c-2fc60a42b693.jpg)
![Screenshot_2021-02-22-03-38-21-260_com miui securitycenter](https://user-images.githubusercontent.com/60130882/108644614-ce61f080-74c0-11eb-80f9-85b257c972ed.jpg)
![Screenshot_2021-02-22-03-38-10-519_com miui securitycenter](https://user-images.githubusercontent.com/60130882/108644615-cefa8700-74c0-11eb-8aaf-f1fa4cd19735.jpg)

**Comment by d4rken** [comment]
https://github.com/d4rken-org/sdmaid-se/pull/206
