### ISSUE TITLE
/storage/emulated/0/MIUI/Gallery

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4600]
Для папки /storage/emulated/0/MIUI/Gallery нужно исключить всех владельцев, кроме com.miui.gallery.

/storage/emulated/0/MIUI/Gallery/cloud/.trashBin — корзина.

/storage/emulated/0/MIUI/Gallery/cloud/.cache — по всей видимости кэш.
[pathdump#_storage_emulated_0_MIUI_Gallery_cloud_.cache#1613273818894.txt](https://github.com/d4rken/sdmaid-public/files/5976976/pathdump._storage_emulated_0_MIUI_Gallery_cloud_.cache.1613273818894.txt)

**Comment by d4rken** [comment]
https://github.com/d4rken-org/sdmaid-se/pull/197
