### ISSUE TITLE
Bug: Ошибка с отправкой отчёта

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4601]
### What happened?
Не отправляются отчёты по папкам в /storage/emulated/0/MIUI/ из-за большого количества предлагаемых владельцев. Например этот https://github.com/d4rken/sdmaid-public/issues/4600

![Screenshot_2021-02-14-06-54-54-296_com android chrome](https://user-images.githubusercontent.com/60130882/107868190-3dbd5c00-6e93-11eb-8df0-2b7c11ee7f75.jpg)

### SD Maid
Version: `5.0.7 (50007)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Redmi/dandelion_ru/dandelion:10/QP1A.190711.020/V12.0.3.0.QCDRUXM:user/release-keys`

**Comment by d4rken** [comment]
:open_mouth: not sure how to solve this besides truncating the list if it gets too large.

How many entries are there?

**Comment by Ingood5** [comment]
53 владельца.

**Comment by Ingood5** [comment]
Я думаю, можно убрать всех владельцев, оставив только владельца Система Андроид. Например как у папки Pictures.

![IMG_20221110_134050](https://user-images.githubusercontent.com/60130882/201070514-2c777b28-b184-433a-970e-c9567f310326.jpg)

Из-за большого числа владельцев отчёты из этой папки приходится отправлять вручную (не через SD Maid), и AppCleaner дольше сканирует эту папку, в некоторых случаях разница заметна (замедляется именно на этой папке) 😟
