### ISSUE TITLE
Bug: Ошибка в проводнике

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4614]
### What happened?
После открытия проводника при первой отправке отчёта долго открывается окно отправки отчёта.

[VIDEO.zip](https://github.com/d4rken/sdmaid-public/files/5995678/VIDEO.zip)

[sdmaid_logfile_1613565181569.txt.zip](https://github.com/d4rken/sdmaid-public/files/5995682/sdmaid_logfile_1613565181569.txt.zip)

### SD Maid
Version: `5.0.7 (50007)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Redmi/dandelion_ru/dandelion:10/QP1A.190711.020/V12.0.3.0.QCDRUXM:user/release-keys`

**Comment by d4rken** [comment]
Thanks for the video. This is normal.

SD Maid has to load the app and ownership data. After loading it once, it is cached until SD Maid is killed.

**Comment by Ingood5** [comment]
Вы попытаетесь это оптимизировать?

На телефоне с 4 Гб ОЗУ такой проблемы не замечал, на телефоне с 2 Гб ОЗУ она появилась.

**Comment by d4rken** [comment]
I can look into it, but I think SD Maid is mostly just waiting for the system to provide the data.
