### ISSUE TITLE
Error downloading tablet.

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4624]
Планшет Lenovo A7600-H. В Google play маркете на странице SD Maid сообщение "Возможно это приложение не оптимизировано для вашего устройства". При установке скачивается старая версия 3.1.5.4. Но на планшете Андроид 4.2, должна скачиваться версия 4.15.15. Можете проконсультировать, из-за чего может быть такая проблема? Почему Google play уведомляет, что приложение возможно не оптимизировано? И почему при установке скачивается сильно старая версия?

**Comment by d4rken** [comment]
What Android version is this?

I did not programm a specific Tablet UI, which is why Google says it has not been optimized, but I shouldn't affect performance.

**Comment by Ingood5** [comment]
Android 4.2. И по какой-то причине устанавливается SD Maid версии 3.1.5.4. Скачал вручную со стороннего сайта версию 4.15.15, работает. Я думал, что устанавливается старая версия из-за того что SD Maid не поддерживает определенные планшеты.

**Comment by d4rken** [comment]
I do not know why this happens.

It's possible that Google requires more things for newer versions of apps for tablets.

I will try to test it on a larger tablet but I have no plans to work on tablet specific features, so I'm not sure how to fix this, there is no setting in Google Play that changes which devices get it, Google Play determines this on based on the APK.

It's possible that a human at Google determined the newer version is no longer fit for tablets?

**Comment by Ingood5** [comment]
> Возможно, человек из Google решил, что новая версия больше не подходит для планшетов?

Возможно 😟
