### ISSUE TITLE
Search does not work in hidden sections.

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4639]
### What happened?
Поиск не ищет в скрытых разделах, хотя через проводник в эти разделы можно зайти и даже скопировать оттуда файлы.

### SD Maid
Version: `5.0.8 (50008)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Redmi/dandelion_ru/dandelion:10/QP1A.190711.020/V12.0.3.0.QCDRUXM:user/release-keys`

**Comment by d4rken** [comment]
What is a hidden path?

Can you give examples and a debug log?

Thanks!

**Comment by Ingood5** [comment]
Я имел ввиду некоторые разделы root, к которым есть доступ без root.

Например есть файл /system/ro.prop. Его можно открыть через проводник, посмотреть его содержимое, скопировать файл себе. Но поиск его не находит.

[sdmaid_logfile_1614592675873.txt.zip](https://github.com/d4rken/sdmaid-public/files/6060693/sdmaid_logfile_1614592675873.txt.zip)
