### ISSUE TITLE
Bug: Doesn't clear cache on Android 8.1

### ISSUE THREAD

**Issue by Vladislav4KZ** [d4rken-org/sdmaid#4669]
### What happened?
SD Maid doesn't clear cache on Android 8.1 (Security patch October 5, 2020) Without root

### What did you expect to happen?
Expected to clear the cache, but it doesn't.

### How can I reproduce the issue?
Just regular cleaning cache, I press the "Scan" button and trying to clean cache (without root)

### Comments
I have given the app all permissions and enabled the service in accessibility settings
### SD Maid
Version: `5.1.0 (50100)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Meizu/meizu_C9_Public/meizuC9:8.1.0/OPM2.171019.012/1601963064:user/release-keys`

**Comment by Vladislav4KZ** [comment]
This is how it looks, the settings are opened several times but the cache does not clear.
![Screenshot_20210226-174430](https://user-images.githubusercontent.com/22411953/109617837-11773000-7b61-11eb-979b-6b340360417c.png)

I go manually into the application settings and see the cache the same size as shown in SD Maid

![Screenshot_20210302-141115](https://user-images.githubusercontent.com/22411953/109618349-9d895780-7b61-11eb-9bbf-28c284e18e24.png)

**Comment by Vladislav4KZ** [comment]
SD Maid recorded log
[sdmaid_logfile_1614673140253.txt.zip](https://github.com/d4rken/sdmaid-public/files/6067179/sdmaid_logfile_1614673140253.txt.zip)

**Comment by d4rken** [comment]
The screenshots look like AOSP, SD Maid tries to match #2910 .
Did Meizu change their OS design?

**Comment by Vladislav4KZ** [comment]
@d4rken this device has stock AOSP rom with minimal changes by meizu (statusbar icons, app icons, etc).

It's not flyme, and this Meizu model does not support flyme rom. AOSP is official stock rom
