### ISSUE TITLE
Widget size does not change on Redmi 9A

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4751]
### What happened?
На Redmi 9A не меняется размер виджета, с боков не появляются точки, с помощью которых нужно менять размер.

                                         
### SD Maid
Version: `5.0.11 (50011)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Redmi/dandelion_ru/dandelion:10/QP1A.190711.020/V12.0.7.0.QCDRUXM:user/release-keys`

**Comment by d4rken** [comment]
Can you share a logcat of this?
I don't have a Redmi 9A to test with, it might be difficult to fix.
Does it also happen with other launchers? NovaLauncher?

**Comment by Ingood5** [comment]
Проверил NovaLauncher и ещё несколько лаунчеров, везде изменение размера работает. В некоторых точки с боков появляются после нажатия и удержания пальцем, в некоторых при удержания пальцем появляется пункт меню "Изменить размер", во встроенном лаунчере во всплывающем меню только один пункт "Удалить".

Что именно записать в logcat? После начала записи создать виджет, нажать на него и задержать палец до появления меню?

**Comment by Ingood5** [comment]
Я немного ошибся, изменять размер виджета можно, но есть небольшая ошибка.

Чтобы слева и справа появились точки в других лаунчерах, достаточно сделать это:
1. Нажать и удержать палец на виджете.
2. Отпустить палец.

Чтобы точки появились на моем телефоне, нужно сделать это:
1. Нажать и удержать палец на виджете.
2. Переместить виджет в другое место (или подвигать его по экрану и вернуть на то же место).
3. Отпустить палец.

Вот logcat
[logcat.txt](https://github.com/d4rken/sdmaid-public/files/6374453/logcat.txt)
