### ISSUE TITLE
Option to delete all duplicates, and not leave a single copy

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4775]
Возможно, в настройках дубликатов нужно добавить возможность включения удаления всех дублей (чтобы не оставалось ни одной копии). По умолчанию удаление всех дублей будет отключено. Тот, кому эта функция удобна, мог бы ее включить.

Пример: я скачал сборник книг размером 11 Гб. В нем достаточно много дублей, а так же книг, которые мне не нужны. У книг, которые мне не нужны, я смог бы сразу удалять все дубли.

Так же часто попадаются дубли ненужных фото или скачанных документов, их тоже можно было удалять при поиске дубликатов, не оставляя копий.

Возможно, такое было бы удобно не только мне, тогда такую функцию можно добавить.

**Comment by d4rken** [comment]
That seems to be totally opposite to what the duplicates tool is intended for though?
Why not use a different tool for deletion, like the Explorer? or a gallery app?

**Comment by Ingood5** [comment]
У меня при поиске дубликатов почти каждый раз ненужные файлы, например, дубли уже ненужных торрент-файлов, созданные программами для скачивания торрентов (*.torrent); дубли уже ненужных гиф-файлов; дубли уже ненужных отправленных фото и других файлов, создаваемые месседжерами (не нужны и дубли, и оригиналы); дубли ненужных драйверов, которые я уже скинул на ПК, и так далее.

Если я уже запустил поиск дубликатов, удобно прямо из этого окна все это сразу помечать и удалять. По-моему у других пользователей такое тоже может часто встречаться, тогда для них это тоже было бы удобно.

По умолчанию опция будет выключена в настройках, тот, кому она удобна, может включить ее.
