### ISSUE TITLE
New Feature - Back-Up state of Frozen Apps & Re-apply 

### ISSUE THREAD

**Issue by marksjc** [d4rken-org/sdmaid#4889]
One of the chores I have to complete when switching devices is to re-apply the various settings for all Apps to stop and freeze bloat, Facebook and other unwanted junk installed by Samsung. Task is to review all apps (698 for me) including system apps and for select crapware: force stop, disable all autostart triggers, freeze app. A few must be frozen in particular sequence or related apps restart (eg, 4 grouped as Facebook).  Only those apps I've frozen are duplicative effort (81 for me) so a backup of that list with all applied settings, with confirm pass and a failed to apply list (for mismatch or missing in 2nd system) would save several hours of time.  This should support new device  and factory reset device.  Rather than create problems, any mismatch or failed update to any parameter should result no change to the (new version) app listed on exception/error report so that user can apply manually.

**Comment by marksjc** [comment]
May be outside of scope but many complex setup apps now backup and restore settings, email, file manager apps, calendar apps.  Any complex, intricate settings become rote.  Another approach would be a super-user type function to that could accomplish the steps for each app as a single batched function  (like a script), though that would drive a request to apply to new device similarly as backup/reapply).

**Comment by shabqty62** [comment]
سلام من چندتای از برنامه های از قبل نصب شده که همان برنامه های اصلی سیستم هستند را پاک کردم خواهش میکنم کمکم کنید به چه صورت میشود آن هارو برگرداند

**Comment by shabqty62** [comment]
> سلام من چندتای از برنامه های قبل از نصب شده که همان برنامه اصلی سیستم وجود دارد را پاک کردم خواهش می کنم کمک کنید چه صورت می شود آن هارو برگرداند
