### ISSUE TITLE
[FEATURE REQUEST] Add support to users who disable (Android Storage Access Framework aka Scoped Storage) even if they are using android 11 API 30

### ISSUE THREAD

**Issue by cpuuntery** [d4rken-org/sdmaid#5004]
You can disable Scoped Storage by using this shell command 

`adb shell sm set-isolated-storage off`

If you are using android 10 or lower, you need to connect your phone to a PC. But if you are using android 11, you can do it without a pc. because android 11 support adb over network. You just need to install Termux 

The developer just need to add a very simple if statement in the code
To check if Scoped Storage is enabled, and if Scoped Storage is enabled then app will use it. 
**BUT if it is disabled. Regardless of how high the API level is, the app will use THE GREAT AND VERY FAST JAVA FILE API.**

this will fix 
#4886
#4870
#4826

**Comment by d4rken** [comment]
Sounds interesting, how can I check if the user did this?

Are there good instructions how to do this that i could link in SD Maids wiki?

**Comment by dragonGod97677** [comment]
> You can disable Scoped Storage by using this shell command
> 
> `adb shell sm set-isolated-storage off`
> 
> If you are using android 10 or lower, you need to connect your phone to a PC. But if you are using android 11, you can do it without a pc. because android 11 support adb over network. You just need to install Termux
> 
> The developer just need to add a very simple if statement in the code
> To check if Scoped Storage is enabled, and if Scoped Storage is enabled then app will use it.
> **BUT if it is disabled. Regardless of how high the API level is, the app will use THE GREAT AND VERY FAST JAVA FILE API.**
> 
> this will fix
> #4886
> #4870
> #4826

This is interesting, and there's also another way to use adb without PC but needs one phone that supports OTG and termux can be also used to run the commands but there's other app can be used to open adb without long setups https://play.google.com/store/apps/details?id=com.htetznaing.adbotg ... I've done this kind of route and it works except fastboot commands but adb works fine

**Comment by dragonGod97677** [comment]
I'll try this tomorrow

**Comment by cpuuntery** [comment]
@d4rken 
Although I am not a programmer. But if I see any line of code, I can understand about 80% of it. I mess around with C, C++, C#, Java.
I spent hours looking at AOSP source code to find anything useful. But I found nothing useful to check if Scoped Storage is enabled or not.
So I think the best course of action is to add a new entry in advanced settings. **The new entry will be disabled by default and need the user to manually enable it after running the command**.

`adb shell sm set-isolated-storage off`

[![Screenshot-20210724-224921.png](https://i.postimg.cc/x1DtYMw6/Screenshot-20210724-224921.png)](https://postimg.cc/9rbGYRF9)

PS I edited my screenshot using MS Paint, so it is not the most polish thing ever, but you get the idea.

**Comment by dragonGod97677** [comment]
> @d4rken
> Although I am not a programmer. But if I see any line of code, I can understand about 80% of it. I mess around with C, C++, C#, Java.
> I spent hours looking at AOSP source code to find anything useful. But I found nothing useful to check if Scoped Storage is enabled or not.
> So I think the best course of action is to add a new entry in advanced settings. **The new entry will be disabled by default and need the user to manually enable it after running the command**.
> 
> `adb shell sm set-isolated-storage off`
> 
> [![Screenshot-20210724-224921.png](https://camo.githubusercontent.com/d97c69b857258f5e14d0bc881bb3ea0e8a4eedbf56968ba0dff8f98baa9e7db8/68747470733a2f2f692e706f7374696d672e63632f78314474594d77362f53637265656e73686f742d32303231303732342d3232343932312e706e67)](https://postimg.cc/9rbGYRF9)
> 
> PS I edited my screenshot using MS Paint, so it is not the most polish thing ever, but you get the idea.
Can you disable scope storage on older android version, I've trying it on android 8.1, sm command seem doesn't recognize it, it shows me the usage list

**Comment by cpuuntery** [comment]
@dragonGod97677 
This may be of useful to you. So I will go in further details about adb wifi in android 11

1- [you can read this article](https://android.gadgethacks.com/how-to/set-up-wireless-debugging-android-11-send-adb-commands-without-usb-cable-0302898/) to have a better understanding about how adb wifi works.
2- install termux from f-droid. Google play version in no longer updated. And the repos no longer works in the Google play version 
3- in termux you need to install a package called platform tools
4-pair by running the running command 
`adb pair localhost:port`
Then do `adb connect localhost:port`
for more details, you can read one of the developer comments [here](https://www.reddit.com/r/termux/comments/mmu2iu/announce_adb_is_now_packaged_for_termux).

**Comment by cpuuntery** [comment]
@dragonGod97677 
**There is no reason and need whatsoever to disable scoped storage on android 9 and lower**
 In android version before 10
 scoped storage is **optional to use**, and it is **only enforced for external SD card**

**Comment by dragonGod97677** [comment]
> @dragonGod97677
> This may be of useful to you. So I will go in further details about adb wifi in android 11
> 
> 1- [you can read this article](https://android.gadgethacks.com/how-to/set-up-wireless-debugging-android-11-send-adb-commands-without-usb-cable-0302898/) to have a better understanding about how adb wifi works.
> 2- install termux from f-droid. Google play version in no longer updated. And the repos no longer works in the Google play version
> 3- in termux you need to install a package called platform tools
> 4-pair by running the running command
> `adb pair localhost:port`
> Then do `adb connect localhost:port`
> for more details, you can read one of the developer comments [here](https://www.reddit.com/r/termux/comments/mmu2iu/announce_adb_is_now_packaged_for_termux).



I already know about this but thanks for sharing

**Comment by dragonGod97677** [comment]
> @dragonGod97677
> **There is no reason and need whatsoever to disable scoped storage on android 9 and lower**
> In android version before 10
> scoped storage is **optional to use**, and it is **only enforced for external SD card**

Oh okay then

**Comment by d4rken** [comment]
So far I had no success. Disabling scoped storage caused the device to hang randomly, and when it worked, I had no access to `/sdcard` at all, due to not being mounted? :thinking:
