### ISSUE TITLE
Disable animations during non-root appcleaner

### ISSUE THREAD

**Issue by Bluscream** [d4rken-org/sdmaid#5073]
Basically just set the global system settings

- window_animation_scale
- transition_animation_scale
- animator_duration_scale

to 0.0 and restore saved values on cancel and finish

**Comment by d4rken** [comment]
(Or root, but then SD Maid can just use root)

**Comment by Bluscream** [comment]
> This would require granting SD Maid WRITE_SECURE_SETTINGS via ADB though.



> (Or root, but then SD Maid can just use root)

you answered it to yourself there xD

**Comment by Bluscream** [comment]
<details>
<summary>Screenshot(s)</summary>
![image](https://user-images.githubusercontent.com/3318223/131409155-8f8ffee3-efa5-4c18-a7e2-72a6b41d2527.png)
![image](https://user-images.githubusercontent.com/3318223/131409158-f5dc1bef-72d0-4c8d-8756-b14dfa31afb6.png)
![image](https://user-images.githubusercontent.com/3318223/131409165-a6a13a17-2d4d-4f3d-a3ed-89f691137bb7.png)


![Screenshot](https)</details>
