### ISSUE TITLE
Exceptions for 'Path Nesting' under Duplicates cleaner

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/sdmaid#5199]
Hello @d4rken 

Under Duplicates cleaner settings, one of the preference is based on Path Nesting. Default is to prefer shallowly nested files.

Usually, deeply nested files are likely to be the ones that are better organised. For example, the same music file under /Downloads and /Downloads/Music. 

But there are times when shallowly nested files are preferred. For example, a file in the Documents folder that is sent on WhatsApp. In this case, if the file is saved in /Android/ Media/com.WhatsApp/WhatsApp/Media/WhatsApp Documents/Sent, then one would usually prefer the shallowly nested file.

If I prefer to keep the deeply nested file under Settings, the file in the default Documents folder would be deleted in the example above.

FEATURE REQUEST:

Whichever setting the user chooses, can you allow for exceptions? 

In the example above, if I can choose WhatsApp folder as an exception with default preference for deeply nested files, then the duplicate cleaner will delete the file in the WhatsApp folder, and not the one in Documents folder.

Same holds true for users preferring the default setting of keeping shallowly nested files. There may be instances where they could prefer deeply nested file as exception.

Allowing for exceptions with both choices would be a very useful feature addition.

Thanks.

**Comment by d4rken** [comment]
It's a cool idea but I fear that the amount of work I'd have to put into this feature is too much compared to the amount of users that would benefit (or use) this feature.

**Comment by d4rken** [comment]
Let's keep this open, see if others have an opinion on this.

**Comment by TheMysticS** [comment]
Thanks for considering the request.

How about providing just a basic exception model, where the user chooses the folders he would like to add to exceptions?

For example, let's assume the user has a preference for deeply nested files by default.

Under exceptions, he chooses the WhatsApp folder or let's say the Android folder (which is now the parent folder for WhatsApp files).

If duplicates are found, the app will delete the deeply nested file (in our example, this is the file in the WhatsApp or Android folder) because it is located in the folder (or path) defined under Exceptions.

However, if both files are inside the folder (or path) added to the Exceptions list (in our case it is the WhatsApp or Android folder), then the app will use the default setting of keeping the deeply nested file, and deleting the rest. 

The folders defined under exceptions list will come into play only when one of the duplicate files found is outside of the folders (or paths) added to the exceptions list.

Will this be difficult to implement?

**Comment by d4rken** [comment]
Difficult is relative. It's mostly about time cost and motivation.

My gut feeling says: I'd rather not work on this. This is not a fun feature for me. I'd rather spend that time on another task/project.

If this would be something that helps a lot of users or increases sales, then I might be motivated, but currently it looks like a very niche feature.
A few days now, a few days later, and a few hours in answering related support emails. SD Maid has a large user base, adding small niche features at this point is not a smart thing to do for me.

**Comment by TheMysticS** [comment]
Sure. Whatever works best for you and your app. 💯 👍🏼
