### ISSUE TITLE
Prefer files with extensions...

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/sdmaid#5215]
Under Settings for Duplicates, can you add another criteria:

**Prefer files with extensions.**

I'll give you an example when this is useful:

WhatsApp has a tendency to store some files without extensions, and even rename them with a generic name (such as DOC-20211205-WA0001). SD maid is able to identify the file for the purpose of duplicate cleaning and can retain the file in the WhatsApp folder, while deleting the others, depending on the settings.

When that happens, we lose the file with the correct name and if WhatsApp saves the file without the extension, it becomes very difficult to find it using the search function.

A setting that prefers a file with an extension defined will delete the file inside the WhatsApp folder, leaving the file which has a proper name and extension.

**Comment by d4rken** [comment]
Seems to be reasonable effort to implement. Not sure how niche this is though, is this a common thing?

Would like to hear some other users chime in. Or are there any forum threads with multiple users who would be helped by this?
