### ISSUE TITLE
Add support do not optimize SD Maid for correct operation of accessibility service

### ISSUE THREAD

**Issue by WoTflix** [d4rken-org/sdmaid#5228]
**Is your feature request related to a problem? Please describe.**
This service is malfunctioning
![Screenshot_20211208-125359](https://user-images.githubusercontent.com/95138610/145235318-60fd3a64-5795-42e7-a1b1-7e7d40d9e06e.png)

**Describe the solution you'd like**
Add support do not optimize SD Maid for correct operation of accessibility service
![Screenshot_20211208-163904](https://user-images.githubusercontent.com/95138610/145235399-886ccb3a-6931-4c6b-8428-1d0b5cfdfa72.png)

**Comment by d4rken** [comment]
Changing this setting stops the service from being killed?

**Comment by WoTflix** [comment]
> Changing this setting stops the service from being killed?

Yes

**Comment by COUPON4Vitamins** [comment]
I have set to not optimize and accessibility service still gets killed very soon after leaving app

**Comment by WoTflix** [comment]
> I have set to not optimize and accessibility service still gets killed very soon after leaving app

Step 1: Ensure accessibility service is disabled if enabled
Step 2: Do not optimize SD Maid
Step 3: Re-enable Accessibility Service for SD Maid

**Comment by COUPON4Vitamins** [comment]
Thanks hope that works for me let you know!

**Comment by COUPON4Vitamins** [comment]
I set setting back to optimize,  deactivated accessibility service, then not optimize and then reenabled accessibility service. And doesn't work unfortunately. Or did I do it wrong?

**Comment by WoTflix** [comment]
> I set setting back to optimize, deactivated accessibility service, then not optimize and then reenabled accessibility service. And doesn't work unfortunately. Or did I do it wrong?

Settings→AppCleaner→Select the check box for Accessibility Service

**Comment by COUPON4Vitamins** [comment]
There is no other app cleaner than ad maid

**Comment by COUPON4Vitamins** [comment]
I only see an optional persistent notification as a solution for this annoying problem.
