### ISSUE TITLE
AppControl App Export Folder Shortcut

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#5370]
### What happened?
                               
Если в AppControl после экспорта приложения на появившейся внизу панели нажать "Показать", то открывается не папка с apk, а каталог на уровень выше. То есть если экспорт в папку Download/1, то открывается папка Download.    

### SD Maid
Version: `5.3.10 (50310)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Redmi/dandelion_ru/dandelion:10/QP1A.190711.020/V12.0.14.0.QCDRUXM:user/release-keys`

**Comment by d4rken** [comment]
I can't reproduce this, can you share a debug log?

**Comment by Ingood5** [comment]
[sdmaid_logfile_1648778762081.txt.zip](https://github.com/d4rken/sdmaid-public/files/8394124/sdmaid_logfile_1648778762081.txt.zip)
