### ISSUE TITLE
Performance when browsing folders with large amount of files

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#5380]
Если в папке много файлов (около тысячи и больше) то папка медленно открывается. Если возможно, оптимизируйте.

**Comment by d4rken** [comment]
In Explorer?
Or StorageAnalyzer?

If Explorer:
It might be the "owner ship research", could you disable this in the option and see if speed improves?

**Comment by Ingood5** [comment]
Замедление вызывают 2 пункта: названный вами выше и "Приложения. Отметьте элементы, которые соответствуют фильтру очистки приложений".

**Comment by dragonGod97677** [comment]
![Screenshot_2022-03-28-08-17-07-22](https://user-images.githubusercontent.com/38875906/160307577-83068cef-9bf8-4af5-abc7-e264f0c25f8b.png)
It is slow if these 3 options is checked

Tested it with more than 3k files

**Comment by dragonGod97677** [comment]
On storage analyzer, kinda bit slow but i know why and that's because it sorts the files bigger to smaller

**Comment by Ingood5** [comment]
> It is slow if these 3 options is checked on explorer

У меня пункт SystemCleaner вызывает небольшое замедление на 3 секунды, остальные два пункта замедляют на 40 секунд. Проверил с 4500 файлов.

**Comment by d4rken** [comment]
There is nothing to really be done here.
If these options are enabled then SD Maid will perform 3 extra operations for all data in the folder.
Especially `Research owner` performs a large lookup to determine who could own a file.

**Comment by d4rken** [comment]
More work  = more time
