### ISSUE TITLE
Widget cleaning error

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#5420]
### What happened?
1. Я нажал на очистку на виджете. 
2. Пока идёт процесс очистки, я зашёл в SD maid.
3. Очистка на заканчивается на моих глазах, напротив каждого инструмента написано "удалено", но внизу остаётся кнопка "запустить сейчас", как будто очистки не было. Вместо нее должна быть кнопка "сканирование".

### SD Maid
Version: `5.3.15 (50315)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Redmi/dandelion_ru/dandelion:10/QP1A.190711.020/V12.0.14.0.QCDRUXM:user/release-keys`

**Comment by d4rken** [comment]
So this is mostly a UI issue, the deletion actually happened?

**Comment by Ingood5** [comment]
Удаление произошло, но кнопка не поменялась на "сканирование"
