### ISSUE TITLE
Schedule error

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#5421]
Для чего в расписании эта кнопка?

![IMG_20220327_151957](https://user-images.githubusercontent.com/60130882/160281105-bd15bcd8-e3ac-4a66-8d39-97ca610287f3.jpg)

Я думал для того чтобы из этого окна запустить очистку, но у меня не запускается, просто появляется надпись "Загрузка"

**Comment by d4rken** [comment]
The button launches the scheduler directly, it's a good way to test it without having to wait.

If it doesn't work, the timer based execution will probably also not work.

To say more I need a debug log.

**Comment by Ingood5** [comment]
[sdmaid_logfile_1648777774268.txt.zip](https://github.com/d4rken/sdmaid-public/files/8394045/sdmaid_logfile_1648777774268.txt.zip)

**Comment by Ingood5** [comment]
Расписание действительно не работает
