### ISSUE TITLE
scan /data/media/0/ instead of /storage/emulated/0/ for better performance [if root access is available]

### ISSUE THREAD

**Issue by railgun77** [d4rken-org/sdmaid#5442]
**Is your feature request related to a problem? Please describe.**
so many users complain about slow scan speed and even if the app granted [MANAGE_EXTERNAL_STORAGE] promission 
it will **still be slow** because of [fuse emulated / virtual filesystem] so scanning the real ext4/f2fs filesystem is light-years way better

**Describe the solution you'd like**
the solution is in the title

**Comment by d4rken** [comment]
Doing a bit of a clean up to free up my mind :broom:.

This is a good idea, [but it's not on SD Maid 1's roadmap](https://github.com/d4rken-org/sdmaid-se/wiki/FAQ#why-are-you-creating-sd-maid-se). Consider creating a new [ticket for SD Maid 2/SE](https://github.com/d4rken-org/sdmaid-se/issues) if this is still relevant.
