### ISSUE TITLE
CorpseFinder (Root) - Remnants detected but no data is deleted

### ISSUE THREAD

**Issue by MeloriTensei** [d4rken-org/sdmaid#5491]
**Describe the bug**
File seems to have been deleted but they show up again upon rescanning.

**Device**
Samsung Galaxy Note 10+ (d2s)
LineageOS Official 18.1 / Android 11 (April 19 2022 Patch)
Magisk 24.3 (24300), Zygisk No, Ramdisk Yes (Installed modules: [Dolby Atmos Razer Phone 2](https://github.com/reiryuki/Dolby-Atmos-Razer-Phone-2-Magisk-Module) ) (Superuser permissions given to: SD Maid only)

SD Maid version: 5.3.19 (50319) (Latest gplay_release)

To reproduce:
(From my observation and assumptions, this might work)
Based on my own case, I...:
1) Move apps to SD Card when still in OneUI
2) Do not format SD Card, change ROM to LineageOS
3) Insert SD Card, and use SD Maid to scan through CorpseFinder

**Video evidence**
https://user-images.githubusercontent.com/3746534/165297636-13ee0f8a-f53d-4a27-870d-fda3f6badfa3.mp4

**Debug log**
None atm (Accidentally deleted affected files manually before being able to recreate the issue)

**Comment by Nisarg12** [comment]
Same happens on my device, unrooted phone. It seems to list package directories which are already purged. I see many from old apps no longer on my device and they're absent under /Android/data as well.

**Comment by d4rken** [comment]
> and they're absent under /Android/data as well.

which `Android/data` though, if you have a removable sdcard (secondary public storage), there are two `Android/data` and usually the system creates default folders in both locations.

The video from @MeloriTensei  looks okay, if the apps are really uninstalled, then files should not appear again. In that case it would be a permission issue and bug of the "was deletion successful" check for the secondary public storage.

I'd need a log of that to further check that out.

**Comment by Nisarg12** [comment]
> 

Thank you; I figured the cause, just had a faulty SD card which would not allow memory change at all. Cannot perform move, delete or write operations on it. Think the app works as intended, apologize for the false alarm.
