### ISSUE TITLE
Bug: Copy/Paste mode lost when deleting files

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#5554]
### What happened?
1. Я выделяю папку или файл и нажимаю Копировать.
2. Удаляю удаляю какой-нибудь другой файл или папку.
3. После этого действия режим копирования отменяется, то есть вставить я уже не могу, мне приходится опять начинать с первого пункта.

### SD Maid
Version: `5.3.19 (50319)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Redmi/dandelion_ru/dandelion:10/QP1A.190711.020/V12.0.14.0.QCDRUXM:user/release-keys`

**Comment by d4rken** [comment]
I think this might be working as intended.
SD Maid doesn't if the copy/cut dataset is still correct after files have been deleted.

**Comment by Ingood5** [comment]
Я жму копировать на одном файле, после этого удаляю другой файл и режим копирования все равно отменяется.
