### ISSUE TITLE
[Off-Topic]: New App Idea: Battery Status

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/sdmaid#5613]
A simple app that:

1. Reports the battery status in real-time
2. Syncs the status to all devices in real-time
3. Provides custom notifications
4. Notification widget showing battery status for all devices
5. Home-screen widgets showing battery status for all devices

I have multiple phones, tablet and a smartwatch. If I have an app that shows me the battery status of all my devices real-time, that would be great.

It will offer notifications for:

1. When the battery is fully charged on a device connected to a charger.
2. When the battery on any device drops below 15%.
3. Multiple Custom Notifications that users can configure.

In this regard, SD Maid for WearOS with very basic features (1-click cleaning), including this one, would be great!

If possible, the app should use Google Play Services to sync this information, so users don't have to create a cloud account for this.

SD Maid for Windows, macOS and Linux would be great too. 😂😂

**Comment by d4rken** [comment]
Needs a server for syncing, so on-going costs. Without the server, the sync won't work.
On-going cost would only make sense for me with a subscription.
I don't think there are enough users willing to pay a subscription fee for an app that does this. :thinking: 

Does not seem too interesting to me :shrug:.

> In this regard, SD Maid for WearOS with very basic features (1-click cleaning), including this one, would be great!

Maybe once Google brings out a SmartWatch that I would buy, I could look into it :wink: 

> SD Maid for Windows, macOS and Linux would be great too. joyjoy

I agree, but completely different code needed :sweat_smile:.

**Comment by d4rken** [comment]
> Can't use Google Drive or similar for this?
> 
> There is this app that syncs clipboard using Google Drive:
> 
> https://play.google.com/store/apps/details?id=studio.onelab.clipboard&hl=en-GB

That's actually a cool idea. :thinking: 

Would it be useful without apps on Desktop or iOS?
Probably needs a WatchOS app :thinking:

**Comment by TheMysticS** [comment]
Most watch faces for WearOS support Phone Battery, but only of the device to which the watch is connected (watch can connect to only one device at a time).

I'm using Samsung Galaxy Watch4. I can see the battery status of the watch on my phone using the Galaxy Wear app. But it is currently buggy at the moment, and there are no notification or homescreen widgets.

I do get a notification on my phone when my watch battery is fully charged. But there is a lot that can be done to improve the overall experience.

As with Desktop and iOS support, you can consider making a browser extension if not a full fledged app for these platforms (it will be wonderful if you make one though).

**Comment by d4rken** [comment]
Out of Scope for SD Maid, but my new app Octi basically does something similar:
https://github.com/d4rken-org/octi
