### ISSUE TITLE
AppControl: New Label AND Filter for Sideloaded Apps

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/sdmaid#5618]
Can we have one more label AND Filter for apps: **Sideloaded Apps**?

These are apps that have been installed using the Package Manager. Those that are neither from Google Play Store nor from OEM managed Stores like Samsung Galaxy Store, Huawei App Gallery, etc. 

Please note that apps installed using 3rd party App Stores like f-droid or others would still be counted as Sideloaded apps.

Thanks.

**Comment by d4rken** [comment]
Not a bad idea :thinking: 
So we'd need to collect a list of OEM store identifiers?
Or we mark everything except Google Play as "sideloaded"?

**Comment by TheMysticS** [comment]
> Not a bad idea 🤔 So we'd need to collect a list of OEM store identifiers? Or we mark everything except Google Play as "sideloaded"?

We'll have to collect those identifiers, which I believe isn't too many (isn't it just one per brand?):

1. Samsung
2. Huawei
3. Oppo
4. Vivo
5. OnePlus - None
6. Nothing - None
7. Nokia - None
8. Motorola - None
9. Sony - Not Sure
10. ?

**Comment by TheMysticS** [comment]
https://github.com/d4rken/mystic-permissions/issues/1#issuecomment-1186184275

Actually, it won't be a bad idea to include labels for all apps, provided the label itself acts as a link to the app on the respective Store, with sideloaded apps being exceptions.

My initial suggestion to keep the label for only side-loaded apps was to keep the UI clean, avoiding unnecessary clutter. But having the label for all apps has it's own distinct advantages:

1. User can open the Store page directly (assuming the label acts as a link too).

2. User can see which app came from which Store. This is especially useful when one store updates apps installed using another Store. For example, some of the apps installed using Google Play Store can be updated using the Samsung Galaxy Store too. Many users (myself included) may not want to do that. So these labels can be useful in such cases.

Whenever we talk of a label, it is understood that there would be a corresponding filter too for that label. So that makes this 4 new labels:

1. Google Play Store
2. Samsung Galaxy Store
3. Huawei App Gallery (or Huawei App Market)
4. Sideloaded Apps

**Comment by TheMysticS** [comment]
With that many labels, may be it is time that you consider implementing icons. It will keep the UI clean. There will be a legend that users can use to understand what each icon represents.

**Comment by dragonGod97677** [comment]
> > Not a bad idea 🤔 So we'd need to collect a list of OEM store identifiers? Or we mark everything except Google Play as "sideloaded"?
> 
> We'll have to collect those identifiers, which I believe isn't too many (isn't it just one per brand?):
> 
> 1. Samsung: **com.sec.android.app.samsungapps**
> 2. Huawei: **com.huawei.appmarket**
> 3. Oppo: **com.huawei.appmarket** (most likely)
> 4. Vivo: **com.huawei.appmarket** (most likely)
> 5. OnePlus - None
> 6. Nothing - None
> 7. Nokia - None
> 8. Motorola - None
> 9. Sony - Not Sure
> 10. ?

This is the package name for oppo app store 
Oppo:``com.oppo.market``
Vivo: (I'll edit this later, when i get my hand on a vivo phone)

**Comment by TheMysticS** [comment]
> > We'll have to collect those identifiers, which I believe isn't too many (isn't it just one per brand?):
> > 
> > 1. Samsung: **com.sec.android.app.samsungapps**
> > 2. Huawei: **com.huawei.appmarket**
> > 3. Oppo: **com.huawei.appmarket** (most likely)
> > 4. Vivo: **com.huawei.appmarket** (most likely)
> > 5. OnePlus - None
> > 6. Nothing - None
> > 7. Nokia - None
> > 8. Motorola - None
> > 9. Sony - Not Sure
> > 10. ?
> 
> This is the package name for oppo and vivo app store Oppo:`com.oppo.market` Vivo: `com.vivo.market` More app store Xiaomi app store: `com.xiaomi.market`

Are these App Stores? I don't think so. Please confirm.

**Comment by dragonGod97677** [comment]
> Are these App Stores? I don't think so. Please confirm.
> 
> I think these stores are for buying accessories and other products.

The vivo app store, i can confirm it, but the Xiaomi app store, i only found it on the internet.

And Huawei doesn't have connections to vivo amd oppo. Same applies to vivo and oppo.

But oppo and realme, they have connections
Vivo, have connection to one brand but i forgot it

BBK, owns oppo and vivo

**Comment by TheMysticS** [comment]
> > Are these App Stores? I don't think so. Please confirm.
> > I think these stores are for buying accessories and other products.
> 
> The vivo app store, i can confirm it, but the Xiaomi app store, i only found it on the internet.
> 
> And Huawei doesn't have connections to vivo amd oppo. Same applies to vivo and oppo.
> 
> But oppo and realme, they have connections Vivo, have connection to one brand but i forgot it
> 
> BBK, owns oppo and vivo

There were reports that Huawei, Oppo, Vivo and Xiaomi were coming together to create an app market as an alternative to Google Play Store. I'm aware BBK owns Oppo, Vivo and OnePlus.

**Comment by dragonGod97677** [comment]
> There were reports that Huawei, Oppo, Vivo and Xiaomi were coming together to create an app market as an alternative to Google Play Store. I'm aware BBK owns Oppo, Vivo, OnePlus, Realme, etc.

Well if that's the case and still not happening now, we can just create a new issue.
Also in my theory, even they will come together, it is impossible that package name will be same on Huawei app store

**Comment by dragonGod97677** [comment]
Oh you were saying is a old news, it's from 2020, ive just searched about it, but nonetheless, my theory will stand

**Comment by TheMysticS** [comment]
> > There were reports that Huawei, Oppo, Vivo and Xiaomi were coming together to create an app market as an alternative to Google Play Store. I'm aware BBK owns Oppo, Vivo, OnePlus, Realme, etc.
> 
> Well if that's the case and still not happening now, we can just create a new issue. Also in my theory, even they will come together, it is impossible that package name will be same on Huawei app store to other brands

OnePlus and Xiaomi also have their Store apps, but these are for accessories and other products.

So please confirm for Oppo, Vivo and others. Since these brands are all from BBK, I wonder why they will use different Store names. As far as I know (I'm not certain though), all these brands use the Huawei App Gallery.

**Comment by dragonGod97677** [comment]
Vivo: 
![Screenshot_2022-07-17-11-12-24-02](https://user-images.githubusercontent.com/38875906/179382224-c0aa66da-ce72-4804-b49c-0b856cb67be0.png)


Oppo
![Screenshot_2022-07-17-11-12-10-32](https://user-images.githubusercontent.com/38875906/179382232-36df647b-001e-4a2c-9bb8-c2b0cb928e5f.png)

@TheMysticS

**Comment by dragonGod97677** [comment]
That two brand is i can only confirm right now

**Comment by dragonGod97677** [comment]
![Screenshot_2022-07-17-11-15-33-36](https://user-images.githubusercontent.com/38875906/179382291-edeccc5f-7dad-4252-bffd-075da8888380.png)
Xiaomi

**Comment by TheMysticS** [comment]
> ![Screenshot_2022-07-17-11-15-33-36](https://user-images.githubusercontent.com/38875906/179382291-edeccc5f-7dad-4252-bffd-075da8888380.png) Xiaomi

It is Xiaomi GetApps: 

com.xiaomi.mipicks

Thanks for these.

**Comment by d4rken** [comment]
https://github.com/d4rken-org/permission-pilot

**Comment by tathastu871** [comment]
when we do adb shell pm list it shows store name, google vendor or android vendor or blank for 3rd party
Also when adb shell install we can pass installer app name, even when we are sideloading apk if we pass pm install -i  "com.android.vending" apk. it will be flagged as if installed from play store and follow normal updates from store
