### ISSUE TITLE
Warning on accessibility service

### ISSUE THREAD

**Issue by atraxsrc** [d4rken-org/sdmaid#5621]
**Describe the bug**
Warning sign displayed when turning on accessibility service

**To Reproduce**
1. Go to SD Maid 'settings'
2. Toggle 'Accessibility service'
3. See warning

**Expected behavior**
warning should not appear

**Screenshots**
![Screenshot_20220717-205438_SD Maid.jpg](https://user-images.githubusercontent.com/92285717/179395093-e13ebc7b-8745-4efd-aadd-5b2b09ef1298.jpg)

**Smartphone (please complete the following information):**
 - Device: S21 Ultra
 - OS: Android 12

**Comment by d4rken** [comment]
The icon shows if the service has been enabled in SD Maid, but it is not running (as the service has not been enabled in the system or because the system didn't start it yet).

Do you think the icon is not displayed correctly?

**Comment by atraxsrc** [comment]
Iam having the same problem listed here:
 https://github.com/d4rken/sdmaid-public/issues/5211#issue-1065121039

Strange because was working fine till last week.

One other reason that I can think of is not working, could be after I use this tool: https://github.com/0x192/universal-android-debloater 
As some feature as disabled

**Comment by d4rken** [comment]
> Iam having the same problem listed here:
https://github.com/d4rken/sdmaid-public/issues/5211#issue-1065121039

This is not something I can fix on my side. It's a ROM issue.
Sometimes you need to reboot. The system may have blacklisted the service for some reason, reboots clear it.

> Strange because was working fine till last week.
> One other reason that I can think of is not working, could be after I use this tool: https://github.com/0x192/universal-android-debloater
> As some features are disabled

It's possible, even plausible if it was working until last work, but that's something you will have to ask the developer of the debloater tool. I have no experience with this.

**Comment by d4rken** [comment]
Also check the FAQ for this:
https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#troubleshooting
