### ISSUE TITLE
Failed Task in System Cleaner

### ISSUE THREAD

**Issue by darlianto** [d4rken-org/sdmaid#5627]
1  task failed in System Cleaner

Device:
Redmi Note 10 Pro
Android 12 (MIUI 13)
Rooted

[Screenshot_2022-07-22-23-09-40-124_eu thedarken sdm](https://user-images.githubusercontent.com/33614922/180481535-476d97b7-220d-4533-895c-27c828757113.jpg)
[Screenshot_2022-07-22-23-09-44-138_eu thedarken sdm](https://user-images.githubusercontent.com/33614922/180481549-9e03cc45-9293-4a6f-9e8f-d09de7e5cc44.jpg)
![Screenshot_2022-07-22-23-12-32-078_eu thedarken sdm](https://user-images.githubusercontent.com/33614922/180481551-ac308e19-6ce1-4d44-9936-434d83199466.jpg)

**Comment by dragonGod97677** [comment]
Is your phone rooted and sd maid have root? If so it should be deleted already, send a debug log for darken to check why it failed

**Comment by d4rken** [comment]
This is probably either a file that has been deleted while SD Maid was scanning, or a file that is still in-use by a process and can't be deleted. There is not much SD Maid can do either way and if this is the case, then it looks like it is working as intended. :shrug:
