### ISSUE TITLE
Bug: Accessibility issue

### ISSUE THREAD

**Issue by rravibansal** [d4rken-org/sdmaid#5635]
### What happened?
Accessibility prompt even after being enabled

### What did you expect to happen?
App cleaner to run properly.....

### How can I reproduce the issue?
Run app cleaner to clean applications data

### Comments
Same Issue with previous versions also
### SD Maid
Version: `5.4.0 (50400)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `xiaomi/violet/violet:10/QKQ1.190915.002/V12.5.1.0.QFHINXM:user/release-keys`

**Comment by d4rken** [comment]
No logs, no fix :shrug: 

https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log
