### ISSUE TITLE
Bug: App cleaner not working in MIUI 11

### ISSUE THREAD

**Issue by NoiseBox20** [d4rken-org/sdmaid#5637]
### What happened?
App cleaner not clearing app cache.

### What did you expect to happen?
App cleaner clear app cache when I click the button, sd maid clean things for me. 

### How can I reproduce the issue?
1. Click find in app cleaner 2. After finished finding, click clean now.

### Comments
I've already turned on accesibility setting for sd maid, but its not helping and there's no draw over app prompt.
### SD Maid
Version: `5.3.23 (50323)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `xiaomi/mido/mido:7.0/NRD90M/V11.0.2.0.NCFMIXM:user/release-keys`

![Screenshot_2022-07-30-18-56-22-532_eu thedarken sdm](https://user-images.githubusercontent.com/65381461/181911794-f0809a31-c75d-43ec-9c23-f6b8b0a503c6.jpg)
![Screenshot_2022-07-30-13-14-15-048_com miui securitycenter](https://user-images.githubusercontent.com/65381461/181911828-ca150d65-25eb-49dc-aaf3-b98a6bf70c99.jpg)
![Screenshot_2022-07-30-13-14-03-988_com miui securitycenter](https://user-images.githubusercontent.com/65381461/181911838-1c301a6c-6047-464f-bf11-959143c78a55.jpg)

**Comment by dragonGod97677** [comment]
Please send a log file, [Here is the instructions ](https://github.com/d4rken-org/sdmaid/wiki/Reporting-a-bug)

**Comment by NoiseBox20** [comment]
[sdmaid_logfile_1659196113856.txt.zip](https://github.com/d4rken-org/sdmaid/files/9226834/sdmaid_logfile_1659196113856.txt.zip)

**Comment by NoiseBox20** [comment]
> It looks like you have the "Custom Sequence" enabled.
> 
> Disable it and try again.
> 
> ```java
> Failed Spec(parent=AppCleaner:ACS:CustomSpecs, label=Find & click 'Penyimpanan', pkg=com.google.android.youtube), retrying: java.util.concurrent.TimeoutException: The source did not signal an event for 4000 milliseconds and has been terminated.
> ```

Ok ,and now it's working. thank you.
