### ISSUE TITLE
Clutterreport: /system/app/WebViewStub/WebViewStub.apk (FP)

### ISSUE THREAD

**Issue by abdihakim392** [d4rken-org/sdmaid#5639]
### Target
Target: `/system/app/WebViewStub/WebViewStub.apk`
Prefix-free: `WebViewStub/WebViewStub.apk`
Path-prefix: `/system/app/`
Type: `FILE`
Location: `SYSTEM_APP`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Chrome`
Packagename: `com.android.chrome`
Version: `103.0.5060.71 (506007120)`

Appname: `Google Play services`
Packagename: `com.google.android.gms`
Version: `22.26.15 (110304-461192076) (222615059)`

Appname: `ADM`
Packagename: `com.dv.adm`
Version: `14.0.13 (140013)`

Appname: `Samsung Internet`
Packagename: `com.sec.android.app.sbrowser`
Version: `17.0.7.34 (1170734500)`

### Current owners
Appname: `Android System WebView`
Packagename: `com.google.android.webview`
Version: `70.0.3538.110 (353811000)`

### SD Maid
Version: `5.3.18 (50318)`

### Device
Fingerprint: `samsung/a2coreltejx/a2corelte:8.1.0/OPR6/A260FXXS8ATJ1:user/release-keys`

**Comment by dragonGod97677** [comment]
Closing this issue because: Invalid owner suggestions
