### ISSUE TITLE
I need help 

### ISSUE THREAD

**Issue by Payelpp** [d4rken-org/sdmaid#5641]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Debug log**
Record a [debug log](https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log) while reproducing the problem and attach the zip file here.

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android 10]

**Additional context**

**Comment by dragonGod97677** [comment]
Please submit a proper bug report, if this issue wasn't get edited within 24 hours of posting, this issue will get closed.

**Comment by dragonGod97677** [comment]
Closing this now since it has not been edited
