### ISSUE TITLE
Clutterreport: /storage/emulated/0/.FilesByGoogleTrash (new)

### ISSUE THREAD

**Issue by abdihakim392** [d4rken-org/sdmaid#5643]
### Target
Target: `/storage/emulated/0/.FilesByGoogleTrash`
Prefix-free: `.FilesByGoogleTrash`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `System UI`
Packagename: `com.android.systemui`
Version: `8.1.0 (27)`

Appname: `Google Play services`
Packagename: `com.google.android.gms`
Version: `22.26.15 (110304-461192076) (222615059)`

Appname: `Chrome`
Packagename: `com.android.chrome`
Version: `103.0.5060.71 (506007120)`

Appname: `Galaxy Apps`
Packagename: `com.sec.android.app.samsungapps`
Version: `5.1.01.12 (510112330)`

### Current owners
None

### SD Maid
Version: `5.3.18 (50318)`

### Device
Fingerprint: `samsung/a2coreltejx/a2corelte:8.1.0/OPR6/A260FXXS8ATJ1:user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid suggested owners, i know the owner of that folder and it's [Files by Google](https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.files) with package name `com.google.android.apps.nbu.files`
