### ISSUE TITLE
Bug: Scheduler does not work on Samsung Galaxy S22+

### ISSUE THREAD

**Issue by BOSBrownie** [d4rken-org/sdmaid#5644]
### What happened?
The scheduler should start up at a set time but doesn't

### What did you expect to happen?
It starts up at my set time and deletes all cache

### How can I reproduce the issue?
Set SD Maid service at a time and it should start time

### Comments
I changed phones a month ago and the scheduler was working on my old phone but now it is not working on my Samsung Galaxy S22+
### SD Maid
Version: `5.4.0 (50400)`
Pro: `isPro=true || isComplete=true (unl=true, iap=true, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/g0qsqw/g0q:12/SP1A.210812.016/S906USQU2AVF7:user/release-keys`

**Comment by dragonGod97677** [comment]
Send a debug log. [Instructions for getting a Debug Log](https://github.com/d4rken-org/sdmaid/wiki/Reporting-a-bug#debug-log).

**Comment by dragonGod97677** [comment]
Also one more thing, is Samsung have that auto kill feature? If so, Can you try excluding sd maid on it and try again?
