### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.dts.freefireth (FP)

### ISSUE THREAD

**Issue by Rioverto** [d4rken-org/sdmaid#5645]
### Target
Target: `/storage/emulated/0/Android/data/com.dts.freefireth`
Prefix-free: `com.dts.freefireth`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `TeraBox`
Packagename: `com.dubox.drive`
Version: `2.22.1 (190)`

### Current owners
~~Appname: `?`~~
~~Packagename: `com.dts.freefireth`~~
~~Version: ` (-1)`~~

### SD Maid
Version: `5.3.23 (50323)`

### Device
Fingerprint: `Lenovo/A6020l36/A6020l36:6.0.1/MMB29M/A6020l36_S155_170212_LAS:user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid owner replacement
