### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.zhiliaoapp.musically (FP)

### ISSUE THREAD

**Issue by Rioverto** [d4rken-org/sdmaid#5646]
### Target
Target: `/storage/emulated/0/Android/data/com.zhiliaoapp.musically`
Prefix-free: `com.zhiliaoapp.musically`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `wt_secret_code_manager`
Packagename: `com.wt.secret_code_manager`
Version: `6.0.1 (23)`

### Current owners
Appname: `TikTok`
Packagename: `com.zhiliaoapp.musically`
Version: `25.5.4 (2022505040)`

### SD Maid
Version: `5.3.23 (50323)`

### Device
Fingerprint: `Lenovo/A6020l36/A6020l36:6.0.1/MMB29M/A6020l36_S155_170212_LAS:user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid new suggested owner, that app has nothing to do with TikTok

**Comment by Rioverto** [comment]
Em sex, 5 de ago de 2022 10:17, dragonGod97677 ***@***.***>
escreveu:

**Comment by Rioverto** [comment]
Em sex, 5 de ago de 2022 10:17, dragonGod97677 ***@***.***>
escreveu:

**Comment by Rioverto** [comment]
Em sáb, 6 de ago de 2022 11:20, Hobby Bittencourt Martins <
***@***.***> escreveu:

**Comment by Rioverto** [comment]
Em sáb, 6 de ago de 2022 11:20, Hobby Bittencourt Martins <
***@***.***> escreveu:

**Comment by Rioverto** [comment]
Em sáb, 6 de ago de 2022 11:21, Hobby Bittencourt Martins <
***@***.***> escreveu:

**Comment by Rioverto** [comment]
Em sáb, 6 de ago de 2022 11:21, Hobby Bittencourt Martins <
***@***.***> escreveu:

**Comment by Rioverto** [comment]
Em sáb, 6 de ago de 2022 11:21, Hobby Bittencourt Martins <
***@***.***> escreveu:

**Comment by Rioverto** [comment]
Em sáb, 6 de ago de 2022 11:21, Hobby Bittencourt Martins <
***@***.***> escreveu:
