### ISSUE TITLE
Formatar a memória interna e externa com backup ultra seguro

### ISSUE THREAD

**Issue by Rioverto** [d4rken-org/sdmaid#5647]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dragonGod97677** [comment]
Uh.. no, i don't think so

**Comment by dragonGod97677** [comment]
Also please don't open and close and open back an issue, i kept receiving an email that specific issue is being opened, closed and open back

**Comment by Rioverto** [comment]
Em sex, 5 de ago de 2022 10:20, dragonGod97677 ***@***.***>
escreveu:
