### ISSUE TITLE
Disable animations

### ISSUE THREAD

**Issue by gallegonovato** [d4rken-org/sdmaid#5648]
Good afternoon:

I downloaded Sd Maid SD_Maid-v5.4.1(50401)-RELEASE-40779c3fa.apk from https://sdmaid.darken.eu/download/beta/ 

And in application control moves the signs of no internet, and others.

And I wanted to know if there is a possibility that there is no such animations.

Also ask one more thing, if I may. It turns out that years ago I bought sd maid pro in the Google store. But now I use my phone with Lineageos and without anything from google. It could be done or get the version of that purchase. Without having to install anything from google?

A hug and thanks for your time and help.

**Comment by dragonGod97677** [comment]
> Good afternoon:
> 
> I downloaded Sd Maid SD_Maid-v5.4.1(50401)-RELEASE-40779c3fa.apk from https://sdmaid.darken.eu/download/beta/
> 
> And in application control moves the signs of no internet, and others.
> 
> And I wanted to know if there is a possibility that there is no such animations.

What do you mean no animations?

> Also ask one more thing, if I may. It turns out that years ago I bought sd maid pro in the Google store. But now I use my phone with Lineageos and without anything from google. It could be done or get the version of that purchase. Without having to install anything from google?

I think you need to buy pro again via https://apps.darken.eu/

![Screenshot_2022-08-06-01-10-04-29](https://user-images.githubusercontent.com/38875906/183127645-69e16572-9522-4315-81da-e618c0cccfe3.png)

**Comment by gallegonovato** [comment]
Good afternoon:

First of all thank you for your reply and help.

As for the animations that I get I upload a screenshot. Let's see if you can see how it is changing:

https://ibb.co/JKcgyy0
https://ibb.co/CHGy0Sv
https://ibb.co/Tgt9WC0
https://ibb.co/GJzH0z7
https://ibb.co/g4fFN0K
https://ibb.co/09hYq1V
https://ibb.co/K5T2DR3

And about the pro. Thanks for the clarification.

A hug

**Comment by dragonGod97677** [comment]
> Good afternoon:
> 
> First of all thank you for your reply and help.
> 
> As for the animations that I get I upload a screenshot. Let's see if you can see how it is changing:
> 
> (Links...)

Ah those, you have to wait for @d4rken , he is the developer of sd maid, he will answer your question.

> And about the pro. Thanks for the clarification.
> 
> A hug

Your welcome!

**Comment by d4rken** [comment]
If we disable the marquee, then the text will be cut off and not readable? 🤔

**Comment by gallegonovato** [comment]
Good afternoon @d4rken

First of all thank you very much for all your work and effort.

In previous versions did not move and read the text.

I take this opportunity to suggest a color change. Since it is now stopped in orange. And would not it be better in red. To know this way better and draw more attention to the view.

A hug
