### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/Nubank(com.nu.production)-7.81.8-minApi26(1000035480)-base.apk (FP)

### ISSUE THREAD

**Issue by ivanuzia** [d4rken-org/sdmaid#5649]
### Target
Target: `/storage/emulated/0/Download/Nubank(com.nu.production)-7.81.8-minApi26(1000035480)-base.apk`
Prefix-free: `Download/Nubank(com.nu.production)-7.81.8-minApi26(1000035480)-base.apk`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Current owners
Appname: `Sistema Android`
Packagename: `android`
Version: `9 (28)`

~~Appname: `Downloads`~~
~~Packagename: `com.android.providers.downloads.ui`~~
~~Version: `9 (28)`~~

Appname: `Gerenciador de downloads`
Packagename: `com.android.providers.downloads`
Version: `9 (28)`

### SD Maid
Version: `5.3.23 (50323)`

### Device
Fingerprint: `samsung/z3qksx/z3qksx:9/PPR1.180720.122/6736742:user/release-keys`

**Comment by ivanuzia** [comment]
gg

**Comment by dragonGod97677** [comment]
Invalid owner remove suggestion
