### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/youtube (FP)

### ISSUE THREAD

**Issue by luutrutatcavaomaytinh** [d4rken-org/sdmaid#5650]
### Target
Target: `/storage/emulated/0/Download/youtube`
Prefix-free: `Download/youtube`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Cửa hàng Google Play`
Packagename: `com.android.vending`
Version: `31.6.13-21 [0] [PR] 462679837 (83161310)`

Appname: `Cài đặt`
Packagename: `com.android.settings`
Version: `11 (30)`

Appname: `CaptivePortalLogin`
Packagename: `com.android.captiveportallogin`
Version: `2019-09 (300000000)`

### Current owners
Appname: `Tệp đã tải xuống`
Packagename: `com.android.providers.downloads.ui`
Version: `11 (30)`

Appname: `Trình quản lý Tải xuống`
Packagename: `com.android.providers.downloads`
Version: `11 (30)`

~~Appname: `Hệ thống Android`~~
~~Packagename: `android`~~
~~Version: `11 (30)`~~

### SD Maid
Version: `5.3.23 (50323)`

### Device
Fingerprint: `realme/RMX3231/RMX3231:11/RP1A.201005.001/1657700640059:user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid suggested owners and remove current ones
