### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.whatsapp/cache (FP)

### ISSUE THREAD

**Issue by Eyesopen4** [d4rken-org/sdmaid#5652]
### Target
Target: `/storage/emulated/0/Android/data/com.whatsapp/cache`
Prefix-free: `com.whatsapp/cache`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
~~Appname: `WhatsApp`~~
~~Packagename: `com.whatsapp`~~
~~Version: `2.22.16.75 (221675004)`~~

### SD Maid
Version: `5.3.23 (50323)`

### Device
Fingerprint: `OPPO/CPH2067/OP4C72L1:11/RKQ1.200903.002/1657009795724:user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid
