### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.viber.voip/files/User photos/.thumbnails (FP)

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#5653]
### Target
Target: `/storage/emulated/0/Android/data/com.viber.voip/files/User photos/.thumbnails`
Prefix-free: `com.viber.voip/files/User photos/.thumbnails`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
Appname: `Viber`
Packagename: `com.viber.voip`
Version: `16.4.7.6 (650814)`

### SD Maid
Version: `5.3.19 (50319)`

### Device
Fingerprint: `Redmi/dandelion_ru/dandelion:10/QP1A.190711.020/V12.0.14.0.QCDRUXM:user/release-keys`

### Comment
`Кэш                 `

**Comment by dragonGod97677** [comment]
Hey @d4rken is this directory already marked on system cleaner?

**Comment by d4rken** [comment]
I'm not sure. Because we know the owner app, app cleaner should be responsible for it.
I think it already checks this but only one nestings level, e.g. files/.thumbnails, I will check the code

**Comment by d4rken** [comment]
https://github.com/d4rken-org/sdmaid-se/pull/203
