### ISSUE TITLE
Clutterreport: /storage/3134-3732/музыка (new)

### ISSUE THREAD

**Issue by AmidbelkA** [d4rken-org/sdmaid#5655]
@### Target
Target: `/storage/3134-3732/музыка`
Prefix-free: `музыка`
Path-prefix: `/storage/3134-3732/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Google Play Фильмы`
Packagename: `com.google.android.videos`
Version: `4.15.10 (41500101)`

### Current owners
None

### SD Maid
Version: `5.3.23 (50323)`

### Device
Fingerprint: `lge/lucye_global_com/lucye:9/PKQ1.190522.001/19347004823f8:user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid suggested owner
