### ISSUE TITLE
[BUG] Not able to access SD card from "choose folders for checking duplicates" menu in settings

### ISSUE THREAD

**Issue by rsmyst** [d4rken-org/sdmaid#5661]
**Describe the bug**
The SD card button literally does nothing. I searched for another thread here and apparently it was marked completed in version 5.3.0. i'm on version 5.3.24. The sd card button simply does nothing. Only main phone directory (/0) is accessible.

**To Reproduce**
1. Go to settings
2. Click duplicates
3. go into folder choosing menu

Expected to pop into sd card directory but nothing happens.
FYI, the SD card itself does seem to be able to be checked with other means ( like using sd maid explore). It's just that it isn't accessible from inside duplicates menu.

**Smartphone (please complete the following information):**
 - Device: Samsung S9+
 - OS: Android 10

**Additional context**
I also tried changing SD maid working directory to sd card, but didn't help. 
i made sure to check if sd maid had permissions for sd card as well ( it did ).

**Comment by d4rken** [comment]
If you use it without default settings, does SD Maid list the sdcard in the options and check it?

**Comment by rsmyst** [comment]
> If you use it without default settings, does SD Maid list the sdcard in the options and check it?

Could you please clarify what you mean by using it without default settings? I've currently set it to check for duplicates only on certain folders where i know duplicates will pop up at some point

**Comment by d4rken** [comment]
I mean with defaults. The defaults should include all accessible public storage.
Not being able to select the SD card may just be a bug of the path picker UI.

**Comment by paulwacko** [comment]
Had this problem for quite a while.
Duplicate settings won't recognise SD card.

**Comment by paulwacko** [comment]
In default it doesn't check SD

**Comment by rsmyst** [comment]
> I mean with defaults. The defaults should include all accessible public storage. Not being able to select the SD card may just be a bug of the path picker UI.

I think i understand what you mean and yes, the SD card is accessible across the rest of the app but inactive in duplicate settings. possible a UI error like you have mentioned. the SD card button in ui settings shows the tap animation when clicking it as well but doesn't lead anywhere. maybe button is improperly linked?

**Comment by d4rken** [comment]
Link also #5343

With a fresh SD Maid install, default settings, on a Samsung Galaxy S20 FE 5G running Android 12, the sdcard and primary storage is checked, and duplicates across both storage are detected.

[Screenshot from 2022-09-13 10-40-04](https://user-images.githubusercontent.com/1439229/189854450-77208ed7-567f-47d1-bb66-9a731a11c774.png)
[Screenshot from 2022-09-13 10-37-40](https://user-images.githubusercontent.com/1439229/189854456-050f779d-f69d-4aa7-8d1b-9faeb172c6d8.png)

I can reproduce though that you can't navigate to secondary storage in the file picker. As a workaround you should be able to press the "reset" button in the duplicates settings, which should setup both primary and secondary public storage as search locations again.

I'll fix the file picker though.

**Comment by d4rken** [comment]
I've changed both primary and secondary toolbar buttons to use SD Maids storage manger instead of the system to resolve the paths, should work now and be more robust.
