### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.zaza.beatbox (FP)

### ISSUE THREAD

**Issue by Bellybill** [d4rken-org/sdmaid#5664]
### Target
Target: `/storage/emulated/0/Android/data/com.zaza.beatbox`
Prefix-free: `com.zaza.beatbox`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Unknown`
Packagename: `com.google.android.trichromelibrary_500509930`
Version: ` (500509930)`

### Current owners
~~Appname: `VoxBox Audio Editor`~~
~~Packagename: `com.zaza.beatbox`~~
~~Version: `5.7.4 (255)`~~

### SD Maid
Version: `5.3.23 (50323)`

### Device
Fingerprint: `T-Mobile/5007W/Tokyo_Lite_4G:10/QP1A.190711.020/v7HDM-0:user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid suggestion
