### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.android.providers.media/thumbnail_cache/thumbnail.db (FP)

### ISSUE THREAD

**Issue by hernanalv89** [d4rken-org/sdmaid#5668]
### Target
Target: `/storage/emulated/0/Android/data/com.android.providers.media/thumbnail_cache/thumbnail.db`
Prefix-free: `com.android.providers.media/thumbnail_cache/thumbnail.db`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `FILE`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
~~Appname: `Almacenamiento multimedia`~~
~~Packagename: `com.android.providers.media`~~
~~Version: `8.0.0 (904)`~~

### SD Maid
Version: `5.3.23 (50323)`

### Device
Fingerprint: `HUAWEI/ATU-LX3/HWATU-QG:8.0.0/HUAWEIATU-LX3/152(C69):user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid
