### ISSUE TITLE
Clutterreport: /storage/emulated/0/DCIM (FP)

### ISSUE THREAD

**Issue by Rterty33** [d4rken-org/sdmaid#5669]
### Target
Target: `/storage/emulated/0/DCIM`
Prefix-free: `DCIM`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Current owners
~~Appname: `Android System`~~
~~Packagename: `android`~~
~~Version: `11 (30)`~~

Appname: `?`
Packagename: `com.meizu.media.gallery`
Version: ` (-1)`

### SD Maid
Version: `5.3.23 (50323)`

### Device
Fingerprint: `motorola/ellis_ga/ellis:11/RRHG31.Q3-37-43/d56d5:user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid
