### ISSUE TITLE
Clutterreport: /storage/emulated/0/Music (FP)

### ISSUE THREAD

**Issue by Rterty33** [d4rken-org/sdmaid#5670]
### Target
Target: `/storage/emulated/0/Music`
Prefix-free: `Music`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Android Shared Library`
Packagename: `com.google.android.ext.shared`
Version: `1 (1)`

### Current owners
Appname: `Android System`
Packagename: `android`
Version: `11 (30)`

Appname: `?`
Packagename: `com.lge.musicpicker`
Version: ` (-1)`

### SD Maid
Version: `5.3.23 (50323)`

### Device
Fingerprint: `motorola/ellis_ga/ellis:11/RRHG31.Q3-37-43/d56d5:user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid suggested new owner
