### ISSUE TITLE
'/storage/emulated/0/Android/data' Permission denied

### ISSUE THREAD

**Issue by crewords** [d4rken-org/sdmaid#5671]
**Describe the bug**
I cannot access to '/storage/emulated/0/Android/data'.

**To Reproduce**
Setup → Public storage → /storage/emulated/0/Android/data(red color) → Google Files Shows That Location Cannot Be Selected. The message 'Choose a different folder for privacy' is displayed.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi9
 - OS: Android 13(EvoX 7.0)

**Comment by d4rken** [comment]
I currently don't know a good workaround :slightly_frowning_face:

**Comment by VexfulNiko** [comment]
What about ADB permissions? Sd Maid needs a ADB mode since ADB is practically a power tool with a ton of options.

**Comment by VexfulNiko** [comment]
Also see: https://twitter.com/MishaalRahman/status/1560433781051428872

**Comment by VexfulNiko** [comment]
https://www.reddit.com/r/Android/comments/wsnhct/_/

**Comment by ymoran00** [comment]
Same here with Pixel 6a. SD maid can't do its cleaning no mo'.

**Comment by lasha117** [comment]
is there any adb command that can fix this issue?

**Comment by VexfulNiko** [comment]
Bump

**Comment by baraa272** [comment]
Bumping this issue since we might need shizuku for this

**Comment by VexfulNiko** [comment]
Bump

**Comment by lawson85** [comment]
ADB trim-caches command?

**Comment by VexfulNiko** [comment]
Bump
Cc @d4rken

**Comment by d4rken** [comment]
Still no known workaround. The only think I know that works is granting access to subfolders directly.
e.g. `/storage/emulated/0/Android/data/<some.app.pk>`
but to make SD Maid operational for 100 apps, the user would have to manually grant access a 100 times.
I don't know an ADB command to grant SAF access that the user could copy/paste and automating this would likely get us into trouble with Google. :frowning:

**Comment by d4rken** [comment]
There are no ADB commands for this, afaik.

Google would dislike automating the permission screen for 100 apps via accessibility service.

**Comment by VexfulNiko** [comment]
@d4rken I mean Tasker does this and more and it's on the Google Play pass so google fine with it as well as ADB has a bunch of one off commands to grant permissions (a lot more were added in recent android versions too) to simplify this process for power users.

**Comment by d4rken** [comment]
Tasker is granting itself permission using an accessibility service? I highly doubt that.

**Comment by d4rken** [comment]
@VexfulNiko you are not understanding the issue and keep repeating the same thing. Please stop conflating different topics and confusing everyone in this thread.

* If there are ADB commands to grant access to "Storage Access Framework" scopes, then yes I could post instructions for users to do that, but this doesn't exist to my knowledge ❌.
* The only work around that I know is that if SD Maid opens a sub folder of `Android/data/`, i.e. `Android/data/<pkg>`, then the user can grant access to that and then SD Maid can access the sub folder ✅ .
    * If you have 100 apps, this needs to be done 100 times. Which is infeasible ❌ .
    * Theoretically granting access 100 times, clicking 100x "Grant access" could be automated using an accessibility service. But it's a super shitty shitty solution 🤢  . 
    * Using an accessibility service to grant yourself permission is what malware does. It will get SD Maid banned as it's total abuse of the accessibility mechanism ❌ .
    * The whole use of accessibility services by SD Maid or Tasker is already borderline and might be against Google Play TOS at some point. Doing something stupid like using ACS to grant yourself permissions could even fast track that.
    * I don't even know if an accessibility service can touch permission request dialogs, as they have extra security properties.
* Tasker does not use an accessibility service to click "grant" on permission dialogs to grant itself permissions in Androids security model.

**Comment by JasonHK** [comment]
I think [RikkaApps/Shizuku](https://github.com/RikkaApps/Shizuku) could be a viable alternative method

**Comment by baraa272** [comment]
Shizuku is good in this case scenario
