### ISSUE TITLE
[Bug] SD Maid is eating up my battery in the background

### ISSUE THREAD

**Issue by erfirya** [d4rken-org/sdmaid#5672]
[Screenshot_2022-08-22-21-40-59-409_com miui securitycenter](https://user-images.githubusercontent.com/71990871/185937301-0aaf0397-bfcd-41d4-99b8-0b84ba86c195.jpg)
[Screenshot_2022-08-22-21-41-35-612_com miui securitycenter](https://user-images.githubusercontent.com/71990871/185937335-27146e42-c122-4357-bd2f-590e20d61c8f.jpg)
[Screenshot_2022-08-22-21-41-43-806_com miui securitycenter](https://user-images.githubusercontent.com/71990871/185937344-0300513f-4e1a-4153-af96-ccfe5b179cef.jpg)
It only started after I granted SD Maid root access
Install ID : b30ab489-84e1-4230-abd6-5c1311fd17c7

**Comment by d4rken** [comment]
Force stop SD Maid, and then check if this happens repeatedly. If force stopping doesn't help, reboot.

If it is reproducible, note what operations cause this.

If root is buggy or SD Maid was interrupted (or crashed) during root operations, a root process could keep running, though I'm not sure if battery management could even attribute that to an app.

**Comment by erfirya** [comment]
Xiaomi POCO X3 NFC
MIUI v13.0.1 by xiaomi.eu Android 12
Magisk v25.2
SD Maid v5.4.1
SD Maid Pro v4.4.1

**Comment by erfirya** [comment]
I don't think I can reproduce it. I don't even open the app and run it. Root is not buggy and I always finish SD Maid's operation before I close it.

**Comment by erfirya** [comment]
Anyway, where can I send the debug log? Its size is huge even after compression (47MB).

**Comment by d4rken** [comment]
A debug log does not help me currently, I wouldn't know what to look for.

You could look through it yourself if you suspect something.

**Comment by erfirya** [comment]
I wouldn't find anything there that I would understand lol. One thing I noticed after granting root is the accessibility service in app cleaner, It doesn't display the manually clearing of the cache in apps. What does it need root for? Do you suggest I just revoke its super user access?

**Comment by erfirya** [comment]
So I forced stop the app and cleared its data. Its not using that much power now. I think it's because of the autostart permission, which I turned off, that's causing sd maid to run and consume that much battery power. Thank you for your reply. Keep up the good work.

**Comment by d4rken** [comment]
> I think it's because of the autostart permission,

This is the wrong conclusion, it was likely the force-stop that fixed what ever dangling process was still running, but I'm happy to hear you solved it.
 
The ON_BOOT permission by itself does nothing but give SD Maid a chance to execute something for at most a few seconds on boot. SD Maid needs this to restore the scheduler if it was activated, if  it wasn't then SD Maid disables the ON_BOOT receiver itself.

**Comment by AlleVVatoR** [comment]
You are Best!!!
