### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download (FP)

### ISSUE THREAD

**Issue by Sctressa2412** [d4rken-org/sdmaid#5676]
### Target
Target: `/storage/emulated/0/Download`
Prefix-free: `Download`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `ATT Security Services`
Packagename: `com.att.csoiam.mobilekey`
Version: `1.0.9 (9)`

Appname: `Activation`
Packagename: `com.motorola.comcastext`
Version: `12 (31)`

Appname: `Android Services Library`
Packagename: `com.google.android.ext.services`
Version: `t_frc_ext_330443000 (330443000)`

Appname: `Android Development Info`
Packagename: `com.arumcomm.androiddevinfo`
Version: `1.3.4 (20220713)`

Appname: `ATT Phone Extension`
Packagename: `com.motorola.att.phone.extensions`
Version: `12 (31)`

Appname: `Android Setup`
Packagename: `com.google.android.setupwizard`
Version: `232.429004660 (15967)`

Appname: `Android System`
Packagename: `android`
Version: `12 (31)`

Appname: `Android System Intelligence`
Packagename: `com.google.android.as`
Version: `S.27.playstore.oem.466685969 (7128007)`

Appname: `AndroidExample`
Packagename: `com.tutorials.learn.androidexample`
Version: `1.1 (4)`

Appname: `Android Auto`
Packagename: `com.google.android.projection.gearhead`
Version: `7.8.622514-release (78622514)`

Appname: `Android System WebView`
Packagename: `com.google.android.webview`
Version: `103.0.5060.129 (506012933)`

Appname: `ArchivoSemiBold`
Packagename: `com.android.theme.font.ArchivoSemiBold`
Version: `1.0 (1)`

Appname: `AutoJsPro`
Packagename: `org.autojs.autojspro`
Version: `Pro 9.1.20-0 GP (9012000)`

Appname: `Basic Daydreams`
Packagename: `com.android.dreams.basic`
Version: `12 (31)`

Appname: `Bluetooth MIDI Service`
Packagename: `com.android.bluetoothmidiservice`
Version: `12 (31)`

Appname: `CACertApp`
Packagename: `vendor.qti.hardware.cacert.server`
Version: `1.0 (1)`

Appname: `Call Log Backup/Restore`
Packagename: `com.android.calllogbackup`
Version: `12 (31)`

Appname: `Call Protect`
Packagename: `com.att.callprotect`
Version: `3.30.0-2447 (330000)`

Appname: `Carrier Hub`
Packagename: `com.sprint.ms.smf.services`
Version: `5.14.0 (51400)`

Appname: `Carrier Device Manager`
Packagename: `com.sprint.ms.cdm`
Version: `1.8.2 (1802)`

Appname: `Carrier Provisioning Service`
Packagename: `com.motorola.omadm.service`
Version: `1.0.0 (1)`

Appname: `CaptivePortalLogin`
Packagename: `com.google.android.captiveportallogin`
Version: `t_frc_net_330443000 (330443000)`

Appname: `Carrier Services`
Packagename: `com.motorola.carrierconfig`
Version: `1.0 (1)`

Appname: `Carrier Settings`
Packagename: `com.google.android.carrier`
Version: `30.1.429180656 (30)`

Appname: `Carrier Setup`
Packagename: `com.google.android.wfcactivation`
Version: `103.1.415403814 (103)`

Appname: `CarrierDefaultApp`
Packagename: `com.android.carrierdefaultapp`
Version: `12 (31)`

Appname: `Cell Broadcast Service`
Packagename: `com.google.android.cellbroadcastservice`
Version: `R-initial (300000000)`

Appname: `ConfigUpdater`
Packagename: `com.google.android.configupdater`
Version: `12-8072170 (31)`

Appname: `Certificate Installer`
Packagename: `com.android.certinstaller`
Version: `12 (31)`

### Current owners
~~Appname: `Android System`~~
~~Packagename: `android`~~
~~Version: `12 (31)`~~

~~Appname: `Downloads`~~
~~Packagename: `com.android.providers.downloads.ui`~~
~~Version: `12 (31)`~~

~~Appname: `Download Manager`~~
~~Packagename: `com.android.providers.downloads`~~
~~Version: `12 (31)`~~

### SD Maid
Version: `5.3.23 (50323)`

### Device
Fingerprint: `motorola/denver_global/denver:12/S2RES32.29-16-1-2/b50654-d6017a:user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid
