### ISSUE TITLE
Clutterreport: /storage/E427-86D0/Android/data/com.camera.one.s10.camera (FP)

### ISSUE THREAD

**Issue by agoesirman** [d4rken-org/sdmaid#5681]
## Target
Target: `/storage/E427-86D0/Android/data/com.camera.one.s10.camera`
Prefix-free: `com.camera.one.s10.camera`
Path-prefix: `/storage/E427-86D0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
~~Appname: `?`~~
~~Packagename: `com.camera.one.s10.camera`~~
~~Version: ` (-1)`~~

### SD Maid
Version: `5.3.19 (50319)`

### Device
Fingerprint: `samsung/o5proltedd/o5prolte:6.0.1/MMB29K/G550FYXXU1BQK2:user/release-keys`

### Comment
`i can not delete`

**Comment by dragonGod97677** [comment]
Invalid suggestion of removing the owner of that folder and you can't delete that folder?
