### ISSUE TITLE
Bug: Internal storage button can't find by sd maid

### ISSUE THREAD

**Issue by Adnan78678600** [d4rken-org/sdmaid#5683]
### What happened?
After updating to 5.4.2 said maid is having problem to press internal storage while clearing cache.

### What did you expect to happen?
Sd maid trying >5 times to find internal storage button then after that clear cache.

### How can I reproduce the issue?
Revert back storage word to Internal storage to fix this issue.

### Comments
After updating to 5.4.2 said maid is having problem to press internal storage while clearing cache.To fix this issue please change the word storage to Internal storage and it will get fixed.
### SD Maid
Version: `5.4.2 (50402)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `vivo/1951/1951:10/QP1A.190711.020/compiler03191625:user/release-keys`

**Comment by d4rken** [comment]
Please provide a debug log of this:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log

The main thing has changed between 5.4.1 and 5.4.2 is the window check and the maximum nesting level when looking for elements. Both have just increased though, so it should not have broken any previously working actions.

Were you on v5.4.1 before?

**Comment by Adnan78678600** [comment]
Yes
