### ISSUE TITLE
Unlocker is targeting a super old Android version

### ISSUE THREAD

**Issue by pwd-github** [d4rken-org/sdmaid#5684]
**Describe the bug**
Update the unlocker to target a more modern version of Android

**To Reproduce**

**Expected behavior**

**Screenshots**

**Debug log**
Record a [debug log](https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log) while reproducing the problem and attach the zip file here.

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: Android 13

**Additional context**

**Comment by d4rken** [comment]
Is there an issue with the current build on Android 13?

**Comment by pwd-github** [comment]
> Is there an issue with the current build on Android 13?

Nope, it works. It's just the only app targeting Pie left on my system. It feels like a security risk. Though I know it's not.
