### ISSUE TITLE
Running System Cleaner crash

### ISSUE THREAD

**Issue by SaigyoujiYusora** [d4rken-org/sdmaid#5686]
**Describe the bug**

**To Reproduce**
1. Go to 'System cleanup'
2. Click on 'start'
3. Wait for the scan to start
4. sdmaid crash

**Expected behavior**
SD Maid won't crash

**Debug log**
[sdmaid_logfile_1661716263867.txt.zip](https://github.com/d4rken-org/sdmaid/files/9440394/sdmaid_logfile_1661716263867.txt.zip)

**Smartphone (please complete the following information):**
 - Device: Samsung note 20ultra
 - OS: Android12

**Comment by d4rken** [comment]
Does it work if you run each tool individually?

According to the crash report from your install id (`b9d49281-7856-45e5-99bc-f2e5325a6b1b`), SD Maid crashed due to running out of available memory.

**Comment by SaigyoujiYusora** [comment]
> Does it work if you run each tool individually?
> 
> According to the crash report from your install id (`b9d49281-7856-45e5-99bc-f2e5325a6b1b`), SD Maid crashed due to running out of available memory.

Storage analyzer, Database, AppCleaner.
Running the above tool alone will still crash.

**Comment by d4rken** [comment]
Do you have custom filters activated?
Does it crash if you disable all system cleaner filter?

**Comment by SaigyoujiYusora** [comment]
> Do you have custom filters activated? Does it crash if you disable all system cleaner filter?

I don't have custom filters, if I disabled all system clearer filters, SD Maid will not crash.

**Comment by d4rken** [comment]
Can you narrow it down to a specific filter?

**Comment by d4rken** [comment]
Currently can't do anything about this, if we run out of memory :frowning_face:
