### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/GUNSHIP BATTLE Helicopter 3D_v2.7.22_apkpure.com.apk (FP)

### ISSUE THREAD

**Issue by 653969** [d4rken-org/sdmaid#5687]
### Target
Target: `/storage/emulated/0/Download/GUNSHIP BATTLE Helicopter 3D_v2.7.22_apkpure.com.apk`
Prefix-free: `Download/GUNSHIP BATTLE Helicopter 3D_v2.7.22_apkpure.com.apk`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `GUNSHIP BATTLE`
Packagename: `com.theonegames.gunshipbattle`
Version: `2.8.21 (2005021821)`

### Current owners
Appname: `ការគ្រប់គ្រងការទាញយក`
Packagename: `com.android.providers.downloads.ui`
Version: `2.0.7.8 (2078)`

~~Appname: `កម្មវិធី​ទាញ​យក`~~
~~Packagename: `com.android.providers.downloads`~~
~~Version: `10.1.0.9 (10109)`~~

~~Appname: `ប្រព័ន្ធ Android`~~
~~Packagename: `android`~~
~~Version: `11 (30)`~~

### SD Maid
Version: `4.15.13 (41513)`

### Device
Fingerprint: `vivo/1920/1920:11/RP1A.200720.012/compiler1126190159:user/release-keys`

### Comment
`Gunship battle free gold `

**Comment by 653969** [comment]
Ig

**Comment by dragonGod97677** [comment]
Invalid and no
