### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.snapchat.android/files (FP)

### ISSUE THREAD

**Issue by Iam757** [d4rken-org/sdmaid#5689]
### Target
Target: `/storage/emulated/0/Android/data/com.snapchat.android/files`
Prefix-free: `com.snapchat.android/files`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
~~Appname: `Snapchat`~~
~~Packagename: `com.snapchat.android`~~
~~Version: `11.92.0.33 (84635)`~~

### SD Maid
Version: `5.4.1 (50401)`

### Device
Fingerprint: `lge/cv7as_fg/cv7as:9/PKQ1.190302.001/2122209041e99:user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid
