### ISSUE TITLE
Accessibility Access grayed out of firestick

### ISSUE THREAD

**Issue by hossbags2** [d4rken-org/sdmaid#5690]
Using SD Maid Pro on firstick....accessibility access is grayed out...not able to clear cache in apps

**Comment by hossbags2** [comment]
Want to use appcleaner on firestick but not able to clear app cache

**Comment by d4rken** [comment]
I currently don#t own a firestick, anyone else have an idea?

**Comment by d4rken** [comment]
I think this is a new security feature on Android, you need to go into the system settings for SD Maid and allow access to sensible permissions.
