### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/media/com.topjohnwu.magisk/com.termux (FP)

### ISSUE THREAD

**Issue by Blackflagraiser** [d4rken-org/sdmaid#5693]
### Target
Target: `/storage/emulated/0/Android/media/com.topjohnwu.magisk/com.termux`
Prefix-free: `com.topjohnwu.magisk/com.termux`
Path-prefix: `/storage/emulated/0/Android/media/`
Type: `DIRECTORY`
Location: `PUBLIC_MEDIA`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Shell`
Packagename: `com.android.shell`
Version: `12 (31)`

### Current owners
Appname: `Magisk`
Packagename: `com.topjohnwu.magisk`
Version: `25.2 (25200)`

### SD Maid
Version: `5.4.2 (50402)`

### Device
Fingerprint: `samsung/beyond1qltesq/beyond1q:12/SP1A.210812.016/G973USQU6IVE7:user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid suggested new owner
