### ISSUE TITLE
Display TargetSDK of apps in "App Control"

### ISSUE THREAD

**Issue by Guru-25** [d4rken-org/sdmaid#5695]

**Comment by d4rken** [comment]
What is your use-case for this?

**Comment by Guru-25** [comment]
> What is your use-case for this?

Useful to check whether an installed app is using latest sdk or not

Eg: ![IMG_20220902_141653](https://user-images.githubusercontent.com/70903440/188101575-a961be1f-007c-454f-80c4-4c9d559d8555.jpg)

**Comment by d4rken** [comment]
Why do you need to know if an app targets the latest SDK?

**Comment by Guru-25** [comment]
> Why do you need to know if an app targets the latest SDK?

It is best practice to use applications with maximum SDK that the platform currently supports in order to ensure that the application is not running in the compatibility mode in order to use privacy-evading features. If you find this feature out of scope, kindly close this issue :)

**Comment by d4rken** [comment]
Bad news: I think it's on the scope border, and overall don't think it's necessary to have in SD Maid, so I'm closing this.

Good news, a made an app that shows is this and is overall more light weight than SD Maid for this purpose:
https://play.google.com/store/apps/details?id=eu.darken.myperm 
😎
