### ISSUE TITLE
Request shortcut permission if required

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#5699]
### What happened?
Не создаются активити ни для одного приложения, появляется сообщение "неудачно".

                                         
### SD Maid
Version: `5.4.1 (50401)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Redmi/dandelion_ru/dandelion:10/QP1A.190711.020/V12.0.14.0.QCDRUXM:user/release-keys`

**Comment by d4rken** [comment]
For all apps and activities?
Or only for some specific ones?

Shortcuts can't be created for everything, there are some limitations.

**Comment by Ingood5** [comment]
Для всех приложений и действий. Обнаружил в чем проблема: после установки у SD Maid нет разрешения создавать ярлыки на главном экране, приходится вручную заходить в настройки смартфона и давать разрешение. После того как дал разрешение ярлыки создаются.

**Comment by d4rken** [comment]
Can you show the screen where the permission need to be granted?

Did you update the ROM or was this always a problem?

**Comment by Ingood5** [comment]
![Screenshot_2022-09-13-13-30-29-264_com miui securitycenter](https://user-images.githubusercontent.com/60130882/189879509-41213026-fc43-4305-8500-8e1f59091b8a.jpg)

Раньше я писал про проблему с этим смартфоном #5137. С тех пор обновлял прошивку, по всей видимости исправили, но появилась эта проблема.
