### ISSUE TITLE
AppCleaner not clearing font files for KingsoftOffice

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#5700]
Папка /storage/emulated/0/Android/data/cn.wps.xiaomi.abroad.lite/.cache/KingsoftOffice/.fonts не очищается, хотя помечена для очистки. Включил все фильтры.
![Screenshot_2022-09-02-12-19-26-423_eu thedarken sdm](https://user-images.githubusercontent.com/60130882/188109263-b5d79585-9d02-4920-9dd7-c20408d31b52.jpg)

**Comment by Ingood5** [comment]
Такая же проблема с этими папками

/storage/emulated/0/Android/data/cn.wps.xiaomi.abroad.lite/.cache

/storage/emulated/0/Android/data/cn.wps.moffice_eng/.cache

/storage/emulated/0/Android/data/cn.wps.moffice_eng/.cache/KingsoftOffice/.fonts

**Comment by d4rken** [comment]
Can you give a debug log of the AppCleaner scan?

Is `/storage/emulated/0/Android/data/cn.wps.moffice_eng/.cache/KingsoftOffice` marked with the AppCleaner symbol?

**Comment by Ingood5** [comment]
[sdmaid_logfile_1663034543731.txt.zip](https://github.com/d4rken-org/sdmaid/files/9552928/sdmaid_logfile_1663034543731.txt.zip)



> Помечен `/storage/emulated/0/Android/data/cn.wps.moffice_eng/.cache/KingsoftOffice`символом AppCleaner?

Да

**Comment by d4rken** [comment]
```java
1663034590113  D/Exclusion:Simple: '/.cache/KingsoftOffice/.fonts/' matches '/storage/emulated/0/Android/data/cn.wps.moffice_eng/.cache/KingsoftOffice/.fonts/wingding.ttf'
1663034590114  D/Exclusion:Simple: '/.cache/KingsoftOffice/.fonts/' matches '/storage/emulated/0/Android/data/cn.wps.moffice_eng/.cache/KingsoftOffice/.fonts/.fontsCache'
1663034590114  D/Exclusion:Simple: '/.cache/KingsoftOffice/.fonts/' matches '/storage/emulated/0/Android/data/cn.wps.moffice_eng/.cache/KingsoftOffice/.fonts/mtextra.ttf'
1663034590115  D/Exclusion:Simple: '/.cache/KingsoftOffice/.fonts/' matches '/storage/emulated/0/Android/data/cn.wps.moffice_eng/.cache/KingsoftOffice/.fonts/symbol.ttf'
1663034590115  V/FileOpsHelper: Indirectly excluded parent: /storage/emulated/0/Android/data/cn.wps.moffice_eng/.cache/KingsoftOffice/.fonts
1663034590115  V/FileOpsHelper: Indirectly excluded parent: /storage/emulated/0/Android/data/cn.wps.moffice_eng/.cache/KingsoftOffice
```

Hm it's due to #1914

You can remove the exclusion for your install, but I'm not sure we should remove it globally.

**Comment by Ingood5** [comment]
Возможно, что в таком случае надо сделать чтобы папка не была помечена AppCleaner 🤔
