### ISSUE TITLE
Hidden caches from com.facemoji.lite.xiaomi

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#5702]
com.facemoji.lite.xiaomi

Две папки

/storage/emulated/0/Android/data/com.facemoji.lite.xiaomi/files/okhttp_cache1798737084

/storage/emulated/0/Android/data/com.facemoji.lite.xiaomi/files/okhttp_cache2018284696

Это кэш?

[files.zip](https://github.com/d4rken-org/sdmaid/files/9477000/files.zip)

**Comment by d4rken** [comment]
Yes I think they actually have a typo and it should be `com.facemoji.lite.xiaomi/files/okhttp_cache / 1798737084`.
