### ISSUE TITLE
Clutterreport: /storage/F946-1DFC/STB0495737FA271 (new)

### ISSUE THREAD

**Issue by barrboss222** [d4rken-org/sdmaid#5705]
### Target
Target: `/storage/F946-1DFC/STB0495737FA271`
Prefix-free: `STB0495737FA271`
Path-prefix: `/storage/F946-1DFC/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `SD Maid`
Packagename: `eu.thedarken.sdm`
Version: `5.4.0 (50400)`

### Current owners
None

### SD Maid
Version: `5.4.0 (50400)`

### Device
Fingerprint: `HONOR/PRA-TL10/HWPRA-H:8.0.0/HONORPRA-TL10/375(C10):user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid
