### ISSUE TITLE
Clutterreport: /data/app/~~QuFLA4gG_mjVJlNLoz9BPw==/com.payjoy.status-7g71QcA3kO4YNnPjsL8skA==/base.apk (new)

### ISSUE THREAD

**Issue by Daviid2205** [d4rken-org/sdmaid#5706]
### Target
Target: `/data/app/~~QuFLA4gG_mjVJlNLoz9BPw==/com.payjoy.status-7g71QcA3kO4YNnPjsL8skA==/base.apk`
Prefix-free: `app/~~QuFLA4gG_mjVJlNLoz9BPw==/com.payjoy.status-7g71QcA3kO4YNnPjsL8skA==/base.apk`
Path-prefix: `/data/`
Type: `FILE`
Location: `DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `PayJoy`
Packagename: `com.payjoy.status`
Version: `22.03.30.2017-4a45420 (2000005039)`

### Current owners
None

### SD Maid
Version: `5.4.0 (50400)`

### Device
Fingerprint: `samsung/a03snnxx/a03s:11/RP1A.200720.012/A037FXXU1AUI7:user/release-keys`

**Comment by d4rken** [comment]
SD Maid should already detect this, can you share a debug log?
Did you recently install or uninstall this app?
