### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android (FP)

### ISSUE THREAD

**Issue by Tiwhish** [d4rken-org/sdmaid#5710]
### Target
Target: `/storage/emulated/0/Android`
Prefix-free: `Android`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
~~Appname: `Système Android`~~
~~Packagename: `android`~~
~~Version: `12 (31)`~~

### SD Maid
Version: `5.4.1 (50401)`

### Device
Fingerprint: `samsung/a52xqcs/a52xq:12/SP1A.210812.016/A526WVLU6CVG4:user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid removal of current owner
