### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/update (FP)

### ISSUE THREAD

**Issue by Zinmimaunh** [d4rken-org/sdmaid#5713]
### Target
Target: `/storage/emulated/0/Download/update`
Prefix-free: `Download/update`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Current owners
~~Appname: `Downloads`~~
~~Packagename: `com.android.providers.downloads.ui`~~
~~Version: `12 (31)`~~

~~Appname: `Download Manager`~~
~~Packagename: `com.android.providers.downloads`~~
~~Version: `12.0.1 (1200001)`~~

~~Appname: `Android System`~~
~~Packagename: `android`~~
~~Version: `12 (31)`~~

### SD Maid
Version: `5.4.1 (50401)`

### Device
Fingerprint: `OPPO/CPH2159/OP4F25L1:12/SKQ1.210216.001/R.202207141715:user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid removal of current owners
