### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/Network manager(com.google.android.networkstack)-aml_net_330811010(330811010)-base.apk (FP)

### ISSUE THREAD

**Issue by Cascade1771** [d4rken-org/sdmaid#5718]
### Target
Target: `/storage/emulated/0/Download/Network manager(com.google.android.networkstack)-aml_net_330811010(330811010)-base.apk`
Prefix-free: `Download/Network manager(com.google.android.networkstack)-aml_net_330811010(330811010)-base.apk`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Current owners
Appname: `Android System`
Packagename: `android`
Version: `12 (31)`

~~Appname: `Downloads`~~
~~Packagename: `com.android.providers.downloads.ui`~~
~~Version: `12 (31)`~~

Appname: `Download Manager`
Packagename: `com.android.providers.downloads`
Version: `12 (31)`

### SD Maid
Version: `5.4.1 (50401)`

### Device
Fingerprint: `samsung/r8qsqx/r8q:12/SP1A.210812.016/G781USQS8FVH1:user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid suggested removing current owner
