### ISSUE TITLE
Clutterreport: /storage/emulated/0/astro/.trash/1662281453094_.$recycle_bin$/dirs/10/Dispositivos_ Una lista de los dispositivos (p.�ej (new)

### ISSUE THREAD

**Issue by Miguelangelmt** [d4rken-org/sdmaid#5719]
### Target
Target: `/storage/emulated/0/astro/.trash/1662281453094_.$recycle_bin$/dirs/10/Dispositivos_ Una lista de los dispositivos (p.�ej`
Prefix-free: `astro/.trash/1662281453094_.$recycle_bin$/dirs/10/Dispositivos_ Una lista de los dispositivos (p.�ej`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Current owners
None

### SD Maid
Version: `5.4.1 (50401)`

### Device
Fingerprint: `motorola/cebu_retailn/cebu:11/RZCS31.Q2-57-12-11/11bfc:user/release-keys`

### Comment
`por q no puedo borrarlo
`

**Comment by dragonGod97677** [comment]
Have you tried restarting your device and deleting it again?

Im gonna modify this clutter report:

> ### Target
> Target: `/storage/emulated/0/astro/.trash/` Prefix-free: `astro/.trash` Path-prefix: `/storage/emulated/0/` Type: `FOLDER` Location: `SDCARD` Current keeper state: `false` Suggested keeper state: `false`
> 
> ### Suggested owners
> ### Current owners
> None
> 
> ### SD Maid
> Version: `5.4.1 (50401)`
> 
> ### Device
> Fingerprint: `motorola/cebu_retailn/cebu:11/RZCS31.Q2-57-12-11/11bfc:user/release-keys`
> 
> ### Comment
> `por q no puedo borrarlo`
