### ISSUE TITLE
Clutterreport: /system/app/Sar (FP)

### ISSUE THREAD

**Issue by FrankEsery** [d4rken-org/sdmaid#5722]
### Target
Target: `/system/app/Sar`
Prefix-free: `Sar`
Path-prefix: `/system/app/`
Type: `DIRECTORY`
Location: `SYSTEM_APP`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Analytics`
Packagename: `com.miui.analytics`
Version: `5.0.0 (2022042900)`

Appname: `ATMWifiMeta`
Packagename: `com.mediatek.atmwifimeta`
Version: `2.1.00.00 (210000)`

### Current owners
Appname: `SarUI`
Packagename: `com.longcheertel.sarauth`
Version: `1.0.0 (100)`

### SD Maid
Version: `5.4.3 (50403)`

### Device
Fingerprint: `Redmi/dandelion_global/dandelion:10/QP1A.190711.020/V12.0.20.0.QCDMIXM:user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid new suggested owner
