### ISSUE TITLE
Clutterreport: /system/app/PaymentService (FP)

### ISSUE THREAD

**Issue by FrankEsery** [d4rken-org/sdmaid#5723]
### Target
Target: `/system/app/PaymentService`
Prefix-free: `PaymentService`
Path-prefix: `/system/app/`
Type: `DIRECTORY`
Location: `SYSTEM_APP`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Android Accessibility Suite`
Packagename: `com.google.android.marvin.talkback`
Version: `13.0.0.456695251 (60125022)`

### Current owners
Appname: `Mi Coin`
Packagename: `com.xiaomi.payment`
Version: `1.12.8-global (1048036)`

### SD Maid
Version: `5.4.3 (50403)`

### Device
Fingerprint: `Redmi/dandelion_global/dandelion:10/QP1A.190711.020/V12.0.20.0.QCDMIXM:user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid new suggested owner
