### ISSUE TITLE
SD Maid marks for deletion files and folders with the same name

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#5724]
Заметил, что если SD Maid помечает что-то для удаления, то он помечает и файл и папку с таким же именем. Например, если файл помечен как кэш и вместо него создать папку с таким же именем, то она тоже будет помечена как кэш. Это безопасно?

**Comment by d4rken** [comment]
This differs a bit between the different tools, some differentiate between files and folders and some don't.
Can you show me an example?

**Comment by Ingood5** [comment]
Во втором случае другие произвольные файлы в папке не помечены.


![IMG_20220921_152401](https://user-images.githubusercontent.com/60130882/191505772-985120f0-a03c-44c4-ac5c-c84e941788a5.jpg)
![IMG_20220921_153617](https://user-images.githubusercontent.com/60130882/191505784-34f42801-4d37-4c82-8791-57c942725d5b.jpg)
![IMG_20220921_153443](https://user-images.githubusercontent.com/60130882/191505790-fe2a1d4a-ecd5-4f5a-afd4-398099d1cc50.jpg)
![IMG_20220921_153303](https://user-images.githubusercontent.com/60130882/191505792-98e04a0e-9e1e-4795-83f8-911e25add9a3.jpg)

**Comment by d4rken** [comment]
Not all filters specify a type (file vs folder), it seems in this case it's not specified and SD Maid only checks the filename. That's okay imho.

Thanks for the report though, I'll confirm this in a few other cases.
