### ISSUE TITLE
Garbage in /storage/emulated/0/DCIM/Camera

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#5725]
Когда я выполняю действия:
1. На заблокированном экране жму кнопку быстрого запуска приложения камера.
2. Переключаюсь на режим видеозаписи.
3. Не начинаю запись, выхожу из приложения камера;

– после этого в папке /storage/emulated/0/DCIM/Camera создаются пустые файлы VID_20220906_125859.mp4, VID_20220920_092728.mp4 и т.д., цифры обозначают дату и время. Возможно их надо удалять. Если запись начать, создаются такие же файлы но не пустые.

**Comment by d4rken** [comment]
This sounds like a bug in the camera app? Trying to delete these seems dangerous...

**Comment by Ingood5** [comment]
По какой причине пустые файлы в такой ситуации может быть опасно удалять? 🤔

**Comment by dragonGod97677** [comment]
Try force stopping the camera app and clear it's data and try again id issue still present?

**Comment by Ingood5** [comment]
> Попробуйте принудительно остановить приложение камеры, очистить его данные и повторить попытку, проблема с идентификатором все еще существует?

После этих действий проблема осталась
