### ISSUE TITLE
com.meizu.filemanager garbage is not being deleted

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#5727]
### What happened?
Файлы в корзине проводника meizu помечены AppCleaner но при сканировании не отображаются. Проводник установлен, сканирование корзин включено.

/storage/emulated/0/Android/data/.com.meizu.filemanager/.garbage.  

Имя пакета com.meizu.filemanager

[sdmaid_logfile_1663765667871.txt.zip](https://github.com/d4rken-org/sdmaid/files/9616887/sdmaid_logfile_1663765667871.txt.zip)

### SD Maid
Version: `5.4.1 (50401)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Redmi/dandelion_ru/dandelion:10/QP1A.190711.020/V12.0.17.0.QCDRUXM:user/release-keys`

**Comment by d4rken** [comment]
https://github.com/d4rken-org/sdmaid-se/pull/201
