### ISSUE TITLE
/storage/emulated/0/Android/media/com.whatsapp.w4b/WhatsApp Business/.Shared/.nomedia

### ISSUE THREAD

**Issue by itatoboali** [d4rken-org/sdmaid#5731]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Debug log**
Record a [debug log](https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log) while reproducing the problem and attach the zip file here.

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android 10]

**Additional context**

**Comment by itatoboali** [comment]
siapkan

**Comment by itatoboali** [comment]
Duplicate of #

**Comment by itatoboali** [comment]
![Uploading cc03e190cf6a46d7b1d044f6789fc4ca.jpg…]()

**Comment by dragonGod97677** [comment]
Closing because no sufficient info
