### ISSUE TITLE
Clutterreport: /storage/1C11-1815/Android/data/com.viber.voip (FP)

### ISSUE THREAD

**Issue by erykvonoleg** [d4rken-org/sdmaid#5733]
### Target
Target: `/storage/1C11-1815/Android/data/com.viber.voip`
Prefix-free: `com.viber.voip`
Path-prefix: `/storage/1C11-1815/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Current owners
Appname: `?`
Packagename: `com.viber.voip`
Version: ` (-1)`

### SD Maid
Version: `5.4.1 (50401)`

### Device
Fingerprint: `xiaomi/cactus/cactus:9/PPR1.180610.011/V11.0.8.0.PCBMIXM:user/release-keys`

### Comment
`не удаляется указаний файл
com.viber.voip.data`

**Comment by erykvonoleg** [comment]
Что делать?

**Comment by erykvonoleg** [comment]
Как правильно поступить

**Comment by erykvonoleg** [comment]
Что нужно сделать и нужно ли удалять или оставить,кроме того есть проблема с активацией Вайбер вчера грохнулся и активация так и не пропускает сообщает о случился сбой активации.помогите? Что делать не знаю остался без связи

**Comment by dragonGod97677** [comment]
Sorry but you have to ask viber support directly for viber related problem. And im closing this because there's is nothing sd maid related in this issue.
