### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/unnamed.png (FP)

### ISSUE THREAD

**Issue by bluemanwidaplan22** [d4rken-org/sdmaid#5736]
I### Target
Target: `/storage/emulated/0/Download/unnamed.png`
Prefix-free: `Download/unnamed.png`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Android Services Library`
Packagename: `com.google.android.ext.services`
Version: `1 (1)`

### Current owners
Appname: `Downloads`
Packagename: `com.android.providers.downloads.ui`
Version: `7.0 (24)`

Appname: `Download Manager`
Packagename: `com.android.providers.downloads`
Version: `6.30.15.2 (63001502)`

Appname: `Android System`
Packagename: `android`
Version: `7.0 (24)`

### SD Maid
Version: `5.4.3 (50403)`

### Device
Fingerprint: `MetroPCS/sf340n_mpcs_us/sf340n:7.0/NRD90U/190291823f95d:user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid new suggested owners
