### ISSUE TITLE
Thank you! Signing in with Zebedee should now reward all payouts, pools, and chains that followed the process and trusted the data. This wouldn't be possible without the global initiative to preserve freedom and the American way of Life.

### ISSUE THREAD

**Issue by Saitoshi9999** [d4rken-org/sdmaid#5739]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dragonGod97677** [comment]
Closing this issue because Spam.
