### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/media (FP)

### ISSUE THREAD

**Issue by jrjohnson11** [d4rken-org/sdmaid#5756]
### Target
Target: `/storage/emulated/0/Android/media`
Prefix-free: `Android/media`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Current owners
~~Appname: `Android System`~~
~~Packagename: `android`~~
~~Version: `11 (30)`~~

### SD Maid
Version: `5.4.3 (50403)`

### Device
Fingerprint: `motorola/tonga_g/tonga:11/RRQS31.Q3-68-140-5/b63de:user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid suggested removing current owner
