### ISSUE TITLE
Floating action button becomes invisible, but not un-clickable

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#5758]
### What happened?
Когда я в любом инструменте проматываю окно вниз, значок корзины внизу справа исчезает, но если на ее место нажать, она нажимается.

> When I scroll down the window in any tool, the trash can icon at the bottom right disappears, but if I click on its place, it is clicked.

### What did you expect to happen?
Она не должна нажиматься когда исчезла

### How can I reproduce the issue?
В любом инструменте начать мотать вниз, чтобы корзина исчезла, после этого нажать точно в центре места где она была

### SD Maid
Version: `5.4.3 (50403)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Redmi/dandelion_ru/dandelion:10/QP1A.190711.020/V12.0.17.0.QCDRUXM:user/release-keys`

**Comment by d4rken** [comment]
This seems to be an OS specific issue, I couldn't reproduce this on a Pixel 6 with Android 13.

I also looked into the code a bit, and changing the code is not trivial if I do it "quickly" then I will likely create more bugs than I fix.

Sorry.
