### ISSUE TITLE
Save filter state 

### ISSUE THREAD

**Issue by alabotski** [d4rken-org/sdmaid#5760]
Section App Control
Can you add support save filter state
It crashes after reboot 

![Screenshot_2022-10-07-21-08-15-1386215808](https://user-images.githubusercontent.com/439337/194622646-8073e1e5-133d-4199-9295-28a8bf464041.png)

**Comment by d4rken** [comment]
Can you provide a stacktrace/error log of the crash?

**Comment by alabotski** [comment]
@d4rken 
It's not error
The filter is reset

For example 
1. Default filter - All items
2. I choose - User
3. Work with list
4. Restart app
5. And filter again - *All items*. Expect - *User*

**Comment by Alseed8889** [comment]
كيف استعادة ماتم حذفة رجو رد
