### ISSUE TITLE
Clutterreport: /storage/emulated/0/system/Files [11].apk

### ISSUE THREAD

**Issue by M3GA-19** [d4rken-org/sdmaid#5761]
### Target
Target: `/storage/emulated/0/system/Files [11].apk`
Prefix-free: `system/Files [11].apk`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `External Storage`
Packagename: `com.android.externalstorage`
Version: `11 (30)`

### Current owners
Appname: `?`
Packagename: `com.yingyonghui.market`
Version: ` (-1)`

Appname: `?`
Packagename: `com.meitu.meiyancamera`
Version: ` (-1)`

### SD Maid
Version: `5.4.3 (50403)`

### Device
Fingerprint: `WIKO/U316AT/U316AT:11/RP1A.200720.011/1662007980:user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid
