### ISSUE TITLE
Clutterreport: /storage/1C11-1815/Android/data/com.viber.voip (FP)

### ISSUE THREAD

**Issue by erykvonoleg** [d4rken-org/sdmaid#5763]
### Target
Target: `/storage/1C11-1815/Android/data/com.viber.voip`
Prefix-free: `com.viber.voip`
Path-prefix: `/storage/1C11-1815/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Current owners
Appname: `?`
Packagename: `com.viber.voip`
Version: ` (-1)`

### SD Maid
Version: `5.4.3 (50403)`

### Device
Fingerprint: `xiaomi/cactus/cactus:9/PPR1.180610.011/V11.0.8.0.PCBMIXM:user/release-keys`

### Comment
`мне не удалось этот паразитирующий файл удалить из нескольких попыток сообщение 0 файлов удаленно что делать что это такое `

**Comment by erykvonoleg** [comment]
[Clutterreport: /storage/1C11-1815/Android/data/com.viber.voip (FP)](https://github.com/d4rken-org/sdmaid/issues/5763#top)
#5763
[erykvonoleg](https://github.com/erykvonoleg) opened this issue 1 minute ago · 0 comments
Comments
[erykvonoleg](https://github.com/erykvonoleg) commented [1 minute ago](https://github.com/d4rken-org/sdmaid/issues/5763#issue-1405212974)
Target
Target: /storage/1C11-1815/Android/data/com.viber.voip
Prefix-free: com.viber.voip
Path-prefix: /storage/1C11-1815/Android/data/
Type: DIRECTORY
Location: PUBLIC_DATA
Current keeper state: false
Suggested keeper state: true

Suggested owners
Current owners
Appname: ?
Packagename: com.viber.voip
Version: (-1)

SD Maid
Version: 5.4.3 (50403)

Device
Fingerprint: xiaomi/cactus/cactus:9/PPR1.180610.011/V11.0.8.0.PCBMIXM:user/release-keys

Comment
мне не удалось этот паразитирующий файл удалить из нескольких попыток сообщение 0 файлов удаленно что делать что это такое

**Comment by erykvonoleg** [comment]
мне не удалось этот паразитирующий файл удалить из нескольких попыток сообщение 0 файлов удаленно что делать что это такое

**Comment by dragonGod97677** [comment]
reset your phone.
Do remember to do backups of your phone data first before resetting your phone, or you will lose those. And im closing this since you are only having problem with your phone, not sd maid.
I've experienced this once, sometimes resetting will fix it
