### ISSUE TITLE
Bug: Can't add Exclusion

### ISSUE THREAD

**Issue by researchscum** [d4rken-org/sdmaid#5766]
### What happened?
yes i press something the app closed i want to add directory to exclusion "/storage/emulated/0/Tachiyomi" the choice is "Global" when i press the save icon app closed

### What did you expect to happen?
i am now using beta 5.5.0 when i used 5.4.3 it save that directory for exclusion

### How can I reproduce the issue?
add any folder from "/storage/emulated/0" to exclusion then press save button?

### Comments
thanks
### SD Maid
Version: `5.5.0 (50500)`
Pro: `isPro=false || isComplete=true (unl=false, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Redmi/alioth/alioth:12/RKQ1.211001.001/V13.0.7.0.SKHCNXM:user/release-keys`

**Comment by d4rken** [comment]
Thanks for the report!
There was a regression related to serialization of exclusion data, please try v5.5.1. It should be fixed.
