### ISSUE TITLE
the checkbox disappears when adding folders to the search for duplicates

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#5767]
### What happened?
                                 
1. Захожу в настройки - поиск дубликатов, перехожу в режим добавления папок. Внизу справа отображается зелёная галочка.
2. Начинаю проматывать вниз, галочка исчезает.
3. Захожу в любую папку в момент, когда галочки нет.
4. В открытой папке галочки тоже нет, из-за этого нет возможности выделить и добавить вложенные папки. Галочка появляется только если содержимое папки не умещается на экране и есть возможность проматывать вверх-вниз.

### SD Maid
Version: `5.4.3 (50403)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Redmi/dandelion_ru/dandelion:10/QP1A.190711.020/V12.0.17.0.QCDRUXM:user/release-keys`

**Comment by Ingood5** [comment]
Заметил что вы исправили ошибку, которая не являлась критичной: https://github.com/d4rken-org/sdmaid/issues/5936.

Можете проблему с галочкой, указанную в этом отчёте, тоже исправить?  Часто пользуюсь поиском дубликатов, из-за этой ошибки неудобно. Поиск дубликатов хорошая функция, не знаю есть ли аналоги в других приложениях.  Невнимательный пользователь может не понять из-за чего в папках галочка исчезает. Как я понял в SD Maid 2 этой функции не будет.

**Comment by Ingood5** [comment]
https://github.com/d4rken-org/sdmaid/assets/60130882/6898abfd-fdb6-42bc-9470-1887723dc95e

**Comment by d4rken** [comment]
> Заметил что вы исправили ошибку, которая не являлась критичной: #5936.
> 
> Можете проблему с галочкой, указанную в этом отчёте, тоже исправить? Часто пользуюсь поиском дубликатов, из-за этой ошибки неудобно. Поиск дубликатов хорошая функция, не знаю есть ли аналоги в других приложениях. Невнимательный пользователь может не понять из-за чего в папках галочка исчезает. Как я понял в SD Maid 2 этой функции не будет.

I wanted to do something good for SD Maid 1 users :blush:. It was an easy fix.



> Screenrecorder-2023-07-08-14-12-03-917.mp4

I will look into it, but I can not make any promises :beers:

**Comment by d4rken** [comment]
Should be fixed in the next update (v5.5.11?).
Send me a mail if you want to test it now.

**Comment by Ingood5** [comment]
Thank you! 🎉
