### ISSUE TITLE
Database cleanup crash at about 14%

### ISSUE THREAD

**Issue by iustinteo** [d4rken-org/sdmaid#5768]
### What happened?
Crush la curățarea bazei de date, se înțepenește, androidul se ambalează termic

### What did you expect to happen?
Sa curate baza de date corect fără să se înțepenească Androidul. Aștept să corectezi acest Bug. 

### How can I reproduce the issue?
Crush la curățarea bazei de date, ambalare termica a Androidului

### Comments
Aștept corectarea bug-ului
### SD Maid
Version: `5.5.1 (50501)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `Redmi/sweet_eea/sweet:12/SKQ1.210908.001/V13.0.13.0.SKFEUXM:user/release-keys`

**Comment by d4rken** [comment]
Please provide a debug log:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log

**Comment by Thunder-Mist** [comment]
Database crash is not at 14% it's because it's trying to cleanup it's own database i.e eu.thedarken.sdm ,hence the crash

**Comment by researchscum** [comment]
it happen to me to, i am not sure if it is ok to put this here

### What happened?
app stopped when optimizing database, it stop/freeze when optimizing "/data/user/0/eu.thedarken.sdm/databases/event_history_v2.db"

### What did you expect to happen?
v 5.4.3 app keep working and optimize database with same settings and phone

### How can I reproduce the issue?
in app setting > database > check all available option except "skip running apps" then re-open sd maid and do database optimization?

### Comments
when i exclude "/data/user/0/eu.thedarken.sdm/databases/event_history_v2.db" and check database only it never stuck anymore.
[sdmaid_logfile_1665685624363.txt](https://github.com/d4rken-org/sdmaid/files/9779572/sdmaid_logfile_1665685624363.txt) error happened
[sdmaid_logfile_1665685624363.txt.zip](https://github.com/d4rken-org/sdmaid/files/9779573/sdmaid_logfile_1665685624363.txt.zip) with exclude

### SD Maid
Version: `5.5.1 (50501)`
Pro: `isPro=false || isComplete=true (unl=false, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `Redmi/alioth/alioth:12/RKQ1.211001.001/V13.0.7.0.SKHCNXM:user/release-keys`

**Comment by d4rken** [comment]
Hm, yeah SD Maid shouldn't run on it's own database. This might be a regression due to changes I made to exclusions in the last update.
