### ISSUE TITLE
I don't know if it would be possible

### ISSUE THREAD

**Issue by gallegonovato** [d4rken-org/sdmaid#5782]
Good afternoon:

I wanted to ask a question, I don't know if I could add in some version of Sd Maid, a button or tab so that when the menus come out and you hit skip. That it does not always ask.

For example in this version comes out a notice of accessibility services. And I give it to omit. But it comes up again and again every time I use Sd Maid. I attach a screenshot so you can see which one I am referring to: https://ibb.co/SmJ7vLb

That's why I don't know, if you can add an option not to show the message again.

Thanks for your help and time.

**Comment by d4rken** [comment]
There should already be such an option.
Top right corner the three dots.

**Comment by gallegonovato** [comment]
Good afternoon @d4rken 

You are right. I didn't know it was in that place.

I finally found it and marked it.

Thank you very much for the help and for your time.

Best regards
