### ISSUE TITLE
How to restore what has been deleted in the device please reply 

### ISSUE THREAD

**Issue by Alseed8889** [d4rken-org/sdmaid#5790]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Alseed8889** [comment]
I wish you would answer my question, all the files have been deleted

**Comment by d4rken** [comment]
See https://github.com/d4rken/sdmaid-public/wiki/Frequently-Asked-Questions#recover-deleted-files

**Comment by Alseed8889** [comment]
Bitte kann ich lösen, was auf dem Gerät gelöscht wurde تم الإرسال من هاتف Huawei الخاص بي-------- الرسالة الأصلية --------من:‏ Matthias Urhahn ***@***.***>التاريخ:‏ الأحد، ٣٠ أكتوبر، ٢٠٢٢ ١١:٥٠ صإلى:‏ d4rken-org/sdmaid ***@***.***>نسخة إلى:‏ Alseed8889 ***@***.***>, Author ***@***.***>الموضوع:‏ Re: [d4rken-org/sdmaid] How to restore what has been deleted in the device please reply  (Issue #5790)
Closed #5790 as completed.
