### ISSUE TITLE
Bug: Unable to do App Cleaning 

### ISSUE THREAD

**Issue by Vishnuvh08** [d4rken-org/sdmaid#5791]
### What happened?
When trying to do delete function. App quits without automatically 

### What did you expect to happen?
I want to free up space. But when the operation starts and quits automatically its a waste of time waiting the whole process of searching and filtering.

### How can I reproduce the issue?
App cleaning, delete option at last

### Comments
Waste of time
### SD Maid
Version: `5.4.3 (50403)`
Pro: `isPro=true || isComplete=true (unl=false, iap=true, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `vivo/1951/1951:11/RP1A.200720.012/compiler1210223124:user/release-keys`

**Comment by d4rken** [comment]
Please provide a debug log of this:
https://github.com/d4rken-org/sdmaid/wiki/Reporting-a-bug#debug-log

**Comment by d4rken** [comment]
Check back after v5.5.8
