### ISSUE TITLE
App Data Cleaner

### ISSUE THREAD

**Issue by Teals53** [d4rken-org/sdmaid#5803]
it should be good for the people like me if you add an option in app cleaner settings for clean app datas too with an app whitelist option so i can be reset my phone back to factory without resetting it and it can save my time bcs im not gonna transfer my datas and i not need to setup everything again with whitelist option

**Comment by d4rken** [comment]
Whitelist is out of scope, there is the exclusion feature though:
https://github.com/d4rken/sdmaid-public/wiki/Exclusions
