### ISSUE TITLE
System Cleaner - Empty Directories 

### ISSUE THREAD

**Issue by alabotski** [d4rken-org/sdmaid#5804]
Hi

Is is possible exclude some directories ?
I have some my work projects in Documents folder

And it's not very convenient, when SDMain delete all empty folders

PS Yes of course I can create empty files.... but may it possible do with SDMain

![Screenshot_2022-11-10-15-46-12-1324348736](https://user-images.githubusercontent.com/439337/201103564-c1560381-0065-4478-9792-cc1ffff68af8.png)

**Comment by d4rken** [comment]
https://github.com/d4rken/sdmaid-public/wiki/Exclusions
