### ISSUE TITLE
AppCleaner ACS not working

### ISSUE THREAD

**Issue by Tbo29** [d4rken-org/sdmaid#5813]
Chromecast with Google TV SD Maid Beta 5.55 gives the following error when trying to clean apps:

"Unable to add window - token null is not valid; is your activity running?"

No such an error on 5.54.

**Comment by SunDevil311** [comment]
![Screenshot_20221116-225441_SD Maid](https://user-images.githubusercontent.com/10506001/202377582-563516c3-5226-4934-a82b-6756acf98907.png)
Getting the same error on Android 12 / Samsung Galaxy S20 5G (SM-G981U)

**Comment by d4rken** [comment]
Can someone record a log of this?
https://github.com/d4rken-org/sdmaid/wiki/Reporting-a-bug#debug-log

**Comment by d4rken** [comment]
I could reproduce it on a Samsung device.
It works on a Pixel device though :frowning_face:.
This error still happens with the previous code for some devices, and the idea was to improve upon that.
Seems that backfired.

I'm restoring the previous code for this.
