### ISSUE TITLE
Android Tv 9 & 10 no need such permision: battery optimization !!! Device with OS Android tv isn't have battery!

### ISSUE THREAD

**Issue by iustinteo** [d4rken-org/sdmaid#5814]
For sd maid 5.5.5: Android Tv 9 & 10 no need such permision: battery optimization!! Device with Android tv don't have battery! No battery, no permision. Also, sd maid work verry good in Android Tv. Solution ?
iustinteo@gmail.com

**Comment by d4rken** [comment]
It's not strictly about battery, but prevent the system from killing background operations. It's unclear whether this still happens on Android TV devices, I don't have Android TV...

**Comment by d4rken** [comment]
I'm disabling the check for TVs for now.
