### ISSUE TITLE
setup button

### ISSUE THREAD

**Issue by bai-qiao** [d4rken-org/sdmaid#5816]
**Describe the bug**
when i tap "setup" in advanced settings nothing happen

**To Reproduce**
1. Go to 'settings'
2. Click on 'general settings'
3. Click on 'advanced settings'
4. Click on 'setup'
5. nothing happen

**Expected behavior**
pop up setting like first time open after install.

**Screenshots**
-

**Debug log**

[sdmaid_logfile_1668744087173.txt.zip](https://github.com/d4rken-org/sdmaid/files/10037626/sdmaid_logfile_1668744087173.txt.zip)

**Smartphone (please complete the following information):**
 - Device: [Redmi K40]
 - OS: [Android 12]

**Additional context**
-

**Comment by d4rken** [comment]
Should be fixed in next update.
