### ISSUE TITLE
add cleaning filtering in hidden cache.

### ISSUE THREAD

**Issue by Tuxiis** [d4rken-org/sdmaid#5819]
I'm not a programmer, so I can't give precise details.

sd maid pro/free + sygic app have an error because sd maid deletes the downloaded maps, but that's only if I have the option to clear the hidden cache.
![Screenshot_2022-11-20-16-15-18-76_62f0e9ef2a35bdc7c62d39832d484c48](https://user-images.githubusercontent.com/101512522/202929818-5f3e0cef-48ff-44bc-afc9-ff2cc804760b.jpg)

**Comment by Perea17** [comment]
Thanks
