### ISSUE TITLE
Bug: App cleaner not responding 

### ISSUE THREAD

**Issue by 03Hari30** [d4rken-org/sdmaid#5821]
### What happened?
App cleaner takes time and clearing same apps for long time and task is not completed

### What did you expect to happen?
App cleaner computing speed need to improved and cahe need to be removed as before 

### How can I reproduce the issue?
Go to three dash button and look for app cleaner and run the task and then give permission for accessibility then proceed,it take's more time and finally the task discontinue's and cahe is not removed from apps

### Comments
Kindly resolve this bug issue sd maid app is known for this app cahe remover and this feature is the main thing to perform Android system clean
### SD Maid
Version: `5.5.4 (50504)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `vivo/1806/1806:10/QP1A.190711.020/compiler07041025:user/release-keys`

**Comment by d4rken** [comment]
Please provide a debuglog of this:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log
