### ISSUE TITLE
App Cleaner not completing task

### ISSUE THREAD

**Issue by Tbo29** [d4rken-org/sdmaid#5822]
What happened?

App cleaner locks up for some time trying to open the cache cleaning page of the first app, then does not clean first app and goes on to the next. Before that it always asks for permission to access to Android/data.

What did you expect to happen?

App cleaner  should clean every cache it found during scanning and not asking for permission to Android/data at each run which could not be given on Android TV 12.

How can I reproduce the issue?

Open the App Cleaner Task, click scan, then all and finally delete.

Comments

Please resolve this bug.

SD Maid
Version: 5.5.6 

Device: Chromecast with Google TV and Android TV 12.

**Comment by d4rken** [comment]
Please provide a debug log of this.
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log
