### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/Permission Pilot(eu.darken.myperm)-1.1.1-rc0(10101000)-split_config.xxhdpi.apk (FP)

### ISSUE THREAD

**Issue by Alianonime** [d4rken-org/sdmaid#5828]
### Target
Target: `/storage/emulated/0/Download/Permission Pilot(eu.darken.myperm)-1.1.1-rc0(10101000)-split_config.xxhdpi.apk`
Prefix-free: `Download/Permission Pilot(eu.darken.myperm)-1.1.1-rc0(10101000)-split_config.xxhdpi.apk`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Current owners
~~Appname: `Système Android`~~
~~Packagename: `android`~~
~~Version: `10 (29)`~~

Appname: `Téléchargements`
Packagename: `com.android.providers.downloads.ui`
Version: `10 (29)`

Appname: `Gestionnaire de téléchargement`
Packagename: `com.android.providers.downloads`
Version: `10 (29)`

### SD Maid
Version: `5.5.6 (50506)`

### Device
Fingerprint: `samsung/star2ltexx/star2lte:10/QP1A.190711.020/G965FXXUHFVG4:user/release-keys`

**Comment by Nuy06155** [comment]
> ### Target
> Target: `/storage/emulated/0/Download/Permission Pilot(eu.darken.myperm)-1.1.1-rc0(10101000)-split_config.xxhdpi.apk`
> Prefix-free: `Download/Permission Pilot(eu.darken.myperm)-1.1.1-rc0(10101000)-split_config.xxhdpi.apk`
> Path-prefix: `/storage/emulated/0/`
> Type: `FILE`
> Location: `SDCARD`
> Current keeper state: `true`
> Suggested keeper state: `false`
> 
> ### Suggested owners
> ### Current owners
> ~~Appname: `Système Android`~~
> ~~Packagename: `android`~~
> ~~Version: `10 (29)`~~
> 
> Appname: `Téléchargements`
> Packagename: `com.android.providers.downloads.ui`
> Version: `10 (29)`
> 
> Appname: `Gestionnaire de téléchargement`
> Packagename: `com.android.providers.downloads`
> Version: `10 (29)`
> 
> 
> ### SD Maid
> Version: `5.5.6 (50506)`
> 
> ### Device
> Fingerprint: `samsung/star2ltexx/star2lte:10/QP1A.190711.020/G965FXXUHFVG4:user/release-keys`
> 
>
