### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/MEGA Downloads/Red Adventure - Demo completa/Red Adventure - Demo completa/Graphics/Animations/Trov�o.png (FP)

### ISSUE THREAD

**Issue by Jesule88** [d4rken-org/sdmaid#5829]
### Target
Target: `/storage/emulated/0/Download/MEGA Downloads/Red Adventure - Demo completa/Red Adventure - Demo completa/Graphics/Animations/Trov�o.png`
Prefix-free: `Download/MEGA Downloads/Red Adventure - Demo completa/Red Adventure - Demo completa/Graphics/Animations/Trov�o.png`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Administrador de descargas`
Packagename: `com.android.providers.downloads`
Version: `12.0.1 (1200001)`

Appname: `Descargas`
Packagename: `com.android.providers.downloads.ui`
Version: `12 (31)`

Appname: `Sistema Android`
Packagename: `android`
Version: `12 (31)`

### Current owners
Appname: `Descargas`
Packagename: `com.android.providers.downloads.ui`
Version: `12 (31)`

Appname: `Administrador de descargas`
Packagename: `com.android.providers.downloads`
Version: `12.0.1 (1200001)`

Appname: `Sistema Android`
Packagename: `android`
Version: `12 (31)`

### SD Maid
Version: `5.5.6 (50506)`

### Device
Fingerprint: `OPPO/CPH2135EEA/OP4EFDL1:12/RKQ1.211119.001/Q.GDPR.202209141700:user/release-keys`

**Comment by Nuy06155** [comment]
สงสัยคงเสียเงินฟรี คงไม่ได้ใช้งาน ใช้งานไม่เป็นนะค่ะ
ไม่รู้ว่าซื่อแพคเกจแล้วต้องทำอย่างอื่นอีก มีแต่ภาษาอังกฤษ
ตั้งเป็นภาษาไทยก็ไม่ได้ ใช้แอปแปลก็ไม่ได้ เข้าไปก็เด้งออก github
ก็ให้ลงชื่อเข้าใช้อยู่นั่นละ พอเข้าใช้ก็บอกไม่มีบัญชีนี้ งง
ถึงเข้าไปได้ก็ใช้งานไม่เป็นอยู่นั่นแหละคะ
รู้สึกว่าโทรศัพท์ถูกรบกวนและก็โดนแฮก แต่ก็ไม่รู้จะทำไง
นึกว่าซื้อแล้วก็จะใช้งานได้เลยน่ะค่ะ อุตส่าซื้อ ทั้ง sdmate  และก็ mate pro
ด้วย เสียเงินฟรี หรือบางทีก็อาจจะมีมิจฉาชีพที่รู้ว่าต้องทำไง เข้าไปใช้
แทนแล้วก็อาจเป็นได้ค่ะ

nuy06155

ในวันที่ จ. 28 พ.ย. 2022 07:53 Jesule88 ***@***.***> เขียนว่า:
