### ISSUE TITLE
For Christmas and New Year, can you put the hat and gloves on the maid.gif?

### ISSUE THREAD

**Issue by iustinteo** [d4rken-org/sdmaid#5844]
For Christmas and New Year, can you put the hat and gloves on the maid.gif? 
Or change the gif with a reindeer, or Santa Claus, or with other animations specific to Christmas?
For d4rken..

iustinteo@gmail.com

**Comment by Ahplla** [comment]
please, no!

**Comment by Ahplla** [comment]
> Aphplla, Why Not? Must be cosmetic thing one time on the year!

Because Christmas is a Catholic holiday, and not everyone is Catholic.  And not all people like this holiday.  Choosing one holiday over all the other hundreds is unfair and biased.  But this is just my opinion.

**Comment by iustinteo** [comment]
Aphplla,
Agree with you! So I will close this request.
All the best!
