### ISSUE TITLE
Bug: Appcleaner module issue

### ISSUE THREAD

**Issue by Juanmegas** [d4rken-org/sdmaid#5846]
### What happened?
Appcleaner not working properly, been failing while phone's blocked, if not, blocks my screen while working instead of working on background as before.

### What did you expect to happen?
It should be as it was before 5 or more updates, a background process without need of any human input while programmed for timed execution.

### How can I reproduce the issue?
Set timer to run Appcleaner while device is blocked(LG V20 phone with Android 9).

### Comments
Thanks for the hard work, please contact me if need more info or screenshots/details.
### SD Maid
Version: `5.5.6 (50506)`
Pro: `isPro=true || isComplete=true (unl=true, iap=true, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `lge/elsa_lgu_kr/elsa:9/PKQ1.190522.001/2019215574aa2:user/release-keys`

**Comment by d4rken** [comment]
To achieve the old behavior, go into AppCleaner settings and disable the accessibility service option.

**Comment by d4rken** [comment]
To remove inaccessible caches from the results (which can only be deleted using the accessibility service) untick that option in AppCleaner settings too.
