### ISSUE TITLE
Are accessibility permissions required?

### ISSUE THREAD

**Issue by TingTing1990** [d4rken-org/sdmaid#5848]
**Is your feature request related to a problem? Please describe.**
Is it necessary to use something that is all manual and does not need to be automated?
Because now you have to jump out of this every time you start it, if you don't have to, please don't pop up every time!

**Describe the solution you'd like**
Don't show again after clicking Skip, only popup again if necessary for action request!

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by d4rken** [comment]
You can choose "Don't show again" in the menu, top right corner of the app.
