### ISSUE TITLE
Can't install SD Maid Pro – Unlocker

### ISSUE THREAD

**Issue by artquest** [d4rken-org/sdmaid#5855]
Hi,
recently I’ve got an update to **SD Maid Pro – Unlocker,** but was unable to install it — Play dropped me an error:
“Can’t download” (screen attached). I’ve uninstalled the old version of Unlocker, cleared cache of Play Services and Play Store,
restarted the phone, but still get the same error. Perhaps it’s because my **Android version** is very old (**6.0**),
but it’s the latest available for my phone, **HTC One M8.** All the other app updates install as usual, without errors.

Maybe you can give me an activation code so I can activate Pro version using this way. My Google Play **Transaction ID** is
**GPA.1381075785457445.** My email is **artgrail@gmail.com.**

![photo_5242583948360532908_y_small](https://user-images.githubusercontent.com/24230703/207671142-ce2b6c3f-605d-4804-873d-c76354261013.jpg)

**Comment by d4rken** [comment]
It's caused by sanctions that Google Play applies to all Russian accounts, due to Russia attacking Ukraine. 

See:
https://support.google.com/googleplay/android-developer/answer/11950272

Please contact Google Play support over this matter.

**Comment by alexvas96** [comment]
@d4rken
Hi! Can you send the Access key as a workaround to activate the application?
