### ISSUE TITLE
Uninstall without root always assumes the user uninstalls the app

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid#587]
If we uninstall without root and the systems uninstall dialog shows, SD Maid always assumes that the user pressed OK, and that the uninstall was successful.

**Comment by Gitoffthelawn** [comment]
Confirmed

**Comment by d4rken** [comment]
Unsure how to fix this. We can block and wait for an "package removed" intent, but if the user aborts, there is no way I know of to detect that.

**Comment by Gitoffthelawn** [comment]
What about collecting a list of all installed apps and seeing if the app is still listed?

**Comment by d4rken** [comment]
We don't know when to check though. There is no "abort" event. I'll have to see if we can detect the UI window getting focus again but this is all but a clean integration...

**Comment by d4rken** [comment]
Fixed in SD Maid SE.

**Comment by Gitoffthelawn** [comment]
@d4rken What was the solution that wound up working?

**Comment by d4rken** [comment]
Sounds trivial, but just monitoring the list of installed apps :grin: 

https://github.com/d4rken-org/sdmaid-se/blob/4dacc27f7de9156fd4724e4f3f749fd49b97c9e3/app/src/main/java/eu/darken/sdmse/appcontrol/core/uninstall/Uninstaller.kt#L66-L77

The thing is that this was just a lot easier to implement in SD Maid SE, due to better core design, e.g. having an auto-refreshing list of installed apps and nicer ways of waiting with timeouts (Kotlin Flows + Coroutines).

**Comment by Gitoffthelawn** [comment]
Thanks for the explanation.  I'll miss the functionality on devices that max out with Android less than version 8 (and thus can't use SD Maid SE)... but it will be nice to have it on newer devices.

BTW, if you want to double the sales of SD Maid SE, perhaps call it SD Maid SX.  If Freud was right, people will see the letter 'E' whether or not it is present. ;)
