### ISSUE TITLE
AppCleaner faster(?) alternative

### ISSUE THREAD

**Issue by bedroomcult** [d4rken-org/sdmaid#5876]
So, AppCleaner is a really good feature that I use almost daily. Without root access, it only depends on Accessibility Service - which take quite some time to completely perform the task.

Though, one thing that comes to my mind is SDMaid could execute an **adb command**
`shell pm trim-caches 999999999`

However to perform that command WITHOUT root, SDMaid would request an **ADB WiFi** permission. (Though you have to connect it through USB Cable upon reboots.)

I've been testing it on Tasker and Termux (w/ Shizuku), and I found it works well clearing caches in my case. And also, it works real fast.

**Comment by bedroomcult** [comment]
Well, it can be executed in any terminal app that has adb access, including Tasker.  But, it is indeed a good workaround to unrooted users.

**Comment by bedroomcult** [comment]
If It also can work via Shizuku's rish, the shell will remain in access without needing an ADB access confirmation to proceed. Thus, scheduled cleaning will work perfectly since typical unrooted Accessibility option requires us to unlock the screen.

**Comment by d4rken** [comment]
Supporting this is out of scope, just too much work to integrate into the current code.

I'm working on a "SD Maid 2" where I would reconsider this.

**Comment by d4rken** [comment]
Available in SD Maid SE if Shizuku is set up.
