### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/th.jpeg (FP)

### ISSUE THREAD

**Issue by Katymartin82** [d4rken-org/sdmaid#5892]
### Target
Target: `/storage/emulated/0/Download/th.jpeg`
Prefix-free: `Download/th.jpeg`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Current owners
Appname: `Android System`
Packagename: `android`
Version: `12 (31)`

~~Appname: `Downloads`~~
~~Packagename: `com.android.providers.downloads.ui`~~
~~Version: `12 (31)`~~

Appname: `Download Manager`
Packagename: `com.android.providers.downloads`
Version: `12 (31)`

### SD Maid
Version: `5.5.7 (50507)`

### Device
Fingerprint: `motorola/ellis_a/ellis:12/S3RHS32.20-42-10-4-1-1/2cb3d:user/release-keys`

**Comment by TheEthicalApproach2** [comment]
Please let me know if there are any pull requests finalized with repositories available.  

Sincerely,

TheEthicalApproach2
