### ISSUE TITLE
Bug: Ошибка в Appcleaner

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#5936]
### What happened?
Сделал поиск дубликатов, в одном пункте не отображается текст. Для примера скриншот с альбомной ориентацией, на котором текст виден.

### What did you expect to happen?
Текст должен отображаться.           

### How can I reproduce the issue?
Скорее всего создать файлы с такими же именами в таких же папках и выполнить поиск дубликатов.

### Comments
![IMG_20230126_083514](https://user-images.githubusercontent.com/60130882/214766346-38f6fb1f-d558-44bb-aca4-add7c0c7217a.jpg)
![IMG_20230126_083548](https://user-images.githubusercontent.com/60130882/214766356-298b3593-ff6e-4359-9f8f-26354feda6ce.jpg)

### SD Maid
Version: `5.5.8 (50508)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Redmi/dandelion_ru/dandelion:10/QP1A.190711.020/V12.0.17.0.QCDRUXM:user/release-keys`

**Comment by d4rken** [comment]
Fixed in v5.5.10
