### ISSUE TITLE
Shan234

### ISSUE THREAD

**Issue by phothargbk** [d4rken-org/sdmaid#5959]

**Comment by DragenJ** [comment]
IzhellaCold35°.  Ryd bksrta,asholes fkd it up! Need quiet 2:(0): calm

**Comment by DragenJ** [comment]
IwillcreateprayR4 U.  Was that why commotion @ dads! Need help fkRs stay
Out of hse!

**Comment by DragenJ** [comment]
My bad were replys thought sent straight to darken!  Am using new equipment.  But gets modded without my knowledge or consent.  When I start getting nasty grams from Google, or device Manu(LG,Samsung etc.)that's when I look deeper...is already to late. 7Isdeadman!
