### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android (FP)

### ISSUE THREAD

**Issue by Cesardfb** [d4rken-org/sdmaid#5960]
### Target
Target: `/storage/emulated/0/Android`
Prefix-free: `Android`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Administrador de Almacenamiento`
Packagename: `com.android.storagemanager`
Version: `8.1.0 (27)`

### Current owners
~~Appname: `Sistema Android`~~
~~Packagename: `android`~~
~~Version: `8.1.0 (27)`~~

### SD Maid
Version: `5.5.8 (50508)`

### Device
Fingerprint: `BLECK/BE_se/BE_se:8.1.0/O11019/1535867887:user/release-keys`

**Comment by DragenJ** [comment]
NtsureboutRyi,he benwatchn0ut4mE.didntKno. inC-LA.2tyRd.words
***@***.*** kan call

**Comment by DragenJ** [comment]
AmkonfsedNcld0nbik?RU

**Comment by DragenJ** [comment]
So am finding out what the case is.  You all will not like it. For now keep to myself.   Feel free to take a look!  Mostly I c way to much bad shit intent of good work. But has been twisted iz ?5o been up my ass.
