### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/Magisk(com.topjohnwu.magisk)-25.2(25200)-base.apk (FP)

### ISSUE THREAD

**Issue by Mjomb2** [d4rken-org/sdmaid#5966]
### Target
Target: `/storage/emulated/0/Download/Magisk(com.topjohnwu.magisk)-25.2(25200)-base.apk`
Prefix-free: `Download/Magisk(com.topjohnwu.magisk)-25.2(25200)-base.apk`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Official TWRP App`
Packagename: `me.twrp.twrpapp`
Version: `1.22 (35)`

Appname: `TWRP UPDATE`
Packagename: `com.installing.twrpupdate`
Version: `1.0 (1)`

### Current owners
Appname: `النظام`
Packagename: `android`
Version: `10 (29)`

Appname: `التنزيلات`
Packagename: `com.android.providers.downloads.ui`
Version: `10 (29)`

Appname: `مدير التنزيل`
Packagename: `com.android.providers.downloads`
Version: `10 (29)`

### SD Maid
Version: `5.5.8 (50508)`

### Device
Fingerprint: `HUAWEI/MAR-LX1M/HWMAR:10/HUAWEIMAR-L21MEA/10.0.0.273C185:user/release-keys`

**Comment by DragenJ** [comment]
Bn crazy weird round her
