### ISSUE TITLE
Clutterreport: /storage/emulated/0/SysQS (new)

### ISSUE THREAD

**Issue by p0w3rfu11** [d4rken-org/sdmaid#5967]
### Target
Target: `/storage/emulated/0/SysQS`
Prefix-free: `SysQS`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Android Setup`
Packagename: `com.google.android.setupwizard`
Version: `233.456442225 (18080)`

### Current owners
None

### SD Maid
Version: `5.5.8 (50508)`

### Device
Fingerprint: `TCL/6102D_EEA/Cruze_Lite:11/RP1A.200720.011/MW2M:user/release-keys`

### Comment
`what's omg this file ...`

**Comment by DragenJ** [comment]
Oh my god! Is for files you just don't believe u seen or find

**Comment by Pil0tXia** [comment]
I met this folder today.
