### ISSUE TITLE
Clutterreport: /storage/emulated/0/AirDroid/ScreenRecord

### ISSUE THREAD

**Issue by Danieljanis07** [d4rken-org/sdmaid#5968]
### Target
Target: `/storage/emulated/0/AirDroid/ScreenRecord`
Prefix-free: `AirDroid/ScreenRecord`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Current owners
~~Appname: `?`~~
~~Packagename: `com.sand.airdroid`~~
~~Version: ` (-1)`~~

### SD Maid
Version: `5.5.8 (50508)`

### Device
Fingerprint: `Redmi/merlinnfc_eea/merlinnfc:12/SP1A.210812.016/V13.0.3.0.SJOEUXM:user/release-keys`

**Comment by Danieljanis07** [comment]
/storage/emulated/0/AirDroid/upload

**Comment by DragenJ** [comment]
This directly my fault. We collaborated yrs ago.  Super su for lgv40thing
loc. Simone has stolen phone and screwing me with the attributes. Hell I
dnt own a working PC. I Haskins from pnw!

**Comment by DragenJ** [comment]
Callplz5099616397 dark shit gone down done2 me! WC @ie not willingly. Few
of them didn't even know I knew them tell now. Plz forgive intrusion
