### ISSUE TITLE
Bug: App Cleaner Gets Stuck On One Random Application

### ISSUE THREAD

**Issue by nikdotgit** [d4rken-org/sdmaid#5978]
### What happened?
Enters 'cache clearing loop' when using App Cleaner; doesn't appear to be app biased

### What did you expect to happen?
I expected the accessibility service to scan and delete the application cache in one pass

### How can I reproduce the issue?
Its difficult to pinpoint, however it seems to happen more often when I have animations on in addition to an incoming pop-up on screen notification.

### Comments
your cholesterol, fatty
### SD Maid
Version: `5.5.9 (50509)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `google/cheetah/cheetah:13/TQ1A.230205.001.D2/9471403:user/release-keys`

**Comment by d4rken** [comment]
> Its difficult to pinpoint, however it seems to happen more often when I have animations on in addition to an incoming pop-up on screen notification.

That would be the cause, this can't be fixed, if someone prevents SD Maid from interacting with the screen SD Maid will retry and then then start skipping app.
