### ISSUE TITLE
Bug: When I use storage analyzer, the app crashed

### ISSUE THREAD

**Issue by halloth** [d4rken-org/sdmaid#5988]
### What happened?
I used storage analyzer to analyze my data partition. When the number of files reached a certain number, about 1.2 million, the application would become unresponsive and crash after a period of time.

### What did you expect to happen?
The app works fine and lists all files.

### How can I reproduce the issue?
Well, I guess you can create lots of files and use the app on them.  By the way, the total number of files I have is around 1.6 million.

### SD Maid
Version: `5.5.9 (50509)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `OnePlus/OnePlus8T_CH/OnePlus8T:11/RP1A.201005.001/2103232100:user/release-keys`

**Comment by d4rken** [comment]
SD Maid is likely running out of memory. There is no easy fix for this except a complete rewrite of the feature to try to use less memory.

**Comment by d4rken** [comment]
SD Maid SE has a more lightweight storage analyzer where data is split up between areas. You can try that.

https://github.com/d4rken-org/sdmaid-se/pulls?q=is%3Apr+label%3A%22c%3A+StorageAnalyzer%22+is%3Aclosed
