### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.mojang.minecraftpe (FP)

### ISSUE THREAD

**Issue by faka642** [d4rken-org/sdmaid#6000]
### Target
Target: `/storage/emulated/0/Android/data/com.mojang.minecraftpe`
Prefix-free: `com.mojang.minecraftpe`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
~~Appname: `?`~~
~~Packagename: `com.mojang.minecraftpe`~~
~~Version: ` (-1)`~~

### SD Maid
Version: `5.5.9 (50509)`

### Device
Fingerprint: `motorola/cyprus64/cyprus64:11/ROQS31.166-72-5/31d77:user/release-keys`

**Comment by dragonGod97677** [comment]
Closing this issue

Reason for closing: invalid suggested removing of current owner/s
