### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/minecraft-1_18_32_02.apk (FP)

### ISSUE THREAD

**Issue by Kawttffyygff** [d4rken-org/sdmaid#6001]
### Target
Target: `/storage/emulated/0/Download/minecraft-1_18_32_02.apk`
Prefix-free: `Download/minecraft-1_18_32_02.apk`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Current owners
Appname: `Sistema Android`
Packagename: `android`
Version: `12 (31)`

Appname: `Downloads`
Packagename: `com.android.providers.downloads.ui`
Version: `12 (31)`

~~Appname: `Gerenciador de downloads`~~
~~Packagename: `com.android.providers.downloads`~~
~~Version: `12 (31)`~~

### SD Maid
Version: `5.5.9 (50509)`

### Device
Fingerprint: `samsung/a12ub/a12:12/SP1A.210812.016/A125MUBS4CWB2:user/release-keys`

**Comment by DragenJ** [comment]
Ya I confused 2

**Comment by dragonGod97677** [comment]
Closing this issue

Reason for closing: invalid suggested removing of current owner/s
