### ISSUE TITLE
Clutterreport: /storage/emulated/0/.polarisOffice6 (new)

### ISSUE THREAD

**Issue by Andrei746** [d4rken-org/sdmaid#6013]
### Target
Target: `/storage/emulated/0/.polarisOffice6`
Prefix-free: `.polarisOffice6`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Polaris Office`
Packagename: `com.infraware.office.link`
Version: `9.0.4 (162)`

### Current owners
None

### SD Maid
Version: `5.5.9 (50509)`

**Comment by phothargbk** [comment]
Yshsjsowowoissusushsh111111111
Vdhdjskskksksjwj1111111
