### ISSUE TITLE
Question: System Cleaner - Empty directories?

### ISSUE THREAD

**Issue by 0pLuS0** [d4rken-org/sdmaid#6020]
Hello,

I have the Pro version, but it's been a long time since I've used sdmaid.

I remember when I started using it, if I didn't check an empty direc option, it would delete the empty directories in my user direc.

I want to keep this directory structure and all these directories Androids creates.

![user_direcs](https://user-images.githubusercontent.com/36190223/232952478-3da12a39-e00d-4d06-a84e-7152c7078a6f.jpg)

If I don't want empty directories deleted, then I need to toggle off System Cleaner - Empty directories, and under Settings - Explorer - Save directory structure?

THANKS

**Comment by d4rken** [comment]
Disabling the empty directories filter in SystemCleaner should be enough.
The explorer feature is unrelated.

**Comment by 0pLuS0** [comment]
Ok thanks...

**Comment by Jung47** [comment]
> สวัสดี,
> 
> ฉันมีรุ่น Pro แต่นานมากแล้วที่ฉันใช้ sdmaid
> 
> ฉันจำได้ว่าตอนที่เริ่มใช้ ถ้าฉันไม่เลือกตัวเลือกไดเรกว่าง มันจะลบไดเร็กทอรีว่างในไดเร็กต์ผู้ใช้ของฉัน
> 
> ฉันต้องการเก็บโครงสร้างไดเร็กทอรีนี้และไดเร็กทอรีทั้งหมดที่ Android สร้างขึ้น
> 
> ![user_direcs](https://user-images.githubusercontent.com/36190223/232952478-3da12a39-e00d-4d06-a84e-7152c7078a6f.jpg)
> 
> ถ้าฉันไม่ต้องการให้ลบไดเร็กทอรีว่าง ฉันต้องปิดระบบทำความสะอาด - ไดเร็กทอรีว่าง และภายใต้การตั้งค่า - Explorer - บันทึกโครงสร้างไดเร็กทอรี
> 
> ขอบคุณ
