### ISSUE TITLE
Upgrading to the current version of SD Maid Pro is not possible

### ISSUE THREAD

**Issue by DiDi-jpg** [d4rken-org/sdmaid#6037]
Sorry, but I use a translator. I hope you will understand me.

Good afternoon!

After the restrictions were imposed, I can neither update SD Maid Pro nor stop it, but I purchased it on Google Play. I am attaching screenshots:
![image](https://user-images.githubusercontent.com/66851854/236486483-aab241e9-ae6b-4e25-a269-fb1a9927ffbf.png)
![image](https://user-images.githubusercontent.com/66851854/236486738-8edc929d-c7c0-49fa-9f37-eb5f2c5f31ed.png)
![image](https://user-images.githubusercontent.com/66851854/236487052-86d93efb-8073-4e76-8bf2-bec1f62c65db.png)
![image](https://user-images.githubusercontent.com/66851854/236488496-89946545-abeb-4f57-bfdd-0065eb8f4efd.png)

I enter my email address with which I purchased the Pro version, but it giv
es an error. I can't even make a new purchase on your site

Do I have any other options to upgrade to the current version?

**Comment by d4rken** [comment]
I have no workarounds for the sanctions. You can use SD Maid SE though:
https://github.com/d4rken-org/sdmaid-se#download
