### ISSUE TITLE
Appcleaner not working on MIUI 11 android 7

### ISSUE THREAD

**Issue by NoiseBox20** [d4rken-org/sdmaid#6046]
Appcleaner not deleting any app cache, keep looping at same app for a few second.

**To Reproduce**
1. Go to appcleaner
2. Click on scan
3. Then delete
4. sd maid keep looping on the same app for a few second.

**Expected behavior**
appcleaner delete apps cache.

**Debug log**
[sdmaid_logfile_1683899891112.txt.zip](https://github.com/d4rken-org/sdmaid/files/11464917/sdmaid_logfile_1683899891112.txt.zip)

**Smartphone (please complete the following information):**
 - Device: Redmi Note 4x
 - OS: Android 7

**Comment by d4rken** [comment]
Please do not enable the accessibility service debug option.
Just record a debug log and let SD Maid loop on the app for a bit, then stop and post the log.

**Comment by NoiseBox20** [comment]
[sdmaid_logfile_1683901252531.txt.zip](https://github.com/d4rken-org/sdmaid/files/11465019/sdmaid_logfile_1683901252531.txt.zip)

**Comment by luxcalor** [comment]
The same for MIUI 14 A13 redmi note 10 pro. Just loops on an app with app settings screen blinking in background everytime I try to delete any apps cache.

**Comment by d4rken** [comment]
> The same for MIUI 14 A13 redmi note 10 pro. Just loops on an app with app settings screen blinking in background everytime I try to delete any apps cache.

If you have a different ROM and Android version then it's likely a different issue. Please open a new issue and provide a debug log (also try SD Maid 2)

**Comment by d4rken** [comment]
Hm the issue is not a screen matching problem, but that the system does not emit any UI events. Try rebooting.

Not something I can fix :frowning_face:.
