### ISSUE TITLE
AppCleaner doesn't work on Android 14

### ISSUE THREAD

**Issue by Puzzak** [d4rken-org/sdmaid#6055]
On Android 14 they have changed app menus in settings, so SDMaid service can't find and clean apps anymore.

**Comment by Puzzak** [comment]
Example: https://youtu.be/TfSzFnvYexY

**Comment by d4rken** [comment]
Android 14 support is out of scope for SD Maid 1.
You can use SD Maid 2 for this:
https://github.com/d4rken-org/sdmaid-se
