### ISSUE TITLE
Question about folders

### ISSUE THREAD

**Issue by Ahplla** [d4rken-org/sdmaid#6069]
**Describe the bug**
No matter what I do, SDMaid always only deletes the contents of the folders and not the folders themselves. What am I doing wrong and how to fix it?

**To Reproduce**
I go to the file explorer, select all the folders that must be included in the system cleanup. Then I name and save the filter and later activate it. But after all SDMaid just deletes the files inside.

**Expected behavior**
I need selected folders to be deleted for good

**Screenshots**
`{
    "color": "#03a9f4",
    "description": "7 itens @ /data/data/just_an_app",
    "identifier": "xxxxxxxxx.scuf.sdm",
    "label": "cotd/data pastas",
    "locations": [
        "PRIVATE_DATA"
    ],
    "mainPath": [
        "/data/data/just_an_app/app_textures/",
        "/data/data/just_an_app/app_webview/",
        "/data/data/just_an_app/cache/",
        "/data/data/just_an_app/code_cache/",
        "/data/data/just_an_app/databases/",
        "/data/data/just_an_app/files/",
        "/data/data/just_an_app/no_backup/"
    ],
    "version": 4
}`

**Comment by Ahplla** [comment]
anyone?

**Comment by d4rken** [comment]
Remove the trailing from paths to match `/`

Or create a filter for the parent path and add the folder name as extra filter condition

The path `/data/data/just_an_app/app_textures/` matches `/data/data/just_an_app/app_textures/some_file` but not `/data/data/just_an_app/app_textures`
