### ISSUE TITLE
System Cleaner: User criteria = hidden folder (.folders) CANNOT be read/scanned

### ISSUE THREAD

**Issue by MaccabeeY** [d4rken-org/sdmaid#6084]
**Describe the bug**
Within the "System Cleaner" in "config'ing" (i.e. gear icon), when one creates a "User" criteria in the User tab and a hidden (i.e. a dot folder ".folder" for example) is entered as either a base folder and/or a "Path Includes", when the System Cleaner scan is run, it DOES NOT/NEVER list as a cleanable item, that User Criteria hidden (dot) folder. 

**To Reproduce**
1. Go to 'System Cleaner'
2. tap on the 'gear icon'
3. tap on "User"
4. tap on +
6. Scroll down to '.Base Path'
7. tap on "Add"
8. type the CORRECT path to any hidden (dot) folder, i.e.  "/storage/emulated/0/DCIM/.thumbnails/"
9. make sure that folder is not empty, i.e. has .jpg file in it
10. tap the "save icon".
11. tap the toggle to ON position
12. See error

**Expected behavior**
When SystemCleaner completes scanning, the User criteria should be listed in the "to clean" list.

**Smartphone (please complete the following information):**
 - Device: all our phones
 - OS: all our Android versions

**Comment by d4rken** [comment]
I can't reproduce this on a Pixel5 @ Android 13 with SD Maid v5.5.10.

Are you certain you typed the path correctly? No extra spaces and that SD Maid does access the path that way? If SD Maid accesses storage using the SAF, then you can't type a normal path for matching.

[2023-07-22 10 06 59](https://github.com/d4rken-org/sdmaid/assets/1439229/702d7a50-d18b-4327-8f24-b70599dd5a03)

[2023-07-22 10 06 53](https://github.com/d4rken-org/sdmaid/assets/1439229/feab360d-60f7-4323-a19f-03f244373c50)

**Comment by MaccabeeY** [comment]
I think you may be in the "wrong" place of SDMaid.
I've attached "step-by-step" pics that may better illustrate the problem.

![1](https://github.com/d4rken-org/sdmaid/assets/4692331/00aa5f01-139d-4961-83d9-62093d8ab6c1)
![2](https://github.com/d4rken-org/sdmaid/assets/4692331/bbacfa06-2ee0-42a5-b5b7-c59459f771cb)
![3](https://github.com/d4rken-org/sdmaid/assets/4692331/2c53eb4c-9c49-4796-bf71-9ff79fdf1a26)
![4](https://github.com/d4rken-org/sdmaid/assets/4692331/6f50a71b-cd46-4e4a-a555-06af5573bae8)
![5](https://github.com/d4rken-org/sdmaid/assets/4692331/4049c810-8490-48d4-9005-44973ae83262)
![6](https://github.com/d4rken-org/sdmaid/assets/4692331/ff0b453c-c8eb-4b54-8be2-9c6eb3e0fbbd)
![7](https://github.com/d4rken-org/sdmaid/assets/4692331/a9e0ae9f-d329-4b51-8a97-8af48140ce4f)
![8](https://github.com/d4rken-org/sdmaid/assets/4692331/3550c51f-085f-443e-a963-4df67fb80ad9)
![9](https://github.com/d4rken-org/sdmaid/assets/4692331/085bdf64-fa01-4266-a6e2-f396957d54c5)

**Comment by d4rken** [comment]
Please record a debug log.
I can't reproduce this.

[Screenshot_20230723-191315.png](https://github.com/d4rken-org/sdmaid/assets/1439229/0cb3c783-71d7-47ed-91ea-b224291d8c09)

[Screenshot_20230723-191324.png](https://github.com/d4rken-org/sdmaid/assets/1439229/5de8acc6-1df6-4445-8026-faa66a4ac2e2)

**Comment by MaccabeeY** [comment]
Where in SDMaid settings do I turn on the SDMaid debug loggoing?

**Comment by d4rken** [comment]
Sorry for my late response, the whole Google thing :roll_eyes:...

Long press settings, there is a debug menu, also see:
https://github.com/d4rken-org/sdmaid/wiki/Reporting-a-bug#debug-log
