### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/.nomedia (FP)

### ISSUE THREAD

**Issue by Gigasmi** [d4rken-org/sdmaid#6090]
### Target
Target: `/storage/emulated/0/Android/data/.nomedia`
Prefix-free: `.nomedia`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `FILE`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Android S Easter Egg`
Packagename: `com.android.egg`
Version: `1.0 (12)`

### Current owners
~~Appname: `Система Android`~~
~~Packagename: `android`~~
~~Version: `12 (31)`~~

### SD Maid
Version: `5.5.9 (50509)`

### Device
Fingerprint: `realme/RMX3690RU/RE58AB:12/SP1A.210812.016/202307071900:user/release-keys`

**Comment by Nuy06155** [comment]
เข้าใช้งานไม่ได้เลย เข้า gibhub ก็ไม่ได้

nuy06155

ในวันที่ พฤ. 27 ก.ค. 2023 08:55 น. Gigasmi ***@***.***>
เขียนว่า:
