### ISSUE TITLE
Bug: App cleaner not cleaning

### ISSUE THREAD

**Issue by B10Reaper** [d4rken-org/sdmaid#6099]
### What happened?
Ran the scan, went to clean as usual, but it just keeps saying "0b deleted" after it found nearly 4gb.

### What did you expect to happen?
Normally it deletes the files it finds

### How can I reproduce the issue?
Scan, press clean, clean displays but doesn't clean

### Comments
Please clean. The app has the permissions it needs according to the settings.
### SD Maid
Version: `5.5.10 (50510)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/star2qltecs/star2qltecs:10/QP1A.190711.020/G965WVLS9FVA1:user/release-keys`

**Comment by d4rken** [comment]
Sounds like the accessibility service not working, is it setup?

**Comment by d4rken** [comment]
Also try out SD Maid 2, since you have Android 10. Could perform better for you.
