### ISSUE TITLE
Gekaufte Apps aus dem Play-Store verschwunden 

### ISSUE THREAD

**Issue by SSlz** [d4rken-org/sdmaid#6105]
Ich habe die beiden Apps "SD Maid" + "Unlock", "SD Maid SE" und "Octi Pro" gekauft gehabt. Diese sind im Store nicht mehr zu finden.

Was ist geschehen?

Was ist mit dem investierten Geld?

Ich hoffe es klärt sich.

Mit freundlichen Grüßen

S.Schulz

==========

I had bought the two apps "SD Maid" + "Unlock", "SD Maid SE" and "Octi Pro". These can no longer be found in the store.

What happened?

What about the money invested?

I hope it clears up.

Yours sincerely,

S.Schulz

**Comment by d4rken** [comment]
Dup of #6098

Last week some app scanning automatism went of the rails at Google Play and decided  SD Maid is malware. Google instantly terminated my developer account.

This prevents any purchase checks from working. If it's not reinstated then your related Google Play purchases are lost.

I'm currently appealing. Let's stay optimistic.

**Comment by SSlz** [comment]
What's next for the app? Is there a plan B?What about the users who paid money?

**Comment by SSlz** [comment]
What's next for the app?

Is there a plan B?

What about the users who paid money?
