### ISSUE TITLE
SD maid removed from the Google Play store 

### ISSUE THREAD

**Issue by Rehaeel** [d4rken-org/sdmaid#6106]
**Describe the bug**
Neither I can download or reuse the SD Maid application nor Pro version that I paid for. 

**To Reproduce**
1. Go to Google Play Store 
2. Find the Pro version: [SD Maid Pro](https://play.google.com/store/apps/details?id=eu.thedarken.sdm.unlocker) (eu.thedarken.sdm.unlocker)

**Expected behavior**
I want to have ability to reinstall the application

**Smartphone (please complete the following information):**
 - Asus Zenfone 9 
 - OS: Android

**Comment by d4rken** [comment]
See #6098
