### ISSUE TITLE
Stupid playstore

### ISSUE THREAD

**Issue by Poeticdreamer** [d4rken-org/sdmaid#6117]
I love your app I actually had sdmaid pro used all the time had to get me a new phone and went to download it and realized it wasn't there so sad. And don't really know how to go about doing this on here

**Comment by COUPON4Vitamins** [comment]
✨IT'S BACK ✨

**Comment by d4rken** [comment]
It's back :partying_face: 

If you are left without SD Maid again due to Google Play shenanigans, then you can grab SD Maid 2 from here: https://github.com/d4rken-org/sdmaid-se/releases
