### ISSUE TITLE
Bug: SD MAID can't find /storage/C750-171C/Android/data and /storage/emulated/0/Android/data

### ISSUE THREAD

**Issue by COUPON4Vitamins** [d4rken-org/sdmaid#6141]
### What happened?
                No app doesn't close it simply doesn't find or navigate to Android Data
                
                ### What did you expect to happen?
                Navigate and select Android Data
                
                ### How can I reproduce the issue?
                Public storage
A secondary storage was detected. Grant SD Maid access by selecting its location.
/storage/C750-171C/Android/data
125 GB free
/storage/emulated/0/Android/data
98 GB free
The system window does not always open with the correct path preselected, you may need to navigate to it.
SKIP
Unsuccessful
                
                ### Comments
Why can't SD Maid not find Android Data on this device. It doesn't navigate to Android Data.
### SD Maid
Version: `5.6.1 (50601)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `WOZIFAN/W10_US/W10_US:12/SP1A.210812.016/20230216SMR2:user/release-keys`

**Comment by adithyaappu** [comment]
Facing the same issue with SD Maid and SD Maid SE. Looks like scoped storage is interfering. My android version 12, and I think this issue started showing up after September 2023 security update of android

**Comment by adithyaappu** [comment]
Adding more info.

Storage analyser in SD Maid is able to open the location. But when selected to allow access, nothing happens. 

![Screenshot_20231010-081611](https://github.com/d4rken-org/sdmaid/assets/37062841/59f88cb9-e533-440f-b9e6-874dc1046caf)

**Comment by d4rken** [comment]
This is related to an update of the "files" app by Google.
They restricted it further and removed a workaround that SD Maid previously used.

You can temporarily downgrade to grant access, see:
https://github.com/d4rken-org/sdmaid-se/wiki/Setup#saf-androiddataobb-access

**Comment by COUPON4Vitamins** [comment]
Worked thanks
