### ISSUE TITLE
Get permissions fore new firesticks via adb

### ISSUE THREAD

**Issue by jydhthrshrhty** [d4rken-org/sdmaid#6169]
New firesticks need permissions we can’t grant.

Any plan to add an option we can grant those permissions via a one click adb commands ?

thank you

**Comment by d4rken** [comment]
SD Maid 1 is in maintenance mode, try SD Maid 2, if it's not possible there, I can look into it.

https://github.com/d4rken-org/sdmaid-se

**Comment by jydhthrshrhty** [comment]
@d4rken  Not possible with both of your app. Tryed
