### ISSUE TITLE
SD Maid has stopped while scanning SystemCleaner

### ISSUE THREAD

**Issue by esnon** [d4rken-org/sdmaid#6175]
**Describe the bug**
While waiting for scan on 'SystemCleaner', even no result yet, suddenly the app stopped. I have already tried "force stop", reboot device, and reinstall app, but still occurred.

**Debug log**
[sdmaid_logfile_1700177030358.txt.zip](https://github.com/d4rken-org/sdmaid/files/13385180/sdmaid_logfile_1700177030358.txt.zip)

**Smartphone (please complete the following information):**
 - Device: Ulefone Power Armor 13
 - OS: Android 12
 - State: Unrooted
 - SD Maid v5.6.2
 - Unlocker v5.6.1

**Comment by d4rken** [comment]
The log doesn't contain a stacktrace of the crash.

Are you able to grab one via logcat/adb or another app?

You can also check if SD Maid SE crashes too.

**Comment by esnon** [comment]
[sdmaid.txt](https://github.com/d4rken-org/sdmaid/files/13491118/sdmaid.txt)
i hope this true, never touch logcat before
last one from several
11-29 01:10:37.037 15054 15212 E AndroidRuntime: FATAL EXCEPTION: SDM:Thread:1
11-29 01:10:37.037 15054 15212 E AndroidRuntime: Process: eu.thedarken.sdm, PID: 15054
11-29 01:10:37.037 15054 15212 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 160 byte allocation with 5137536 free bytes and 5017KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
11-29 01:10:37.037 15054 15212 E AndroidRuntime: 	at android.net.Uri$PathPart.appendEncodedSegment(Uri.java:2248)
11-29 01:10:37.037 15054 15212 E AndroidRuntime: 	at android.net.Uri$PathPart.appendDecodedSegment(Uri.java:2258)
11-29 01:10:37.037 15054 15212 E AndroidRuntime: 	at android.net.Uri$Builder.appendPath(Uri.java:1475)
11-29 01:10:37.037 15054 15212 E AndroidRuntime: 	at android.provider.DocumentsContract.buildDocumentUriUsingTree(DocumentsContract.java:1012)
11-29 01:10:37.037 15054 15212 E AndroidRuntime: 	at a1.z.N(Unknown Source:205)
11-29 01:10:37.037 15054 15212 E AndroidRuntime: 	at tb.a$b.a(SourceFile:20)
11-29 01:10:37.037 15054 15212 E AndroidRuntime: 	at ed.e.getValue(Unknown Source:20)
11-29 01:10:37.037 15054 15212 E AndroidRuntime: 	at tb.a.isEmpty(Unknown Source:2)
11-29 01:10:37.037 15054 15212 E AndroidRuntime: 	at la.d$a.a(SourceFile:210)
11-29 01:10:37.037 15054 15212 E AndroidRuntime: 	at eu.thedarken.sdm.systemcleaner.core.filter.b.match(Unknown Source:10)
11-29 01:10:37.037 15054 15212 E AndroidRuntime: 	at h3.j.a(SourceFile:361)
11-29 01:10:37.037 15054 15212 E AndroidRuntime: 	at tb.b.a(SourceFile:162)
11-29 01:10:37.037 15054 15212 E AndroidRuntime: 	at tb.b.n(SourceFile:70)
11-29 01:10:37.037 15054 15212 E AndroidRuntime: 	at ob.a.n(Unknown Source:7)
11-29 01:10:37.037 15054 15212 E AndroidRuntime: 	at mb.d0.n(SourceFile:80)
11-29 01:10:37.037 15054 15212 E AndroidRuntime: 	at ja.b.M(SourceFile:659)
11-29 01:10:37.037 15054 15212 E AndroidRuntime: 	at i8.a.I(SourceFile:5)
11-29 01:10:37.037 15054 15212 E AndroidRuntime: 	at ja.b.I(SourceFile:39)
11-29 01:10:37.037 15054 15212 E AndroidRuntime: 	at i8.e$b.run(SourceFile:38)
11-29 01:10:37.037 15054 15212 E AndroidRuntime: 	at h3.d.run(SourceFile:43)
11-29 01:10:37.037 15054 15212 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
11-29 01:10:37.037 15054 15212 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
11-29 01:10:37.037 15054 15212 E AndroidRuntime: 	at h3.d.run(SourceFile:130)
11-29 01:10:37.037 15054 15212 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)

**Comment by esnon** [comment]
![sdmaidse](https://github.com/d4rken-org/sdmaid/assets/95175440/6e2c51b7-c760-42ff-973e-799cee7be7f3)

click cancel not work.
just stuck there, after use *ls* on that file. i thought it was a big file, apparently not
*total 44336
drwxrws--- 5 u0_a125 ext_data_rw     4096 2023-11-12 08:25 .
drwxrws--- 3 u0_a125 ext_data_rw     4096 2022-12-01 17:34 ..
-rw-rw---- 1 u0_a125 ext_data_rw        2 2023-06-13 07:15 .dog_watch
-rw-rw---- 1 u0_a125 ext_data_rw       20 2023-06-13 07:15 .srcMid
drwxrws--- 2 u0_a125 ext_data_rw 45371392 2023-11-29 00:59 crash
drwxrws--- 2 u0_a125 ext_data_rw     4096 2023-11-12 08:25 fota
drwxrws--- 2 u0_a125 ext_data_rw     4096 2023-11-12 08:25 gotronfota*

inside *crash* directory, there were over 700k crash file, each of them is 5.6kB
i don't know it related or not. but explorer app unable to open that crash dir. it will "External Storage has stopped"

then, this appear one time:
![sdmaidse_readexcept](https://github.com/d4rken-org/sdmaid/assets/95175440/a44b0408-943a-4137-89dd-2d111bb40953)

logcat - [sdmaidse.txt](https://github.com/d4rken-org/sdmaid/files/13494853/sdmaidse.txt)

**Comment by d4rken** [comment]
This is an out of memory error because of the amount of files. This will not be fixed in SD Maid 1. Not sure if this can be fixed as this just are natural limits we are running into.

I've made a ticket to investigate further though:

https://github.com/d4rken-org/sdmaid-se/issues/837

**Comment by esnon** [comment]
thank you, i respect it
