### ISSUE TITLE
S-20 + plus 5G ( Samsung Galaxy) Data connectivity

### ISSUE THREAD

**Issue by marietorres655** [d4rken-org/sdmaid#6190]
S-20 + plus 5G ( Samsung Galaxy) Data connectivity 
loss after Android 13 , security  patches.

_Originally posted by @dusty1977 in https://github.com/d4rken-org/sdmaid/issues/5989#issuecomment-1515911157_

**Comment by dragonGod97677** [comment]
Dont make a new issue based on comment unless said so
