### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/obb (FP)

### ISSUE THREAD

**Issue by phothargbk** [d4rken-org/sdmaid#6193]
### Target
Target: `/storage/emulated/0/Android/obb`
Prefix-free: `Android/obb`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `ADM`
Packagename: `com.dv.adm`
Version: `14.0.25 (140025)`

### Current owners
Appname: `Android System`
Packagename: `android`
Version: `12 (31)`

### SD Maid
Version: `5.6.3 (50603)`

### Device
Fingerprint: `samsung/d2xks/d2x:12/SP1A.210812.016/N976NKSU2HWH5:user/release-keys`

### Comment
`munamayloe`

**Comment by phothargbk** [comment]
https://egmbrqbrfg.fvekhjtfjl.net/gs2c/html5Game.do?jackpotid=0&gname=Gates%20of%20Olympus&extGame=1&ext=0&cb_target=exist_tab&symbol=vs20olympgate&jurisdictionID=99&lobbyUrl=https%3A%2F%2Fapi-2104.ppgames.net%2Fgame%2FPRAGMATIC&minilobby=false&mgckey=AUTHTOKEN@6a0f9042518d221d1cff3ce1826202edbdeb20ca5551484747468b2231f861dc~stylename@btnxs_btnexus~SESSION@a7454f12-0f3b-47a8-8253-4c2d98860b1b~SN@d3956701&tabName=

**Comment by dragonGod97677** [comment]
Closing this issue

Reason for closing: invalid suggestion of new owners
