### ISSUE TITLE
Xiaomi HyperOs: accessibility service not working

### ISSUE THREAD

**Issue by mxr576** [d4rken-org/sdmaid#6197]
After the Xiaomi HyperOs update the accessibility service stopped working. Even after a fresh reboot, if I start the app immediately, it is just not working.

![Screenshot_2024-01-11-08-18-15-334_com android settings](https://github.com/d4rken-org/sdmaid/assets/1755573/e2f25375-170d-48e3-8b62-476d243d2ac7)

**Comment by cerberus6666** [comment]
this is well known..hyperOS has recently released...darken needs to update it when he can

**Comment by mxr576** [comment]
Sure it is new, just wanted to be sure that the issue is tracked.

I was uncertain if #6191 about the same problem, the OS is different.

**Comment by d4rken** [comment]
HyperOS is Android 13/14+ and will not be supported by SD Maid 1, consider switching to [SD Maid 2/SE](https://github.com/d4rken-org/sdmaid-se). If it's not working there, provide a debug log and I'll fix it. Thanks.
