### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android (FP)

### ISSUE THREAD

**Issue by happyday98** [d4rken-org/sdmaid#6199]
### Target
Target: `/storage/emulated/0/Android`
Prefix-free: `Android`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Certificate Installer`
Packagename: `com.android.certinstaller`
Version: `12 (31)`

Appname: `CapitalDNA`
Packagename: `com.capitaldna.client`
Version: `4.0 (252)`

Appname: `Cell Broadcast Service`
Packagename: `com.android.cellbroadcastservice`
Version: `12 (31)`

### Current owners
Appname: `Android System`
Packagename: `android`
Version: `12 (31)`

### SD Maid
Version: `5.6.2 (50602)`

### Device
Fingerprint: `Maxwest/NITRO_N62/MX-NN62WW01:12/SP1A.210812.016/1685015924:user/release-keys`

### Comment
`GARY LAQUITA DENISE ™ AA.ATLAS AMERICA0907HOME HP2.`

**Comment by dragonGod97677** [comment]
Closing this issue

Reason for closing: invalid suggestion of new owners
