### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.miui.gallery/files/gallery_disk_cache/full_size/e4f2ff3d7b1f62fb82abe24b82668dd47e3712cc8202b81471cdeeec7ea2a05c.0 (FP)

### ISSUE THREAD

**Issue by Iamshubh07** [d4rken-org/sdmaid#6200]
### Target
Target: `/storage/emulated/0/Android/data/com.miui.gallery/files/gallery_disk_cache/full_size/e4f2ff3d7b1f62fb82abe24b82668dd47e3712cc8202b81471cdeeec7ea2a05c.0`
Prefix-free: `com.miui.gallery/files/gallery_disk_cache/full_size/e4f2ff3d7b1f62fb82abe24b82668dd47e3712cc8202b81471cdeeec7ea2a05c.0`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `FILE`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Bokeh`
Packagename: `com.miui.extraphoto`
Version: `1.0.0 (1)`

### Current owners
Appname: `Gallery`
Packagename: `com.miui.gallery`
Version: `3.5.4.16-global (403600)`

### SD Maid
Version: `5.6.3 (50603)`

### Device
Fingerprint: `Redmi/curtana/curtana:12/SKQ1.211019.001/V14.0.3.0.SJWINXM:user/release-keys`

**Comment by dragonGod97677** [comment]
It is already inside MIUI Gallery's Private Directory and the following app has nothing to do with that file

Appname: Bokeh
Packagename: com.miui.extraphoto
