### ISSUE TITLE
Apps

### ISSUE THREAD

**Issue by Goddesskylee** [d4rken-org/sdmaid#6203]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Androidf13** [comment]
[](url)https://github.com/d4rken-org/sdmaid/issues/6203#issue-2108654920

**Comment by Androidf13** [comment]
[CHANGELOG.md](https://github.com/d4rken-org/sdmaid/files/14158534/CHANGELOG.md)

**Comment by dragonGod97677** [comment]
Closing this now because no useful info found
