### ISSUE TITLE
New App Feature

### ISSUE THREAD

**Issue by JMViertel85** [d4rken-org/sdmaid#6219]
Can you please create a pro version for SD maid se that we can purchase without going through google play? I bought the pro version, but I don't use google play anymore. I'd also like a pro version that I can use that doesn't require an internet connection. I deny SD maid that permission. 

Thank you.

**Comment by d4rken** [comment]
SD Maid 2 is already available as a FOSS version without Google Play.

See https://github.com/d4rken-org/sdmaid-se
