### ISSUE TITLE
Bug: Very slow 

### ISSUE THREAD

**Issue by Stoffeltof** [d4rken-org/sdmaid#6222]
### What happened?
Very slow and 2files won't delete. 

### What did you expect to happen?
I expected that it would run the data and suggest to delete the useless data, and do it without stuttering over 2 apps, 13mb

### How can I reproduce the issue?
Where can I find a simple update or what do I have to do in developer settings. But I actually don't know much about it.

### SD Maid
Version: `5.6.3 (50603)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Xiaomi/gauguin_eea/gauguin:12/SKQ1.211006.001/V14.0.2.0.SJSEUXM:user/release-keys`

**Comment by d4rken** [comment]
Check SD Maid 2/SE, if it's reproducable there, I'll look into it.

https://github.com/d4rken-org/sdmaid-se
