### ISSUE TITLE
App cleaner no longer works on Xiaomi Hyper OS

### ISSUE THREAD

**Issue by RishavKum4r** [d4rken-org/sdmaid#6257]
**Describe the bug**
App cleaner doesn't work on Hyper OS. It keeps on trying to clear the cache.

**To Reproduce**
1. Go to QuickAccess
2. Click on Scan
3. Select Appcleaner menu and start

**Expected behavior**
It's supposed to initiate a cache cleanup of all applications on my device.

**Screenshots**

**Debug log**
Record a [debug log](https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log) while reproducing the problem and attach the zip file here.

**Smartphone (please complete the following information):**
 - Device: Mi 11x Pro
 - OS: HyperOS - Android 14

**Additional context**

**Comment by d4rken** [comment]
SD Maid 1 is not made for Android 14, try SD Maid 2.
