### ISSUE TITLE
Add a target directory where searcher will search for

### ISSUE THREAD

**Issue by ghost** [d4rken-org/sdmaid#682]
Currently the searcher searches through the entire storage. It would be great if I can restrict the search so that I can find files quickly especially when searching through contents.
Attaching a screenshot of aGrep app where target directories can be added which will then search only within it. Something similar can be done in searcher. Currently there is excludes only.
![screenshot_2017-01-08-19-03-48](https://cloud.githubusercontent.com/assets/1277952/21750299/10ea0264-d5d6-11e6-8f6d-2531aa8a7232.jpg)

**Comment by d4rken** [comment]
I already think the exclusion category `SEARCHER` is somewhat useless or at least doesn't make too much sense. A search is there to find everything...

So adding a search path option and maybe a "Does not contain" option, then remove the ability to use exclusions for the searcher?

**Comment by kadaj** [comment]
Yes, adding search path would do it. But you don't need to remove exclusions. These are two different usecases.

**Comment by ivanunderdog** [comment]
☺ thankyou
