### ISSUE TITLE
More time units for file ages in searches

### ISSUE THREAD

**Issue by KaMyKaSii** [d4rken-org/sdmaid#742]
Maybe a field where you select what kind of unit you want (minutes, hours, days, weeks, months...) and in the other you put the gross value. Preferably with the keyboard, no sliding. For both minimum and maximum age

**Comment by d4rken** [comment]
When does the current search option fail to be useful?
When/Why do you execute such searches?

Just looking to better understand the usecase so I know what problem the enhancement should solve.

**Comment by KaMyKaSii** [comment]
I use search to find files created by other apps. The search never failed for me, but even then it would be nice more units of time for more refined searches

**Comment by d4rken** [comment]
> Maybe a field where you select what kind of unit you want (minutes, hours, days, weeks, months...) and in the other you put the gross value.

We need multiple fields though right? Or how would we enter something like "1 day and 5 hours ago"?
