### ISSUE TITLE
Tasker support

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid#83]
Originally reported by: **Bitbucket: [d4rken](http://bitbucket.org/d4rken), GitHub: [d4rken](http://github.com/d4rken)**

---

Support for Tasker:
https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm

Offer SD Maids operation to be triggered externally through Tasker.

Docs here:
http://tasker.dinglisch.net/developers.html

---
- Bitbucket: https://bitbucket.org/d4rken/sd-maid/issue/84

**Comment by cyandotapps** [comment]
http://puu.sh/oJrta/fb2f8ab80d.png <=== I created a concept image of how the UI where you can choose the wanted operations, as reference how it could be done. You easily see it's a concept, since the fonts don't match.

**Comment by ezio84** [comment]
Hi! Tasker support would be nice, using AutoInput and Tasker atm isn't a good solution yet because the screen must be on and unlocked.

Thanks anyway for the great app.

**Comment by kantjer** [comment]
I second this request

**Comment by d4rken** [comment]
* How do you imagine this would be integrated? With an extra "SD Maid Tasker Plugin App"?
* What configurations would be possible?

**Comment by cyandotapps** [comment]
I imagine this being integrated into the app itself, because I actually think this would be the easiest way for you to do it.

The most useful thing I would love to see is an event being triggered, that can have for example Database optimizer, SystemCleaner, CorpseFinder, or any other module only search for files/databases to delete/optimize or actually scan and delete.

**Comment by d4rken** [comment]
I don't know yet how we can make this secure.
How can we prevent malicious apps from acting like tasker and commanding SD Maid to do malicious stuff?

**Comment by kantjer** [comment]
interesting point.
My idea was sending an intent but that could/would be insecure

**Comment by cyandotapps** [comment]
Well, the users chooses the event inside Tasker and MacroDroid, and an activity opens which let's the user choose which modules should do what. So malicious apps shouldn't be able to do malicious stuff using SD Maid.

**Comment by cyandotapps** [comment]
*the users choose

**Comment by ezio84** [comment]
Ye it'd be nice to have the possibility to run a specific task (or all tasks in the Rapid Access screen) scheduling it from Tasker instead of the SdMaid built-in scheduler. Just to have one single background process (Tasker) handling all scheduled operations on the phone.

**Comment by d4rken** [comment]
@cyandotapps What prevents a malicious app from doing that without a UI (because it already knows what malicious stuff it wants to do)?

@ezio84 Just using Tasker instead of SD Maids scheduler is not much reason for me to add this functionality, I'd rather spend the time on improving SD Maids scheduler then. Taking full advantage of SD Maid and Tasker, allowing Tasker to access AppControl, Explorer or Searcher, that would cool.

I don't think we can find out where an `Intent` originated from.
`Intent`'s don't require any special permission or user action. One could make a malicious app that works fine and in the background sends Intents to SD Maid. To the user it would look like SD Maid just went rogue.

Or am I miss understanding how tasker works? Tasker just sends intents with specific options in the extras to trigger 3rd party apps that support it?

**Comment by cyandotapps** [comment]
I'll describe what the user would see if you make a GUI for selecting what should be cleaned:
The user chooses the event to happen every hour. As soon as he/she (will be only he now to avoid slashes) taps it, a GUI by SD Maid opens, asking him to choose modules and if they should only scan or also clean automatically. The settings get saved in SD Maid.

What would happen if a malicious app tried to do it:
It triggers the intent, SD Maid asks the user to choose stuff that should be cleaned, but still needs an OK by the user itself.

**Comment by cyandotapps** [comment]
There are a few apps that would act like Tasker, such as MacroDroid and Locale, BTW.

**Comment by Ajaymamtora** [comment]
> I don't know yet how we can make this secure. How can we prevent malicious apps from acting like tasker and commanding SD Maid to do malicious stuff?

Do it the same way adguard does. Provide a key with the intent. Please can you add support.
