### ISSUE TITLE
Option to sort by `apparent size` instead of `size on disk`

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid#831]
See #830 

Allow changing which size value is used to sort items.

Not sure what to name the options though.

* Allocated size, size on disk
* File size, apparent size

**Comment by d4rken** [comment]
Seems like a semi workaround for #830, do we really need this?

**Comment by rishabhkohli** [comment]
File size, size on disk.
Windows does it right.

It might be a useful option for people with older devices who won't see many more updates.
