### ISSUE TITLE
Detect Link2SD'ed pathes

### ISSUE THREAD

**Issue by gsearle** [d4rken-org/sdmaid#870]
The "Duplicates" function flags all files found in linked directories created by apps such as Link2SD or FolderMount. For example, /storage/emulated/0/DCIM -> /storage/external_SD/DCIM. Is it possible to ignore these linked directories?

**Comment by d4rken** [comment]
Can show show me from a console e.g. "ls -l" what this looks like? Are these really symbolic links? Or is this a hardlink? Or a mount?

If possible please also mail me a log of the duplicates scan as described here:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

An option to not follow symlinks should be no problem, similar to the option for the Databases tool.

**Comment by d4rken** [comment]
The folders are mounted in multiple locations. I'm not sure how to fix this. Theoretically there is the option to not leave filesystem boundaries, but there are also legit cases of `/sdcard/external_sd` where the external sd is mounted nested in the internal.
This is tougher than symlinks too. For this type of scan SD Maid has 3 options of how to read files (java-file, DocumentFile and via shell) and I'm not sure which options besides reading via shell can detect "leaving the filesystem" ...

I'll look into whether this behavior could be detected, if that's not possible I'll look into adding an option.

As a workaround, exclusions do the trick though right?
https://github.com/d4rken/sdmaid-public/wiki/Exclusions

```
/dev/block/vold/179:65 /data/media/0/DCIM vfat rw,dirsync,nosuid,nodev,noexec,noatime,uid=1023,gid=1023,fmask=0007,dmask=0007,allow_utime=0020,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro 0 0
```

```
1493392150823 V/CheckSum: MD5 CHECKSUM is 5E77420A85B6C6B217D7B687134E5D93 (2ms) for '/storage/emulated/0/DCIM/.dbsu'
1493392150798 V/CheckSum: MD5 CHECKSUM is 5E77420A85B6C6B217D7B687134E5D93 (10ms) for '/storage/external_SD/DCIM/.dbsu'
```

```
770:directory:21:3084920936:0:1028:32768:512:64:1488401270:`/storage/emulated/0/DCIM'
770:regular file:24:3074082704:0:1028:82:512:64:1481896054:`/storage/external_SD/DCIM/.dbsu'
770:directory:24:3072564648:0:1028:32768:512:64:1488401270:`/storage/external_SD/DCIM'
770:regular file:21:3085205512:0:1028:82:512:64:1481896054:`/storage/emulated/0/DCIM/.dbsu'
```

**Comment by gsearle** [comment]
Ok, thanks for taking a look. Yes, I was able to set up exclusions and they are working fine.

BTW - The path to the file to turn on debug logging is incorrect on the web site. It shows the file inside the "logging" folder. Holding the "Settings" button and turning it on from there places it into the "files" folder.

Thanks!


-------- Original Message --------

**Comment by d4rken** [comment]
> BTW - The path to the file to turn on debug logging is incorrect on the web site. It shows the file inside the "logging" folder. Holding the "Settings" button and turning it on from there places it into the "files" folder.

Thanks! Changed:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug/_compare/3f803631e39f1e264d8f5430b260275ed8392963...3f120cd77aa9434f44808329f2897b92927fcf88
