### ISSUE TITLE
Feature Req: User Quality of Life: Select default landing page on Application Open

### ISSUE THREAD

**Issue by NeoBeum** [d4rken-org/sdmaid#911]
Adding an option in general settings to set the app to select one of the tools as a landing page for default instead of last used on exit would be nice.

This will prevent SD Maid from executing a search in App Control if the app opened and launched in this section.

**Comment by d4rken** [comment]
Just as a fix for the AppControl issue? Because that's a bug I just have not yet fixed (#784).

Or is there a usability issue with the open on last page concept?

**Comment by NeoBeum** [comment]
No there's no issue, last page is ok.
Just sometimes, I close on AppControl, but I always go to Quick or overview before i start doing anything

Maybe for later - "Default" option sets to last page opened, and the other options for each section

**Comment by NeoBeum** [comment]
Was the AppControl refresh  just fixed yesterday?

**Comment by d4rken** [comment]
I didn't make any changes to that specific functionality, so not intentionally.

**Comment by NeoBeum** [comment]
I think the spinner is fixed then, only refreshes on first load and button press. I'll play around and see

**Comment by NeoBeum** [comment]
I have another suggestion I just come across, I'll post in a new ticket

**Comment by NeoBeum** [comment]
the spinner is fixed, I installed 4.6.3 and checked

**Comment by NeoBeum** [comment]
and 4.7.3
