### ISSUE TITLE
Determining running apps on Android O without root

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid#946]
`getRunningServices` has been deprecated and only returns 1 app (us) now.

Might need to look into the `UsageStatsManager` again.

Did so for #527 but it wasn't a reliable solution...

A bad solution is better than none at all?

**Comment by NeoBeum** [comment]
is it possible to query open windows in background or not in focus?

**Comment by d4rken** [comment]
Nope.

**Comment by mbirth** [comment]
[SystemPanel2](https://play.google.com/store/apps/details?id=nextapp.sp) makes you grant proper permissions via adb commands for non-rooted devices. There's a tutorial in the app walking you through the process. Perhaps you could make something similar?

**Comment by d4rken** [comment]
![2017-06-14 16 47 15](https://user-images.githubusercontent.com/1439229/27144416-0864daec-5132-11e7-841e-b04f239c6520.png)

**Comment by d4rken** [comment]
Tried using the usage stats data as work around to determine running apps, but the data is quite (#527) inaccurate as it's often ~30seconds old, even on the highest interval settings. So it only works for long running processes.

Btw `android.permission.PACKAGE_USAGE_STATS` can be granted via system settings though, without requiring ADB.

Side note: https://stackoverflow.com/questions/28921136/how-to-check-if-android-permission-package-usage-stats-permission-is-given

Getting the data via dump ( `android.permission.DUMP`) is something I have not thought about and could work really well. The data we need only needs to be current for the moment we pull it, and a non async access (in contrast to usage stats) should work really well for our purposes.

**Comment by d4rken** [comment]
We probably want to use the output from `dumpsys activity processes`

```
ACTIVITY MANAGER RUNNING PROCESSES (dumpsys activity processes)
  All known processes:
  *APP* UID 10241 ProcessRecord{78e144a 17489:org.telegram.messenger/u0a241}
    user #0 uid=10241 gids={50241, 20241, 9997, 3002, 3003}
(...)
```

**Comment by NeoBeum** [comment]
I use Developers Mode to check active/inactive flags on apps, but I know that if an app has a running process, it does not immediately switch to inactive, but also always appears as active on first load of the page, you could use it as a secondary source gor verification?
![screenshot_20170615-165202](https://user-images.githubusercontent.com/12646422/27169875-fe9c2b3c-51ea-11e7-9612-7c7ff94a5bb0.png)

**Comment by d4rken** [comment]
How can we access this data through app code?

**Comment by NeoBeum** [comment]
I think Dev options is part of the settings framework, but I haven't looked at the API. I had a quick look in https://developer.android.com/studio/debug/dev-options.html but it wasn't detailed as the complete reference

**Comment by d4rken** [comment]
Also see #527

**Comment by d4rken** [comment]
#1588 added usage stats permission to SD Maid, time to evaluate this again.

**Comment by spicyfoxx** [comment]
Idea: Check if the app is using battery in background > The app is running.

**Comment by mcl21014** [comment]
Uncertain of what Android version changed this behavior.  Consider hiding the running apps option on unrooted devices but providing ADB as an option.

**Comment by mcl21014** [comment]
Android Nougat introduced this limitation.

**Comment by yaayesita** [comment]
> `getRunningServices` ha quedado en desuso y solo devuelve 1 aplicación (nosotros) ahora.
> 
> Puede que tenga que mirar de `UsageStatsManager`nuevo.
> 
> Lo hice para el [# 527](https://github.com/d4rken/sdmaid-public/issues/527) pero no fue una solución confiable ...
> 
> ¿Una mala solución es mejor que ninguna?

Si

**Comment by Sp1r1tdanc3r** [comment]
@d4rken are you the guy that's been hacking me all week and siphoning all my data and content into some mysterious void. I found you! Now you gotta help me finish this content and build an empire and make some money. Happy  synchronicity day! I'd leave my contact info but you know how to reach me. Ps I knew the mysterious trickbot trojan was an artist ...i knew it. Were you listening when I had that convo with you? Sd maid is soooooo much fun...I just have no idea what I'm doing.  K in NDA your fault. Does that mean I get to be your padawan cause you were messy and let a newb track you down by a trail of digital breadcrumbs and carbon footprints. Also....please pull the malware off of my friends who have been supporting my 45 year old ass midlife crises. They are sweet and helping me and since were partnered now...it would be swell. Please help me recover my 40 gb of content I was trying to edit and upload so I could start constructing a user journey and beginning a content calendar. But since I finally have some help let's get this going.

**Comment by Sp1r1tdanc3r** [comment]
Sd maid really is amazing did you do that all by yourself or are you on a team

**Comment by Sp1r1tdanc3r** [comment]
Also I don't code but I'm funny and a great DJ. Can I score the next project? I'm also quite the wordsmith when I remember to use commas

**Comment by Sp1r1tdanc3r** [comment]
Sorry one last thing....I've lost my 2 hour video masterpiece I made called "dance of the darken spirit" that i made right before getting evicted and moving into my kar..."kiki the kontent kruiser". Ismt it weird that 3 months ago I made a video with both our name in it? I'm basically an alchemist and a wizard. Told ya. Haoou synchronicity day. 
We are a team. We are 
d4rkenSp1r1t

**Comment by Sp1r1tdanc3r** [comment]
Oh no.....I think I may be violating a decorum. Forgive me everyone. I'm usually funny and a character on social media and this topic is way above my head. Forgive the intrusion

**Comment by d4rken** [comment]
Available in SD Maid SE with 3 methods for this: Root, Shizuku or UsageStats.
