### ISSUE TITLE
Don't show notifications about empty UninstallWatcher results

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid#960]
> The "Uninstall Watcher" feature under "Settings --> CorpseFinder" gives me notifications even when there are 0 items left behind by an uninstalled app. This is obviously unnecessary. Can you fix this please?

This could work as  the "working" notification still gives the user visual feedback that the UninstallWatcher was active.

**Comment by d4rken** [comment]
> Actually I think it would be best if the "Uninstall Watcher" just remained silent if no items were found. I prefer not having to clear a notification about this feature "working" every time I Uninstall an app with no items left behind. Unless, of course, you can make a specific "0 items were found" pop up notification that just disappear automatically after 1-3 seconds.

**Comment by najodleglejszy** [comment]
so, uh, any update on that? I was about to make a feature request for being able to disable the "0 items found" notification from showing.

**Comment by d4rken** [comment]
Still possible to do afaik, just wasn't high priority.

**Comment by dragonGod97677** [comment]
Can that be optional rather disabling it completely?

Disabled by default but can be re-enabled on CorpseFinder Settings page

**Comment by d4rken** [comment]
Technically yes, but adding a setting + glue code + text + translations for this quite simple setting seems too much.
I'd rather we agree on it one way or another, though as it has been like this for years, I would lean towards just keeping it the way it is. 🤔
